// Proxy client for Google Places API (New) address autocomplete.
// Two-step flow: suggestAddresses() while the user types, then
// retrieveSuggestedAddress() for the selected suggestion. The caller supplies a
// per-entry session token (UUIDv4, generated by the frontend); passing the same
// token through both steps groups them into one billable autocomplete session.
// Google ToS: autocomplete/place responses must not be cached or persisted —
// keep this client pass-through.

export const GOOGLE_PLACES_AUTOCOMPLETE_URL = "https://places.googleapis.com/v1/places:autocomplete";
export const GOOGLE_PLACES_DETAILS_URL_PREFIX = "https://places.googleapis.com/v1/places/";

// Snappier than the Census geocoder's 30s default: suggest runs on keystrokes,
// so a slow upstream should fail fast rather than stack up requests.
export const DEFAULT_GOOGLE_PLACES_TIMEOUT_MS = 8_000;

// Shared contract with the retrieve endpoint's validation: suggestions only
// surface place IDs that the retrieve step will accept, so a rendered
// suggestion can never dead-end with a 400 on selection. Google place IDs are
// base64url-shaped in practice; if Google ever widens its charset, widen this
// pattern (and the retrieve validation with it).
export const GOOGLE_PLACE_ID_PATTERN = /^[A-Za-z0-9_-]+$/;

const SUGGEST_FIELD_MASK =
  "suggestions.placePrediction.placeId,suggestions.placePrediction.text,suggestions.placePrediction.structuredFormat";
// addressComponents, not postalAddress: Google returns an empty postalAddress
// for postal_code places (verified live 2026-08-25 — place "Irwindale, CA
// 91706" came back with types=["postal_code"] and no postalAddress at all),
// while addressComponents always carries the postal_code component.
const RETRIEVE_FIELD_MASK = "formattedAddress,location,types,addressComponents";

// Google types that mark a suggestion as an area, not a deliverable address.
// Selecting one must NOT hand its centroid to the resolver as an exact point:
// the centroid's House/state-leg/school districts are not the visitor's
// (docs/plans/partial-address-scope.md). Server-side because the classification
// gates correctness — the client only renders it.
const REGION_PLACE_TYPES = new Set([
  // A bare road ("US 101", "Harlan Ave"): its point is an arbitrary spot
  // along the way, and long routes cross district lines.
  "route",
  "postal_code",
  "postal_code_prefix",
  "postal_code_suffix",
  "postal_town",
  "locality",
  "sublocality",
  "sublocality_level_1",
  "sublocality_level_2",
  "sublocality_level_3",
  "sublocality_level_4",
  "sublocality_level_5",
  "neighborhood",
  "colloquial_area",
  "school_district",
  "administrative_area_level_1",
  "administrative_area_level_2",
  "administrative_area_level_3",
  "administrative_area_level_4",
  "administrative_area_level_5",
  "administrative_area_level_6",
  "administrative_area_level_7",
  "country",
]);

export type GooglePlacesAutocompleteErrorCode =
  | "invalid_input"
  | "http_error"
  | "bad_response"
  | "network_error"
  | "timeout";

export class GooglePlacesAutocompleteError extends Error {
  readonly code: GooglePlacesAutocompleteErrorCode;

  constructor(code: GooglePlacesAutocompleteErrorCode, message: string) {
    super(message);
    this.name = "GooglePlacesAutocompleteError";
    this.code = code;
  }
}

export type GooglePlacesAutocompleteOptions = {
  apiKey: string;
  timeoutMs?: number;
  fetchImpl?: typeof fetch;
};

export type AddressSuggestion = {
  place_id: string;
  description: string;
  main_text: string;
  secondary_text: string;
};

export type RetrievedSuggestedAddress = {
  address: string;
  /** Place coordinates, or null when Google omits them — and always null for
   * coarse (zip/region) selections, so no client can submit an area centroid
   * as an exact point. Pass-through only — never cached or persisted
   * (Google ToS). */
  location: { lat: number; lng: number } | null;
  /** How specific the selected place is. "address": a deliverable address or
   * venue — today's behavior. "zip": a ZIP code — postal_code carries the
   * five digits for the partial-ballot flow. "region": any other area (city,
   * neighborhood, county, state) — the region partial-ballot flow. */
  granularity: "address" | "zip" | "region";
  /** Five-digit ZIP when granularity is "zip"; null otherwise. */
  postal_code: string | null;
  /** Two-letter state abbreviation for "region" selections, when Google's
   * administrative_area_level_1 component names one; null otherwise. Feeds
   * the resolve endpoint's region partial-ballot path. */
  state: string | null;
  /** The locality component's name for "region" selections ("Los Angeles"),
   * when present; null otherwise. Lets the resolver look for the matching
   * incorporated place's races. */
  locality: string | null;
};

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function truncate(text: string, max = 500): string {
  const trimmed = text.trim();
  if (trimmed.length <= max) {
    return trimmed;
  }
  return `${trimmed.slice(0, max)}...`;
}

function normalizeApiKey(apiKey: string): string {
  const normalized = apiKey.trim();
  if (normalized.length === 0) {
    throw new GooglePlacesAutocompleteError("invalid_input", "apiKey must not be empty");
  }
  return normalized;
}

function normalizeTimeoutMs(value: number | undefined): number {
  const timeoutMs = value ?? DEFAULT_GOOGLE_PLACES_TIMEOUT_MS;
  if (!Number.isInteger(timeoutMs) || timeoutMs <= 0) {
    throw new GooglePlacesAutocompleteError("invalid_input", `timeoutMs must be a positive integer, got ${timeoutMs}`);
  }
  return timeoutMs;
}

function normalizeRequiredInput(value: string, fieldName: string): string {
  const normalized = value.trim();
  if (normalized.length === 0) {
    throw new GooglePlacesAutocompleteError("invalid_input", `${fieldName} must not be empty`);
  }
  return normalized;
}

function isAbortError(error: unknown): boolean {
  return (
    (error instanceof DOMException && error.name === "AbortError") ||
    (error instanceof Error && error.name === "AbortError")
  );
}

async function fetchGooglePlacesJson(
  url: string,
  init: { method: "GET" | "POST"; headers: Record<string, string>; body?: string },
  options: GooglePlacesAutocompleteOptions
): Promise<unknown> {
  const timeoutMs = normalizeTimeoutMs(options.timeoutMs);
  const fetchImpl = options.fetchImpl ?? globalThis.fetch;
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), timeoutMs);

  try {
    const response = await fetchImpl(url, {
      ...init,
      redirect: "follow",
      signal: controller.signal,
    });
    const bodyText = await response.text();

    if (!response.ok) {
      throw new GooglePlacesAutocompleteError(
        "http_error",
        `Google Places request failed: status=${response.status} ${response.statusText}; body=${truncate(bodyText)}`
      );
    }

    try {
      return JSON.parse(bodyText) as unknown;
    } catch {
      throw new GooglePlacesAutocompleteError(
        "bad_response",
        `Google Places returned non-JSON response; body=${truncate(bodyText)}`
      );
    }
  } catch (error) {
    if (isAbortError(error)) {
      throw new GooglePlacesAutocompleteError("timeout", `Google Places request timed out after ${timeoutMs}ms`);
    }
    if (error instanceof GooglePlacesAutocompleteError) {
      throw error;
    }
    // Node fetch surfaces DNS/connection failures as plain TypeError; wrap them
    // so the API layer maps them to 503 instead of the generic TypeError->400.
    throw new GooglePlacesAutocompleteError(
      "network_error",
      `Google Places request failed: ${error instanceof Error ? error.message : String(error)}`
    );
  } finally {
    clearTimeout(timeout);
  }
}

function parseLocalizedText(value: unknown): string {
  if (!isRecord(value) || typeof value.text !== "string") {
    return "";
  }
  return value.text.trim();
}

function parseSuggestion(value: unknown): AddressSuggestion | null {
  if (!isRecord(value) || !isRecord(value.placePrediction)) {
    return null;
  }
  const prediction = value.placePrediction;
  const placeId = typeof prediction.placeId === "string" ? prediction.placeId.trim() : "";
  const description = parseLocalizedText(prediction.text);
  if (!GOOGLE_PLACE_ID_PATTERN.test(placeId) || description.length === 0) {
    return null;
  }
  const structuredFormat = isRecord(prediction.structuredFormat) ? prediction.structuredFormat : {};
  return {
    place_id: placeId,
    description,
    main_text: parseLocalizedText(structuredFormat.mainText) || description,
    secondary_text: parseLocalizedText(structuredFormat.secondaryText),
  };
}

export function parseGooglePlacesSuggestPayload(payload: unknown): AddressSuggestion[] {
  if (!isRecord(payload)) {
    throw new GooglePlacesAutocompleteError("bad_response", "Google Places autocomplete response is not a JSON object");
  }
  // Google omits `suggestions` entirely when nothing matches.
  if (payload.suggestions === undefined) {
    return [];
  }
  if (!Array.isArray(payload.suggestions)) {
    throw new GooglePlacesAutocompleteError("bad_response", "Google Places autocomplete suggestions is not an array");
  }
  return payload.suggestions
    .map(parseSuggestion)
    .filter((suggestion): suggestion is AddressSuggestion => suggestion !== null);
}

export async function suggestAddressesWithGooglePlaces(
  input: { input: string; sessionToken: string },
  options: GooglePlacesAutocompleteOptions
): Promise<AddressSuggestion[]> {
  const apiKey = normalizeApiKey(options.apiKey);
  const normalizedInput = normalizeRequiredInput(input.input, "input");
  const sessionToken = normalizeRequiredInput(input.sessionToken, "sessionToken");

  const payload = await fetchGooglePlacesJson(
    GOOGLE_PLACES_AUTOCOMPLETE_URL,
    {
      method: "POST",
      headers: {
        "content-type": "application/json",
        "x-goog-api-key": apiKey,
        "x-goog-fieldmask": SUGGEST_FIELD_MASK,
      },
      body: JSON.stringify({
        input: normalizedInput,
        sessionToken,
        includedRegionCodes: ["us"],
      }),
    },
    options
  );

  return parseGooglePlacesSuggestPayload(payload);
}

export function parseGooglePlacesRetrievePayload(payload: unknown): RetrievedSuggestedAddress {
  if (!isRecord(payload) || typeof payload.formattedAddress !== "string" || payload.formattedAddress.trim().length === 0) {
    throw new GooglePlacesAutocompleteError("bad_response", "Google Places details response is missing formattedAddress");
  }
  // Absent or malformed types classify as "address" (the response is still a
  // retrieved place the string path can geocode) but fail CLOSED on the
  // location below: the type list is what proves coordinates are safe to
  // treat as an exact point, so no proof means no coordinates.
  const types = Array.isArray(payload.types)
    ? payload.types.filter((entry): entry is string => typeof entry === "string")
    : [];
  const isRegion = types.some((entry) => REGION_PLACE_TYPES.has(entry));
  let granularity: RetrievedSuggestedAddress["granularity"] = isRegion ? "region" : "address";
  let postalCode: string | null = null;
  const components = Array.isArray(payload.addressComponents) ? payload.addressComponents : [];
  const componentText = (componentType: string, field: "longText" | "shortText"): string | null => {
    for (const component of components) {
      if (
        isRecord(component) &&
        Array.isArray(component.types) &&
        component.types.includes(componentType) &&
        typeof component[field] === "string"
      ) {
        const text = component[field].trim();
        if (text.length > 0) {
          return text;
        }
      }
    }
    return null;
  };
  if (isRegion && types.includes("postal_code")) {
    // The ZIP lives in the postal_code address component (its value may carry
    // ZIP+4; the partial-ballot flow works on the five-digit ZCTA). A
    // missing/odd value downgrades to "region" rather than inventing a ZIP.
    const rawPostalCode = componentText("postal_code", "longText");
    const match = rawPostalCode === null ? null : /^(\d{5})(?:-\d{4})?$/.exec(rawPostalCode);
    if (match) {
      granularity = "zip";
      postalCode = match[1];
    }
  }

  // Region selections carry the state (and locality, when Google names one)
  // so the resolve endpoint can serve the region partial ballot. Shape-checked
  // here; the resolver validates membership in the covered 50 states + DC.
  let state: string | null = null;
  let locality: string | null = null;
  if (granularity === "region") {
    const rawState = componentText("administrative_area_level_1", "shortText");
    state = rawState !== null && /^[A-Z]{2}$/.test(rawState) ? rawState : null;
    // Only when the selection IS a locality: a neighborhood or sublocality
    // pick also carries a locality component, but those areas can straddle
    // city lines — offering the containing city's races would show some
    // residents someone else's ballot. Such picks stay statewide only.
    locality = types.includes("locality") ? componentText("locality", "longText") : null;
  }

  // location is best-effort: a missing or malformed one must not fail the
  // retrieve — the resolver falls back to the address-string path without it.
  // Range-checked with the same bounds the resolve validator enforces, so a
  // bad value dies here as null instead of 400ing the whole search later.
  // Coarse selections never return one (see RetrievedSuggestedAddress), and
  // neither does a response with no usable types — unverifiable coordinates
  // must not become an exact point.
  let location: RetrievedSuggestedAddress["location"] = null;
  if (granularity === "address" && types.length > 0 && isRecord(payload.location)) {
    const { latitude, longitude } = payload.location;
    if (
      typeof latitude === "number" &&
      typeof longitude === "number" &&
      Number.isFinite(latitude) &&
      Number.isFinite(longitude) &&
      latitude >= -90 &&
      latitude <= 90 &&
      longitude >= -180 &&
      longitude <= 180
    ) {
      location = { lat: latitude, lng: longitude };
    }
  }
  return { address: payload.formattedAddress.trim(), location, granularity, postal_code: postalCode, state, locality };
}

export async function retrieveSuggestedAddressWithGooglePlaces(
  input: { placeId: string; sessionToken: string },
  options: GooglePlacesAutocompleteOptions
): Promise<RetrievedSuggestedAddress> {
  const apiKey = normalizeApiKey(options.apiKey);
  const placeId = normalizeRequiredInput(input.placeId, "placeId");
  const sessionToken = normalizeRequiredInput(input.sessionToken, "sessionToken");

  const url = new URL(`${GOOGLE_PLACES_DETAILS_URL_PREFIX}${encodeURIComponent(placeId)}`);
  url.searchParams.set("sessionToken", sessionToken);

  const payload = await fetchGooglePlacesJson(
    url.toString(),
    {
      method: "GET",
      headers: {
        "x-goog-api-key": apiKey,
        "x-goog-fieldmask": RETRIEVE_FIELD_MASK,
      },
    },
    options
  );

  return parseGooglePlacesRetrievePayload(payload);
}
