// Proxy client for Google Places API (New) address autocomplete.
// Two-step flow: suggestAddresses() while the user types, then
// retrieveSuggestedAddress() for the selected suggestion. The caller supplies a
// per-entry session token (UUIDv4, generated by the frontend); passing the same
// token through both steps groups them into one billable autocomplete session.
// Google ToS: autocomplete/place responses must not be cached or persisted —
// keep this client pass-through.

export const GOOGLE_PLACES_AUTOCOMPLETE_URL = "https://places.googleapis.com/v1/places:autocomplete";
export const GOOGLE_PLACES_DETAILS_URL_PREFIX = "https://places.googleapis.com/v1/places/";

// Snappier than the Census geocoder's 30s default: suggest runs on keystrokes,
// so a slow upstream should fail fast rather than stack up requests.
export const DEFAULT_GOOGLE_PLACES_TIMEOUT_MS = 8_000;

// Shared contract with the retrieve endpoint's validation: suggestions only
// surface place IDs that the retrieve step will accept, so a rendered
// suggestion can never dead-end with a 400 on selection. Google place IDs are
// base64url-shaped in practice; if Google ever widens its charset, widen this
// pattern (and the retrieve validation with it).
export const GOOGLE_PLACE_ID_PATTERN = /^[A-Za-z0-9_-]+$/;

const SUGGEST_FIELD_MASK =
  "suggestions.placePrediction.placeId,suggestions.placePrediction.text,suggestions.placePrediction.structuredFormat";
const RETRIEVE_FIELD_MASK = "formattedAddress";

export type GooglePlacesAutocompleteErrorCode =
  | "invalid_input"
  | "http_error"
  | "bad_response"
  | "network_error"
  | "timeout";

export class GooglePlacesAutocompleteError extends Error {
  readonly code: GooglePlacesAutocompleteErrorCode;

  constructor(code: GooglePlacesAutocompleteErrorCode, message: string) {
    super(message);
    this.name = "GooglePlacesAutocompleteError";
    this.code = code;
  }
}

export type GooglePlacesAutocompleteOptions = {
  apiKey: string;
  timeoutMs?: number;
  fetchImpl?: typeof fetch;
};

export type AddressSuggestion = {
  place_id: string;
  description: string;
  main_text: string;
  secondary_text: string;
};

export type RetrievedSuggestedAddress = {
  address: string;
};

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function truncate(text: string, max = 500): string {
  const trimmed = text.trim();
  if (trimmed.length <= max) {
    return trimmed;
  }
  return `${trimmed.slice(0, max)}...`;
}

function normalizeApiKey(apiKey: string): string {
  const normalized = apiKey.trim();
  if (normalized.length === 0) {
    throw new GooglePlacesAutocompleteError("invalid_input", "apiKey must not be empty");
  }
  return normalized;
}

function normalizeTimeoutMs(value: number | undefined): number {
  const timeoutMs = value ?? DEFAULT_GOOGLE_PLACES_TIMEOUT_MS;
  if (!Number.isInteger(timeoutMs) || timeoutMs <= 0) {
    throw new GooglePlacesAutocompleteError("invalid_input", `timeoutMs must be a positive integer, got ${timeoutMs}`);
  }
  return timeoutMs;
}

function normalizeRequiredInput(value: string, fieldName: string): string {
  const normalized = value.trim();
  if (normalized.length === 0) {
    throw new GooglePlacesAutocompleteError("invalid_input", `${fieldName} must not be empty`);
  }
  return normalized;
}

function isAbortError(error: unknown): boolean {
  return (
    (error instanceof DOMException && error.name === "AbortError") ||
    (error instanceof Error && error.name === "AbortError")
  );
}

async function fetchGooglePlacesJson(
  url: string,
  init: { method: "GET" | "POST"; headers: Record<string, string>; body?: string },
  options: GooglePlacesAutocompleteOptions
): Promise<unknown> {
  const timeoutMs = normalizeTimeoutMs(options.timeoutMs);
  const fetchImpl = options.fetchImpl ?? globalThis.fetch;
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), timeoutMs);

  try {
    const response = await fetchImpl(url, {
      ...init,
      redirect: "follow",
      signal: controller.signal,
    });
    const bodyText = await response.text();

    if (!response.ok) {
      throw new GooglePlacesAutocompleteError(
        "http_error",
        `Google Places request failed: status=${response.status} ${response.statusText}; body=${truncate(bodyText)}`
      );
    }

    try {
      return JSON.parse(bodyText) as unknown;
    } catch {
      throw new GooglePlacesAutocompleteError(
        "bad_response",
        `Google Places returned non-JSON response; body=${truncate(bodyText)}`
      );
    }
  } catch (error) {
    if (isAbortError(error)) {
      throw new GooglePlacesAutocompleteError("timeout", `Google Places request timed out after ${timeoutMs}ms`);
    }
    if (error instanceof GooglePlacesAutocompleteError) {
      throw error;
    }
    // Node fetch surfaces DNS/connection failures as plain TypeError; wrap them
    // so the API layer maps them to 503 instead of the generic TypeError->400.
    throw new GooglePlacesAutocompleteError(
      "network_error",
      `Google Places request failed: ${error instanceof Error ? error.message : String(error)}`
    );
  } finally {
    clearTimeout(timeout);
  }
}

function parseLocalizedText(value: unknown): string {
  if (!isRecord(value) || typeof value.text !== "string") {
    return "";
  }
  return value.text.trim();
}

function parseSuggestion(value: unknown): AddressSuggestion | null {
  if (!isRecord(value) || !isRecord(value.placePrediction)) {
    return null;
  }
  const prediction = value.placePrediction;
  const placeId = typeof prediction.placeId === "string" ? prediction.placeId.trim() : "";
  const description = parseLocalizedText(prediction.text);
  if (!GOOGLE_PLACE_ID_PATTERN.test(placeId) || description.length === 0) {
    return null;
  }
  const structuredFormat = isRecord(prediction.structuredFormat) ? prediction.structuredFormat : {};
  return {
    place_id: placeId,
    description,
    main_text: parseLocalizedText(structuredFormat.mainText) || description,
    secondary_text: parseLocalizedText(structuredFormat.secondaryText),
  };
}

export function parseGooglePlacesSuggestPayload(payload: unknown): AddressSuggestion[] {
  if (!isRecord(payload)) {
    throw new GooglePlacesAutocompleteError("bad_response", "Google Places autocomplete response is not a JSON object");
  }
  // Google omits `suggestions` entirely when nothing matches.
  if (payload.suggestions === undefined) {
    return [];
  }
  if (!Array.isArray(payload.suggestions)) {
    throw new GooglePlacesAutocompleteError("bad_response", "Google Places autocomplete suggestions is not an array");
  }
  return payload.suggestions
    .map(parseSuggestion)
    .filter((suggestion): suggestion is AddressSuggestion => suggestion !== null);
}

export async function suggestAddressesWithGooglePlaces(
  input: { input: string; sessionToken: string },
  options: GooglePlacesAutocompleteOptions
): Promise<AddressSuggestion[]> {
  const apiKey = normalizeApiKey(options.apiKey);
  const normalizedInput = normalizeRequiredInput(input.input, "input");
  const sessionToken = normalizeRequiredInput(input.sessionToken, "sessionToken");

  const payload = await fetchGooglePlacesJson(
    GOOGLE_PLACES_AUTOCOMPLETE_URL,
    {
      method: "POST",
      headers: {
        "content-type": "application/json",
        "x-goog-api-key": apiKey,
        "x-goog-fieldmask": SUGGEST_FIELD_MASK,
      },
      body: JSON.stringify({
        input: normalizedInput,
        sessionToken,
        includedRegionCodes: ["us"],
      }),
    },
    options
  );

  return parseGooglePlacesSuggestPayload(payload);
}

export function parseGooglePlacesRetrievePayload(payload: unknown): RetrievedSuggestedAddress {
  if (!isRecord(payload) || typeof payload.formattedAddress !== "string" || payload.formattedAddress.trim().length === 0) {
    throw new GooglePlacesAutocompleteError("bad_response", "Google Places details response is missing formattedAddress");
  }
  return { address: payload.formattedAddress.trim() };
}

export async function retrieveSuggestedAddressWithGooglePlaces(
  input: { placeId: string; sessionToken: string },
  options: GooglePlacesAutocompleteOptions
): Promise<RetrievedSuggestedAddress> {
  const apiKey = normalizeApiKey(options.apiKey);
  const placeId = normalizeRequiredInput(input.placeId, "placeId");
  const sessionToken = normalizeRequiredInput(input.sessionToken, "sessionToken");

  const url = new URL(`${GOOGLE_PLACES_DETAILS_URL_PREFIX}${encodeURIComponent(placeId)}`);
  url.searchParams.set("sessionToken", sessionToken);

  const payload = await fetchGooglePlacesJson(
    url.toString(),
    {
      method: "GET",
      headers: {
        "x-goog-api-key": apiKey,
        "x-goog-fieldmask": RETRIEVE_FIELD_MASK,
      },
    },
    options
  );

  return parseGooglePlacesRetrievePayload(payload);
}
