# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"

reviews:
  profile: "chill"
  auto_review:
    enabled: true
    drafts: false
  review_status: true

chat:
  auto_reply: true
