CLOSE = {
 1546456: "The Alaska House accepted the Senate's changes 21-16, but the governor vetoed it and the override fell short.",
 1546119: "The Alaska Senate passed it 11-9, but the governor vetoed it and the override fell short.",
 1562693: "The Alaska House accepted the Senate's changes 31-8, the legislature overrode the governor's veto 46-14, and it became law.",
 1567929: "The Alaska House passed it 26-14, but the governor vetoed it and the override fell short.",
 1548818: "The Alaska Senate passed it 16-4, but the governor vetoed it and the override fell short.",
 1699131: "The Alaska House passed it 27-13, but the governor vetoed it and the override fell short.",
 1699385: "The Alaska House accepted the Senate's changes 26-14, but the governor vetoed it and the override fell short.",
 1699781: "The Alaska House passed it 31-9, but the governor vetoed it and the override fell short.",
}
EFFECTS = {
 "HB 69": "a bill to raise the per-student school funding allocation from $5,960 to $6,960",
 "HB 57": "which raises the per-student school funding allocation from $5,960 to $6,660",
 "HB 58": "a bill to let the governor pick the head of the Office of Public Advocacy",
 "SB 113": "a bill to tax multistate companies on where their customers are instead of where they work",
 "HB 33": "which changes the ethics rules for members of the Board of Fisheries and Board of Game",
 "SB 183": "which gives the Legislative Budget and Audit Committee more power to get records",
 "HB 35": "which lets prisoners keep an approved computer or tablet in their cell",
 "HB 48": "which raises the ceiling on money for the civil legal services fund for low-income people",
 "HB 20": "a bill to stop businesses charging extra for a paper bill or notice",
 "HB 26": "a bill to make the state write a transit plan for the whole of Alaska",
 "SB 41": "a bill to add mental health to the health lessons schools are urged to teach",
 "HB 184": "which lets the state development bank help pay for building workforce housing",
 "HB 10": "a bill to add a tenured professor seat to the University of Alaska Board of Regents",
 "HB 52": "a bill to give children in psychiatric hospitals weekly private contact with a parent",
 "SB 21": "a bill to create a state retirement savings plan called Alaska Work and Save",
 "HB 133": "a bill to give the state a deadline to pay its bills, with interest after that",
 "HB 27": "which tells the state education department to write lessons on hands-only CPR",
 "SB 24": "a bill to raise the tobacco and vaping age from 19 to 21 and tax throwaway vapes",
 "HB 25": "a bill to stop restaurants serving food in polystyrene foam containers",
 "SB 258": "a bill to bar state software contracts from limiting which computers the state may use",
 "HB 280": "a bill to tax multistate companies on where their customers are instead of where they work",
 "SB 111": "a bill to give owners and independent shops a right to repair everyday electronics",
 "SB 250": "a bill to make large data centers pay for the power and gas lines built to serve them",
}
