EFFECTS = {
 "HB 212": "the Anti-Road Rage Act, which bars staying in the interstate fast lane more than a mile and a half without passing",
 "HB 233": "a bill to flag voters who may have moved using postal and other records",
 "HB 361": "the Fantasy Contests Act, which legalized paid fantasy sports with registration, age checks and a tax",
 "HB 380": "which rebuilt the parole system, setting how much of a sentence must be served before parole",
 "SB 193": "which cut unemployment pay from 26 weeks to 14 and raised the weekly maximum by $10",
 "HB 491": "called Gianna's Law, a bill to require doctors to try to save a child born alive after an abortion",
 "SB 69": "which abolished the marriage license, replacing it with sworn statements filed with the probate judge",
 "HB 498": "which made every public college adopt a free expression policy and banned free speech zones",
 "SB 397": "which asked voters to replace the elected State Board of Education with an appointed commission",
 "HB 209": "which lets a retired officer with 20 years of service serve as an armed school resource officer",
 "HB 147": "which barred cities from starting new taxes on what people earn at work",
 "HB 34": "a bill to make impounding a car optional when police stop an unlicensed driver",
 "HB 24": "a bill to let some nonviolent prisoners ask to be sentenced again under newer guidelines",
 "HB 385": "which rewrote sex education, deleting the rule that classes call homosexuality unacceptable",
 "HB 103": "which lets businesses and churches stay open during a disease emergency if they follow safety rules",
 "HB 404": "which let college athletes be paid for the use of their name, image or likeness",
 "HB 246": "which let schools teach yoga again, with English pose names and no chanting or namaste",
 "HB 72": "a bill to shorten supervised release for the longest prison sentences",
 "HB 184": "a bill to make reporting to the state immunization registry compulsory",
 "HB 391": "which barred transgender girls from girls' school sports",
 "HB 445": "the Anti-Aggravated Riot Act, which created new crimes around protests with mandatory jail time",
 "HB 285": "which banned curbside voting, requiring every voting machine to sit inside a named building",
 "HB 90": "called CiCi and Jay's Law, a bill to ban holding a phone while driving",
 "HB 388": "which asked voters to require a six-month wait before new election rules take effect",
 "SB 308": "which made sheriffs approve concealed carry permits unless one of eleven listed reasons applies",
 "SB 107": "which froze city police jurisdictions at their 2021 boundaries and shrank planning jurisdictions",
 "SB 117": "which let people clear old misdemeanor and some felony convictions from their record",
 "HB 239": "a bill to raise the penalty for causing injury or death while fleeing police",
 "HB 238": "a bill to suspend boating certificates for boating or driving under the influence",
 "HB 631": "which set up reservoir upkeep grants paid for by a $5 yearly fee on every registered boat",
 "HB 202": "a bill to free grand jury witnesses to talk about their own testimony",
 "HB 273": "which raised the tobacco and vaping age from 19 to 21 and banned candy-style vape packaging",
 "SB 46": "the Compassion Act, which created a medical cannabis program for 16 listed conditions",
 "SB 323": "which let prisoners earn up to 12 months off a sentence by finishing education programs",
 "SB 94": "a bill to delay by two years the rule holding back third graders who cannot read well enough",
 "HB 52": "which gave judges more room over how much of a split sentence to impose after a probation breach",
 "HB 2": "the Anti-Aggravated Riot Act, which created new crimes around protests with mandatory jail time",
 "HB 272": "which let Alabamians carry a concealed handgun without a permit",
 "HB 194": "which barred election officials from taking private money to run elections",
 "HB 312": "a bill to bar teaching a listed set of divisive ideas about race, sex and religion",
 "HB 63": "a bill to ban handing someone a part-filled voter registration or absentee form",
 "HB 230": "which banned leg and waist restraints on pregnant prisoners during pregnancy, labor and six weeks after birth",
 "SB 171": "the Alabama Numeracy Act, which overhauled early grade math with 60 minutes a day and twice-yearly screening",
 "HB 337": "a bill to raise the penalties for fleeing police",
 "SB 224": "which requires people claiming unemployment pay to contact three employers a week with proof",
 "SB 2": "the Alabama Second Amendment Protection Act, which barred enforcing presidential orders limiting guns",
 "SB 184": "which made it a felony to give a minor puberty blockers, cross-sex hormones or gender surgery",
 "HB 95": "which gave prisoners a break from court fines and fees just after release, with a repayment plan",
 "SB 38": "a bill to ask voters to fold the State Auditor's office into the State Treasurer's",
 "SB 255": "a bill to require the Governor's approval before a state health order could take effect",
 "HB 322": "which requires students to use the school restroom matching the sex on their original birth certificate",
 "SB 313": "which barred officials from spending public money to campaign for or against a ballot measure",
 "HB 5": "which put $400 million of federal pandemic relief money into building two men's prisons",
 "HB 6": "which put $154 million of state money into prisons",
 "HB 4": "which let the state borrow up to $785 million to build prisons",
 "HB 1": "which redrew Alabama's seven U.S. House districts using the 2020 census",
 "SB 1": "which redrew the 35 Alabama Senate districts using the 2020 census",
 "SB 15": "which requires a parent's written consent before a minor may get a COVID-19 vaccine",
 "SB 9": "which requires employers who mandate COVID-19 vaccination to let workers claim an exemption",
 "HB 131": "which stops the parole board considering a prisoner who is facing a new criminal charge",
 "SB 10": "which bars vote counting machines that can go online or contain modem technology",
 "HB 379": "the Alabama Property Protection Act, which bars listed foreign governments from buying Alabama land",
 "HB 363": "which changed how public charter schools are overseen and funded in their first year",
 "HB 229": "a bill to let some prisoners sentenced under the habitual felony offender law seek resentencing",
 "HB 392": "a bill to make federal gun bans a state crime",
 "SB 278": "which set up a state loan fund for colleges in financial trouble",
 "SB 206": "the Retail Theft Crime Prevention Act, which made stealing over $2,500 of goods a Class B felony",
 "SB 261": "which barred government contracts with companies that boycott fossil fuels, timber, farming or guns",
 "SB 301": "which made it an offense to hold a phone while driving badly, with fines up to $150",
 "HB 129": "the CHOOSE Act, which pays families $7,000 per child toward private school costs through tax credits",
 "SB 129": "which shut down diversity, equity and inclusion offices in state agencies, schools and public colleges",
 "HB 22": "which called for an assistant principal in every public school and set out the job",
 "HB 111": "a bill to write fixed meanings for male and female into every Alabama law",
 "HB 130": "a bill to widen limits on classroom talk about sexual orientation and gender identity up to eighth grade",
 "HB 36": "a bill to make having a pistol fitted with a machine gun conversion part a Class C felony",
 "HB 195": "a bill to make school sex education teach that avoiding sex outside marriage is best",
 "HB 356": "the Pregnancy Resource Act, a bill to give a state income tax credit for gifts to pregnancy centers",
 "HB 151": "a bill to ask voters to allow a school lottery, electronic gaming sites and a tribal gaming deal",
 "HB 152": "a bill to set the rules for gambling in Alabama if voters approved it",
 "SB 186": "which banned ranked-choice voting in Alabama",
 "SB 231": "which cut off state business incentives for employers that recognize a union without a secret ballot",
 "HB 29": "a bill to make unemployment claimants in larger counties contact five employers a week",
 "SB 116": "which made it a crime to have, sell or use a part that turns a pistol into a machine gun",
 "HB 30": "a bill to make probate judges audit one precinct's ballots after every general election",
 "HB 234": "called Alyssa's Law, a bill to give school staff wearable panic buttons that call police",
 "HB 357": "which taxed heated tobacco products at about half the cigarette rate",
 "HB 7": "the Laken Riley Act, a bill to let state and local police enforce federal immigration law by agreement",
 "HB 247": "the Gulf of America Act, a bill to rename the Gulf of Mexico in Alabama law",
 "HB 8": "which limited unauthorized vapes to licensed vape stores that keep out anyone under 21",
 "SB 71": "which stops state agencies setting pollution limits tougher than federal rules",
 "HB 360": "a bill to create a yearly sales tax holiday for guns, ammunition and hunting supplies",
 "HB 86": "which makes the parole board weigh a prisoner's work and education when deciding on release",
 "HB 475": "the Power to the People Act, which freezes electric base rates until 2029 and bars billing customers for lobbying",
 "SB 57": "which tells Alabama to seek federal permission to stop candy and soda being bought with SNAP benefits",
 "SB 5": "which asks voters to require every public school to play the national anthem at least once a week",
 "SB 341": "which lets Alabama try speed cameras in one interstate work zone",
 "SB 119": "a bill to end Common Core standards in Alabama schools",
 "SB 22": "a bill to let taxpayers send part of a state refund to a private border wall group",
 "SB 222": "a bill to end the election of county school superintendents",
 "SB 220": "a bill to ask voters to allow a paper-ticket state lottery",
 "SB 128": "which made photographing someone else's ballot at a polling place a misdemeanor",
 "SB 236": "which set up a commission to study medical marijuana and extended Carly's Law by a year",
 "HB 423": "a bill to make kindergarten compulsory",
 "SB 165": "the Compassion Act, a bill to create a medical cannabis program for 16 listed conditions",
 "SB 158": "a bill to build a statewide database of police misconduct",
 "SB 214": "a bill to ask voters to allow a lottery, five casinos and sports betting",
 "SB 97": "a bill to end most states of emergency after 45 days unless the Legislature extends them",
 "SB 319": "a second bill to ask voters to allow a lottery, casinos and sports betting",
 "SB 91": "a bill to ban racial profiling in traffic stops and require data collection",
 "HB 123": "which let prosecutors, judges, legislators and police keep their details off the public voter list",
 "HB 116": "the Alabama Voter Confidence Act, which allowed one trial audit of the 2022 general election",
 "HB 154": "which requires every campaign finance report to be filed electronically in a public database",
 "SB 168": "which made fentanyl test strips legal",
 "SB 26": "the Agent Billy Clardy III Act, a bill to give Alabama its own wiretap power for felony drug cases",
 "SB 79": "a bill to set statewide fair-hearing rules for school discipline",
 "SB 200": "which delayed by two years the rule holding back third graders who cannot read well enough",
 "SB 51": "a bill to require every school system to employ a mental health service coordinator",
 "SB 181": "a bill to set statewide fair-hearing rules for students facing suspension or expulsion",
 "SB 263": "which widened the tax-credit scholarship program and raised its yearly cap to $40 million",
 "HB 125": "a mid-year spending bill adding $207.6 million from the general fund and $10 million for veterans",
 "HB 289": "which set out who may see police body camera and dashboard camera video",
 "SB 63": "which bars releasing a person in the country illegally until police take fingerprints and DNA",
 "SB 53": "which made knowingly bringing a person into Alabama who is in the country illegally a felony",
 "HB 165": "which made Juneteenth an official state holiday",
 "HB 580": "which limits faculty senates at public colleges to an advisory role and sets state tenure rules",
}
