EFFECTS = {
 "SB 3": "which bars state and local government from treating anyone better or worse because of race, sex or ethnicity",
 "HB 1222": "which lets the Attorney General reject a ballot measure that clashes with federal law",
 "SB 207": "which makes petition canvassers warn each signer out loud that petition fraud is a crime",
 "SB 211": "which makes every petition canvasser file a sworn statement of compliance with the Secretary of State",
 "SB 208": "which makes petition canvassers check a signer's photo ID before taking their name",
 "HB 1489": "which lets Arkansas carry out a death sentence with nitrogen gas as well as lethal injection",
 "HB 1503": "which makes cities allow at least one accessory dwelling unit on a single-family lot",
 "SB 296": "which requires the county clerk's early voting site to sit in the county seat",
 "SB 209": "which throws out every signature a canvasser collected if that canvasser broke petition law",
 "SB 210": "which requires petition signers to read or hear the ballot title in front of the canvasser",
 "HB 1713": "which bars ballot titles written above an eighth-grade reading level",
 "SB 366": "which creates a grant program to strengthen owner-occupied homes against wind and hail",
 "HB 1365": "which strips race and sex requirements from the membership of about twenty state boards",
 "SB 433": "which requires a Ten Commandments poster in every public classroom, library and tax-funded building",
 "HB 1965": "which sets up grants and loans to help food shops open where fresh food is hard to buy",
 "HB 1627": "which makes property tax bills tell taxpayers about relief for older and disabled homeowners",
 "HB 1017": "which makes the state pay the whole cost of 12 weeks of maternity leave for public school staff",
 "SB 446": "which lets private landowners and businesses use automatic license plate readers",
 "SB 426": "the Defense Against Criminal Illegals Act, which adds prison time for violent crimes by people here illegally",
 "HB 1945": "which lets students transfer to another public school inside their own district",
 "HB 1974": "which tells government employers to check new hires through E-Verify",
 "HB 1866": "Eli's Law, which requires audio recording devices in every school locker room from the 2027-2028 school year",
 "SB 584": "which applies statewide ballot petition rules to county and city petitions",
 "SB 551": "which adds fraud warnings and ID checks to petitions for local votes on alcohol sales",
 "SB 406": "which bars recording a deed unless the person giving up the land shows photo ID",
 "SB 520": "which bars counties, cities and towns from running a diversity, equity and inclusion program",
 "SB 364": "which lets an unlicensed contractor sue a customer for the value of the work after paying fines",
 "SB 640": "which ends the terms of every State Library Board member and lets the Governor appoint replacements",
 "SJR 15": "a proposed constitutional amendment letting lawmakers create economic development districts with public loans",
 "SB 486": "which defines sex by biology and requires shared restrooms and sleeping rooms to be set aside for one sex",
 "SB 638": "which makes motorboat buyers pay sales tax to the state at registration instead of to the dealer",
 "SB 591": "a standby law barring abortions sought because of the race of the fetus, not yet in force",
 "HB 1221": "which voids petition signatures collected after the next general election following approval of the wording",
 "SB 223": "which lists religious rights students and staff keep at public schools",
 "SB 307": "the Generating Arkansas Jobs Act, which lets utilities charge customers for big new plants while still building them",
 "SB 411": "which makes driving with a front bumper raised four inches above the rear an offense",
 "HB 1574": "which lets only Arkansas residents be paid to collect ballot petition signatures",
 "SB 392": "which rebuilds how Arkansas classifies and pays state employees",
 "HB 1641": "which makes using a tracking device to follow someone part of the crime of harassment",
 "HB 1424": "which makes Medicaid and private health plans cover care for illnesses caused by severe obesity",
 "HB 1150": "which bars a pharmacy benefits manager from owning a retail pharmacy in Arkansas",
 "HB 1752": "which protects health, college and disability savings accounts from debt judgments",
 "SJR 11": "a proposed constitutional amendment widening the right to keep and bear arms to hunting, recreation and ammunition",
 "HB 1929": "which bars state agencies from using the term West Bank and requires Judea and Samaria instead",
 "HB 1428": "which caps bed height at 23 inches in hotel rooms built for guests with mobility disabilities",
 "HB 1683": "which bars governments from buying electric vehicles without a sworn statement that no forced labor was used",
 "HB 1878": "which requires early voting sites in every city of more than 15,000 people",
 "SB 437": "which creates a permit system for large wind farms with setback rules",
 "SB 491": "which makes state employee benefits contractors agree to outside data audits",
}
