EFFECTS = {
 "HB 2074": "which lets school safety grants pay for safety officers, equipment, training and building work",
 "HB 2007": "a bill to ban paying anyone by the number of voter registration forms they collect",
 "HB 2006": "a bill to make private senders of official-looking election mail print Not from a Government Agency on it",
 "HB 2017": "a bill to close voting centers and cut back early voting sites",
 "HB 2088": "a bill to let the state water director shrink a groundwater management area",
 "HB 2114": "which raises the penalty for an adult over 21 who has sex with a teenager aged 15 to 17",
 "HB 2089": "a bill to let voters end a groundwater management area by petition after ten years",
 "HB 2004": "a bill to stop county recorders sending voter registration cards to out-of-state addresses",
 "HB 2062": "a bill to set one meaning for sex-based words across state law",
 "HB 2202": "a bill to let farmers move an old groundwater pumping right onto new ground",
 "HB 2375": "a bill to make schools answer summer requests to assess a child for a disability within 15 days",
 "HB 2110": "which makes cities open at least 10 percent of older commercial property to housing",
 "HB 2291": "which ends the rule that a pharmacist must put a red cap on a bottle of prescription opioids",
 "HB 2450": "a bill to tie how long unemployment benefits last to the jobless rate, from 12 to 24 weeks",
 "HB 2121": "a bill to make able-bodied adults under 60 join a work program to keep food assistance",
 "HB 2122": "a bill to stop Arizona easing the work rule attached to food assistance",
 "HB 2447": "which makes cities let staff approve site plans and land splits without a public hearing",
 "HB 2374": "which raises the offense class for stalking, threats and assault done by agents of a foreign government",
 "HB 2527": "a bill to bar retiring a power plant until a plant of equal output is available",
 "HB 2788": "a bill to make electric utilities file a 15-year resource plan every three years",
 "HB 2173": "which bars health licensing boards from asking applicants whether they ever sought mental health help",
 "HB 2165": "a bill to make the state seek federal permission to keep food assistance from being spent on soda",
 "HB 2573": "a bill to move wine grapes and soil-free crops outside Arizona's irrigation limits",
 "HB 2154": "a bill to drop voters from the early ballot list when their mail comes back undelivered",
 "HB 2607": "which sets fixed prison terms of 5 to 15 years for carrying 200 grams or more of fentanyl in a vehicle",
 "HB 2880": "which bans overnight encampments on university and community college campuses",
 "HB 2440": "a bill to shield county supervisors from prosecution for voting against certifying an election",
 "HB 2574": "a bill to let counties approve small subdivisions without a water supply test",
 "SB 1437": "which makes school board members and substitute teachers report suspected child abuse",
 "SB 1060": "which makes police forces give an officer the papers 24 hours before an internal inquiry interview",
 "SB 1159": "which raises the unpaid wage claim a worker can bring to the Industrial Commission from $5,000 to $12,000",
 "SB 1071": "a bill to check food assistance households against lottery and gambling winnings",
 "SB 1501": "a bill to require electricity grid security reviews every two years",
 "SB 1333": "which pushes the state to place foster children in family homes rather than group settings",
 "SB 1164": "a bill to push local officials toward federal immigration enforcement and make jails honor detainers",
 "SB 1461": "which stops a police officer being fired for failing probation after a promotion",
 "SB 1296": "a bill to make unemployment claimants report five job search actions every week",
 "SB 1584": "a bill to make the state and local governments hire on merit and nothing else",
 "SB 1123": "a bill to set security rules for the paper ballots are printed on",
 "SB 1612": "a bill to put the state health program under Arizona's procurement rules",
 "SB 1089": "a bill to make the transport department explain passing over the cheapest bid",
 "SB 1280": "a bill to make counties publish the cast vote record within 48 hours of the county count",
 "SB 1705": "a bill to let a court fine a local official personally for making local gun rules",
 "SB 1256": "a bill to bar state agencies from using diversity, equity and inclusion programs in hiring",
 "SB 1610": "a bill to make county jails send arrestees' details to federal immigration agents",
 "SB 1462": "which extends the law on sharing explicit images to computer-made fakes of real people",
 "SB 1378": "which stops a homeowners association banning a political flag",
 "SB 1316": "which makes Arizona's review of deaths tied to pregnancy permanent",
 "SB 1694": "a bill to cut off state money to any public college that offers a diversity, equity and inclusion course",
 "SB 1590": "which removes the yearly dollar limit on insurance coverage for autism therapy",
 "SB 1020": "a bill to stop universities and community colleges banning guns on campus",
 "SB 1014": "a bill to take firearm suppressors off Arizona's list of prohibited weapons",
 "SB 1002": "a bill to stop school staff using a pupil's chosen name or pronoun without written parental permission",
 "SB 1003": "a bill to make schools provide separate restrooms and changing rooms on request",
 "SB 1586": "a bill to make clinicians liable for the cost of reversing gender transition care given to a minor",
 "SB 1036": "a bill to let any resident sue over public money being used to sway an election",
 "SB 1307": "which makes the state plan for small electric aircraft landing pads and charging from September 2026",
 "SB 1725": "a bill to cut the fentanyl amount that triggers the toughest sentences from 200 grams to 9",
 "SB 1088": "a bill to tie Arizona government and its contractors to federal immigration enforcement",
 "SB 1064": "a bill to set minimum security standards for vote counting machines",
 "SB 1052": "a bill to take the vote away from citizens who have never lived in the United States",
 "SB 1310": "a bill to make filing a fake claim against someone's property a class 4 felony",
 "SB 1098": "a bill to require proof of identity to hand in an early ballot",
 "SB 1295": "which makes using a computer-made voice, image or video of a real person to cheat people a felony",
 "SB 1143": "a bill to block government records showing who owns firearms",
 "SB 1268": "a bill to make hospitals ask patients about their immigration status",
 "SB 1518": "a bill to make old groundwater pumping rights tradable",
 "SB 1300": "a bill to let Cochise County voters decide groundwater limits for part of the San Simon valley",
 "SB 1097": "a bill to make public schools serve as polling places and close on election days",
 "SB 1353": "which gives larger cities 15 working days to answer a single-family home permit request",
 "SB 1351": "which creates a new felony of gift card theft",
 "SB 1247": "which raises the age for buying tobacco and vaping products from 18 to 21",
 "SB 1514": "a bill to make arbitration binding for warehouse workers",
 "SB 1019": "a bill to ban photo enforcement of traffic laws",
 "SB 1001": "a bill to let counties count early ballots on site and tighten late drop-offs",
 "SB 1529": "which makes cities keep ready-made house plans any builder can use",
 "SB 1537": "which sets up a state license for housing people move into after prison",
 "SB 1308": "which tightens the rules for sober living homes",
 "HB 2099": "a bill to require Arizona officials to help enforce federal immigration law",
 "HB 2449": "a bill to check state health coverage members against gambling records",
 "HB 2203": "a bill to widen the years used to set how much groundwater a farm may keep pumping",
 "HB 2514": "which makes schools tell parents before releasing a student's directory information",
 "HB 2438": "a bill to stop a person changing the sex recorded on their birth certificate",
 "HB 2169": "a bill to make school boards meet in public buildings and post all meeting materials online",
 "HB 2653": "which lets crime victims and witnesses keep their names out of public records",
 "HB 2221": "a bill to stop cities cutting police budgets below the previous year's",
 "HB 2222": "a bill to require 30 days' warning before a public body settles a case",
 "HB 2046": "a bill to set out how the hand count check on election results is run",
 "HB 2233": "a bill to make the Corporation Commission vote in public before lobbying",
 "HB 2570": "a bill to let irrigation users petition to cap new irrigation outside groundwater zones",
 "HB 2611": "known as Preston's Law, which makes an assault by a group that injures the victim a class 4 felony",
 "HB 2868": "a bill to ban diversity, equity and inclusion offices across much of Arizona government",
 "HB 2895": "a bill to make public bodies post task order contracts online",
 "HB 2928": "which makes counties allow small second homes on lots zoned for one house",
 "HB 2195": "which makes apps aimed at children keep mature advertising off their screens",
 "HB 2386": "which sets yearly pay benchmarks so the state police can compete with big city and county forces",
}
