OPEN = {
 1601541: ("Voted to agree to the Senate's changes to Assembly Bill 1318", "Voted against agreeing to the Senate's changes to Assembly Bill 1318"),
 1601264: ("Voted to pass Assembly Bill 1318", "Voted against passing Assembly Bill 1318"),
 1726450: ("Voted to pass Assembly Bill 1770, known as Lindalee's Law", "Voted against passing Assembly Bill 1770, known as Lindalee's Law"),
 1726270: ("Voted to pass Assembly Bill 1770, known as Lindalee's Law", "Voted against passing Assembly Bill 1770, known as Lindalee's Law"),
 1601918: ("Voted to agree to the Assembly's changes to Senate Bill 766", "Voted against agreeing to the Assembly's changes to Senate Bill 766"),
 1602273: ("Voted to pass Assembly Bill 1108", "Voted against passing Assembly Bill 1108"),
 1602910: ("Voted to agree to the Assembly's changes to Senate Bill 53", "Voted against agreeing to the Assembly's changes to Senate Bill 53"),
 1602931: ("Voted to agree to the Assembly's changes to Senate Bill 294", "Voted against agreeing to the Assembly's changes to Senate Bill 294"),
}
EFFECTS = {
 "AB 309": "which permanently lets pharmacies supply clean needles and syringes to adults without a prescription",
 "AB 1056": "which stops a commercial gill net permit passing to another fisher when the holder dies or becomes disabled",
 "SB 551": "which rewrites the stated purpose of California's prison system around normal daily life and rehabilitation",
 "SB 358": "which lowers traffic-impact fees for housing built near transit with little parking",
 "AB 454": "which makes it permanently unlawful in California to kill or capture birds protected under federal law as of 2025",
 "AB 1061": "which lets small housing projects in historic districts use fast-track approval unless the building itself is historic",
 "AB 1415": "which puts the management companies and investors behind medical practices under the state health cost watchdog",
 "AB 399": "a bill to let the Coastal Commission approve wetland restoration projects that measure stored carbon",
 "AB 435": "which sets a physical fit test from 2027 for when a child can ride without a booster seat",
 "AB 931": "which regulates companies that advance lawsuit money in return for a cut of the payout, requiring written terms",
 "SB 262": "which counts policies that keep people housed when the state rates a city's support for housing",
 "SB 437": "which funds up to $6 million of state university research on reparations and verifying descent from enslaved people",
 "SB 524": "which makes police reports written with artificial intelligence say so and carry the officer's signature",
 "SB 642": "which widens the equal pay law and tightens what a posted pay range must mean",
 "SB 704": "which requires gun barrels to be sold in person through a licensed gun dealer",
 "SB 82": "which stops consumer contract fine print from covering disputes unrelated to that contract",
 "SB 580": "which orders model rules by July 2026 on how state and local agencies deal with immigration authorities",
 "SB 805": "which makes plainclothes officers, including federal ones, visibly show their agency and name or badge number",
 "AB 1312": "which makes hospitals check from July 2027 whether a patient qualifies for free or discounted care",
 "SB 30": "which bars public agencies from passing on retired diesel rail equipment for further use unless it meets cleaner standards",
 "AB 1318": "which lets state tax-exempt status count wherever state law looks at federal tax-exempt status for grants and payments",
 "SB 518": "which sets up a state bureau to verify descent from enslaved Americans for reparations programs",
 "SB 36": "a bill to widen what counts as price gouging after a disaster and let consumers sue over it",
 "SB 497": "which shields medical records from other states' cases over care that is legal in California",
 "SB 634": "which bars local laws that punish people for helping the homeless with food, water and shelter",
 "SB 627": "which makes it a crime for officers, including federal agents, to hide their faces on duty",
 "AB 1340": "which lets rideshare drivers form an organization and bargain with the companies over pay and conditions",
 "SB 682": "a bill to ban forever chemicals in cleaning products, dental floss, food packaging and other everyday goods",
 "AB 1441": "which hands Merced County redistricting to an independent commission instead of the supervisors",
 "SB 647": "a bill to tell energy program applicants about other help and add a low-income advisory board seat",
 "SB 629": "a bill to widen fire hazard maps and create post-wildfire safety areas",
 "AB 1079": "which lets a court's fix for illegal local election rules take effect while the losing side appeals",
 "AB 1376": "which caps juvenile probation at 12 months unless a court extends it after a hearing",
 "SB 744": "which freezes the list of college accreditors California recognizes until July 2029",
 "SB 541": "a bill to make the state publish how much each electric utility shifts power use away from peak hours",
 "SB 59": "which keeps court records private for people of any age changing their name or gender marker",
 "AB 572": "which makes police and prosecutors adopt rules by 2027 for interviewing the family of someone an officer killed",
 "SB 42": "the California Fair Elections Act, which lifts the ban on public money for candidates who accept spending limits",
 "SB 613": "a bill to make state agencies give priority to cutting methane emissions, including from imported gas",
 "SB 707": "which makes larger local governments let the public join open meetings by phone or video",
 "SB 763": "which raises the top antitrust fine for a company from $1 million to $6 million",
 "AB 325": "which makes price-fixing cases easier to bring by letting plausible facts of a conspiracy go forward",
 "AB 695": "a bill to let deported community college students keep paying in-state tuition online",
 "AB 847": "which lets civilian police oversight boards see officers' confidential personnel records in investigations",
 "SB 352": "which keeps an environmental justice bureau in the Justice Department and sets neighborhood air monitoring rules",
 "SB 635": "which bars cities from asking sidewalk vendors about immigration status or requiring background checks",
 "AB 1127": "which bars gun dealers from July 2026 from selling pistols that can easily be converted to machine guns",
 "AB 1071": "which lets defendants claiming racial bias in their case get all the evidence bearing on that claim",
 "AB 1036": "which widens the right to see evidence after conviction to any felony with a state prison sentence",
 "AB 1084": "which lets adults change their name to match their gender identity without a hearing or objection from July 2026",
 "AB 7": "a bill to let California colleges give admissions preference to descendants of slavery",
 "SB 840": "which rewrites how California spends its greenhouse gas permit money, putting fire prevention first",
 "SB 79": "which makes cities allow taller apartment buildings near major transit stops",
 "SB 630": "which lets the state parks department buy and lease land with less outside review",
 "AB 1249": "which widens early in-person voting to start 29 days before election day",
 "SB 709": "which makes self-storage rental agreements disclose key terms on the first page in standout type",
 "SB 418": "a bill to make health plans cover a year's supply of hormone therapy at once",
 "AB 1487": "which widens what a state grant fund for transgender and intersex people can pay for",
 "AB 495": "the Family Preparedness Plan Act, which lets more relatives enroll a child in school and approve school medical care",
 "AB 1324": "a bill to drop the parental work-hours test for CalWORKs cash aid eligibility",
 "AB 246": "which lets tenants facing eviction cite a break in their Social Security payments as a defense through 2029",
 "AB 1336": "a bill to presume a farmworker's heat illness is job-related for workers' compensation",
 "AB 1319": "which makes it illegal to trade in wildlife taken in breach of protections as they stood in January 2025",
 "AB 93": "a bill to make data centers disclose their water use before getting a business license",
 "AB 692": "which bars stay-or-pay contracts that leave a worker owing money if the job ends",
 "AB 1037": "which widens who can carry and hand out overdose-reversal drugs such as naloxone",
 "AB 628": "which makes a working stove and refrigerator part of what a rented home must have from 2026",
 "AB 742": "a bill to speed up professional licensing for descendants of American slaves",
 "AB 1362": "which extends foreign labor recruiter registration rules to farmworker recruiters from July 2027",
 "AB 727": "which makes schools and colleges print an LGBTQ+ crisis line on student ID cards from July 2026",
 "SB 838": "which closes a hotel loophole in the law that protects housing projects from local rejection",
 "AB 858": "which keeps the hotel and building services layoff recall law running until 2027",
 "AB 766": "a bill to make state agencies build racial equity into their strategic plans",
 "SB 825": "which confirms the state financial regulator can act against escrow agents and lenders that deceive customers",
 "SB 22": "which lets people cash out gift cards with less than $15 left, up from $10",
 "AB 263": "which keeps emergency water flow rules for the Scott and Shasta rivers in force until 2031",
 "SB 7": "a bill to set rules for employers using automated systems to manage, discipline and fire workers",
 "SB 596": "which tightens the fines hospitals face for breaking nurse-to-patient staffing limits",
 "SB 25": "which makes companies filing federal merger notices send a copy to the California Attorney General",
 "AB 1876": "a bill to write a broad nondiscrimination rule for health plans into state law",
 "AB 2448": "a bill to make companies holding sensitive medical records switch on the security features they built",
 "SB 73": "which bars police from interfering with elections or touching voter lists without a court order",
 "AB 2122": "a bill to end arrest warrants and jail exposure for infractions such as traffic tickets",
 "AB 2428": "a bill to cancel court filing fees charged to people in prison and wipe unpaid balances",
 "AB 2646": "a bill to set a $19.75 minimum wage for temporary foreign farm workers",
 "AB 2393": "a bill to let people falsely arrested by a private person claim fixed damages",
 "AB 1854": "a bill to widen the shield for abortion and gender-affirming care against outside investigations",
 "AB 1758": "a bill to raise the yearly fee travel sellers pay into the fund that repays defrauded customers",
 "SB 177": "the Fair Share from Big Corporations Act, which orders options for billing large employers whose workers rely on Medi-Cal",
 "SB 1371": "a bill to stop garbage companies using a strike as a reason to halt service",
 "AB 2624": "which lets people who provide immigration support services keep their home address private from October 2027",
 "SB 934": "a bill to extend the ban on conversion therapy for minors to cover gender identity",
 "AB 2186": "a bill to exempt reparations payments from state income tax for 2028 through 2032",
 "SB 1093": "a bill to set what a mobilehome park owner owes residents after a disaster",
 "AB 1201": "a bill to narrow when a parent can be denied help getting a child back from foster care",
 "SB 1349": "a bill to make the Legislative Analyst review six large tax breaks",
 "AB 1743": "a bill to widen who can obtain the state's crime-gun tracing data",
 "SB 1250": "a bill to make Caltrans plan wildlife crossings on state highways",
 "SB 1037": "a bill to let state officials, not federal ones, judge whether a health insurance rate increase is unreasonable",
 "SB 937": "a bill to limit flash-bang grenades in crowd control and bar them in immigration raids",
 "AB 1973": "a bill to widen which health professionals may perform abortions and how late in pregnancy",
 "SB 1379": "a bill to separate the coroner from the sheriff in Riverside County and report on jail deaths",
 "AB 2128": "a bill to bar public housing agencies from putting time limits or work requirements on tenants",
 "AB 1116": "a bill to open online voter registration to citizens without a California license or state ID",
 "SB 1237": "a bill to raise the penalty on employers that repeatedly fail to file a pay data report",
 "SB 1164": "a bill to widen the California Voting Rights Act and who can sue under it",
 "SB 1414": "a bill to hand San Bernardino County redistricting to an independent commission",
 "SB 747": "the No Kings Act, which lets people sue in state court over violations of their federal constitutional rights",
 "AB 1801": "a bill to make it harder for local governments to approve a private immigration detention facility",
 "SB 1425": "a bill to create penalties for interfering with high-speed rail land",
 "SB 608": "a bill to widen access to contraception in schools and shops and check sex education compliance",
 "SB 873": "a bill to widen the protection against civil arrest at courthouses",
 "SB 633": "a bill to raise penalties on drink makers that miss recycled-plastic targets",
 "SB 938": "a bill to stop former federal immigration officers skipping the police academy on that experience alone",
 "AB 1905": "a bill to bar undercover questioning of young people held in custody",
 "AB 1807": "a bill to bar immigration enforcement from using state property as a base",
 "SB 1173": "a bill to let a defendant ask the jury to consider a closely related lesser offense",
 "AB 2247": "a bill to pay for counseling for young gun violence survivors in Los Angeles County",
 "AB 762": "a bill to ban disposable tobacco vapes from 2027",
 "AB 2465": "a bill to cut off state grants, loans and tax credits to companies tied to immigration detention",
 "SB 1406": "a bill to close a use-tax dodge for expensive cars, boats and planes bought through out-of-state shell companies",
 "AB 1661": "a bill to send oil-well penalty money directly to households near the Inglewood oil field",
 "AB 1806": "a bill to extend independent state investigation of deadly shootings to immigration officers",
 "SB 923": "a bill to widen the right to make a company delete personal information it got from others",
 "AB 2531": "a bill to open the state's subsidized abortion and contraception program to veterans regardless of income",
 "AB 1664": "a bill to make election officials alert the state when police or prosecutors seek election records",
 "AB 1770": "a bill to put the Attorney General in charge of watching how health plans run forced arbitration",
 "AB 1886": "a bill to cap juvenile probation at 12 months for young people placed outside the home",
 "AB 1049": "a bill to stop a sponsor's income counting against immigrants applying for state food aid",
 "AB 1930": "a bill to route out-of-state demands for abortion and gender care records through the Attorney General",
 "AB 1457": "a bill to make cities involve poor and polluted neighborhoods in environmental justice planning",
 "AB 1448": "a bill to tighten the rules on oil and gas drilling in California's coastal waters",
 "AB 1650": "a bill to make police mark rented cars used to stop, arrest or transport people",
 "SB 327": "a bill to stop utilities charging customers for fighting public takeovers of their service",
 "AB 1633": "a bill to tax private detention facility operators 25 percent of their California income from 2028",
 "AB 2318": "a bill to make it unlawful for an officer to block medical care for someone they are holding",
 "AB 2227": "a bill to raise the bonds and penalties that apply to farm labor contractors",
 "AB 40": "a bill to force a full environmental study before a large coal terminal can be approved",
 "SB 513": "which gives workers the right to see and copy their own training records",
 "SB 515": "which makes cities and counties use more detailed ancestry categories when recording who they hire",
 "SB 98": "which makes schools and colleges tell their communities when immigration enforcement is confirmed on site",
 "AB 373": "which makes a lawyer for an adult former foster youth follow that client's instructions",
 "AB 43": "which keeps state protection for rivers that lose federal wild and scenic status",
 "AB 893": "which makes fast-track approval easier for housing, including near college campuses",
 "AB 734": "a bill to make wildlife survey data in power plant applications public",
 "AB 321": "which widens the window for a judge to reduce a borderline felony to a misdemeanor",
 "AB 1136": "a bill to give workers unpaid leave for immigration appointments",
 "AB 681": "which raises how much graduate students may borrow under the state DREAM Loan Program",
 "AB 339": "which makes local agencies give a union 45 days' notice before contracting out its members' work",
 "AB 1303": "which bars the low-income phone program from handing applicant data to immigration authorities",
 "AB 393": "a bill to make prisons compare costs before hiring contract doctors over civil service ones",
 "AB 797": "a bill to create a state-backed program to buy and resell homes destroyed by the January 2025 wildfires",
 "AB 1348": "a bill to protect school funding when immigration enforcement keeps students at home",
 "AB 1296": "which makes the state housing department help school districts build housing on land they own",
 "AB 499": "which reimburses one farm worker health plan up to $3 million a year for large medical bills through 2030",
 "AB 57": "a bill to reserve part of a state down-payment fund for descendants of enslaved people",
 "AB 1261": "which funds lawyers for immigrant young people in California",
 "AB 1411": "which makes counties without all-mail elections write their own plans to reach unregistered voters",
 "SB 827": "which widens who must take local government ethics training and adds financial training",
 "AB 1167": "which stops utility customers paying for their utility's political influence work",
 "AB 260": "which protects abortion medication and lets pharmacists leave names off mifepristone labels",
 "AB 461": "which ends the crime of being the parent of a chronically truant child",
 "AB 86": "a bill to set a deadline for adopting health education materials for younger pupils",
 "AB 1525": "which stops the State Bar disciplining lawyers over out-of-state penalties tied to abortion or gender care",
 "AB 723": "which makes real estate listings disclose when a photo has been digitally altered",
 "AB 812": "which makes the prison system set rules for referring incarcerated firefighters for resentencing",
 "AB 39": "which makes larger cities and counties write a local plan for electrification and clean energy",
 "AB 82": "which widens the legal shield for gender-affirming care providers to match the one covering abortion",
 "SB 388": "a bill to create a California Latino Commission to study inequities",
 "SB 464": "which tightens employer pay data reporting from 2027",
 "AB 851": "which bans unsolicited offers to buy homes in areas burned by the January 2025 wildfires",
 "AB 538": "which makes contractor payroll records on public construction jobs easier for the public to obtain",
 "AB 419": "which makes schools post the state's immigration enforcement guide where families can find it",
 "AB 1050": "which widens the route around private deed restrictions that block housing",
 "AB 507": "which lets qualifying building conversions into housing skip discretionary review from July 2026",
 "AB 1263": "which makes it a misdemeanor to help someone make an untraceable gun, including with a 3D printer",
 "SB 655": "which makes it state policy that every home can reach a safe maximum indoor temperature",
 "SB 313": "which moves a parent's country of birth off the public part of a birth certificate",
 "SB 766": "the California Combating Auto Retail Scams Act, which tightens rules against deceptive car dealer pricing",
 "SB 578": "which sets up a program paying nonprofits to teach low-wage workers their rights once funded",
 "SB 771": "a bill to fine large social media companies whose recommendation systems break civil rights laws",
 "SB 24": "a bill to bar utilities from charging customers for fighting public takeover of their service",
 "AB 963": "a bill to make property owners and developers hand over public works records on request",
 "AB 1108": "which stops sheriff-coroners deciding the cause of deaths in custody from 2027",
 "AB 45": "which restricts tracking people by their location at family planning centers",
 "SB 53": "the Transparency in Frontier Artificial Intelligence Act, which sets safety duties for companies training the largest AI models",
 "SB 294": "the Workplace Know Your Rights Act, which makes employers hand every worker a yearly notice of workplace rights",
 "SB 787": "a bill to build state machinery to coordinate clean energy manufacturing",
 "SB 703": "a bill to make trucking companies at two ports disclose how they classify their drivers",
 "SB 1194": "a bill to set up a fellowship program expanding free immigration legal help",
 "SB 1196": "a bill to set deadlines for utilities to connect small customers to the grid",
 "AB 1944": "a bill to let zero-emission transit buses carry more weight per axle for several years",
 "AB 2011": "a bill to lock the state's mental health insurance parity standard to the federal rules as of 2025",
 "AB 1820": "a bill to cap what a city may charge to permit an electric vehicle charger at an apartment building",
 "AB 1655": "a bill to keep a family's cash aid intact when a member is held in immigration detention",
 "SB 1328": "a bill to extend campus LGBTQ points of contact to branch and satellite locations",
 "AB 2395": "a bill to make it easier to settle unpaid child support owed to the state",
 "AB 2599": "a bill to make large long-established companies search their records for historical ties to slavery",
 "AB 2495": "a bill to widen the ban on using someone's immigration status against them at work",
 "SB 501": "a bill to widen the battery recycling program to cover far more batteries",
 "AB 801": "a bill to require regular checks that banks and mortgage lenders are not discriminating",
 "AB 956": "which makes cities approve two backyard homes on a lot rather than one",
 "AB 1539": "a bill to require a sworn statement that a presidential ticket is eligible before it goes on the ballot",
 "AB 2510": "a bill to protect cash aid for parents working to get their children back from foster care",
 "AB 1803": "a bill to add anti-hate-speech training to required workplace harassment training",
 "AB 1792": "a bill to have the curriculum commission consider adding dating abuse and online abuse to health teaching",
 "SB 1220": "a bill to make gun serial-number tampering a conviction that costs a person the right to own a gun",
 "AB 2164": "a bill to shield people who helped someone get abortion or gender-affirming care in another state",
 "AB 2619": "a bill to make data centers disclose their water use when seeking a business license",
 "SB 909": "a bill to raise the penalties for underpaying workers on public construction",
 "SB 1323": "a bill to tighten the rules on immigration enforcement inside hospitals and clinics for three years",
 "AB 1979": "a bill to apply medical privacy law to health chatbots and keep a licensed person in charge of clinical decisions",
 "AB 1838": "a bill to make contractors bidding on local public works disclose their wage and hour violations",
 "SB 1125": "a bill to set up a program helping low-income households pay water bills",
 "AB 1629": "a bill to make dental plans pay out-of-network dentists directly and tell patients the cost first",
 "AB 1595": "a bill to make it easier to overturn a conviction based on false evidence",
 "SB 998": "a bill to add state staff working to prevent discrimination in schools",
 "AB 713": "a bill to stop public colleges requiring proof of federal work authorization for campus jobs",
 "AB 690": "a bill to set rules for how counties pay lawyers appointed to defend people who cannot afford one",
 "SB 1418": "a bill to strengthen the rules on keeping election materials until any contest is decided",
 "SB 1255": "a bill to create a state designation for colleges serving Latino students",
 "SB 1388": "a bill to create a state service helping affordable housing providers with insurance costs",
}
