EFFECTS = {
 "SB 52": "which ends the blanket secrecy over railroad accident reports filed with the state utilities commission",
 "HB 1030": "which makes local and state building codes adopted from 2026 follow current national accessibility standards",
 "HB 1132": "which replaces the veterans mental health program with grants for behavioral health care for military families",
 "HB 1179": "which makes car insurance pay to replace a child car seat damaged in a crash",
 "HB 1148": "which puts criminal protection orders on a standard form naming the people, animals and places covered",
 "HB 1011": "a bill to set price-posting and other rules for child care centers owned by investment firms",
 "HB 1109": "which makes a death certificate record a person's gender as their gender identity when documents show it",
 "HB 1217": "which makes stealing money a client prepaid for funeral services both a crime and a deceptive trade practice",
 "HB 1197": "which sets labeling and equipment rules for electric bicycles sold in stores or online into Colorado",
 "HB 1114": "which gives criminal defendants the right to inspect physical evidence held by police at least 35 days before trial",
 "SB 4": "which lets families get child care application and wait list fees back if not enrolled within six months",
 "HB 1169": "a bill to make larger local governments allow homes on land owned by faith groups and schools",
 "HB 1093": "which bars urban local rules that cut housing density or allowed housing uses below their July 2025 zoning",
 "HB 1009": "which lets fire districts require property owners to clear dead or dry plants that can carry a wildfire",
 "HB 1282": "a bill to bar card networks from charging swipe fees on the sales tax or tip part of a bill",
 "HB 1250": "which makes the state post gun violence prevention material online for schools to give parents",
 "SB 3": "which bans making, selling or buying most detachable-magazine semiautomatic rifles unless the buyer passes a safety course",
 "SB 14": "which repeals Colorado's dead-letter statute limiting marriage to one man and one woman",
 "HB 1090": "which makes sellers show one total price that includes every fee a buyer must pay",
 "HB 1238": "which makes gun show promoters file a security plan with local police and carry liability insurance",
 "HB 1133": "which keeps ammunition behind the counter and bars selling it to most people under 21",
 "HB 1018": "which lets people apply for state vocational rehabilitation services without being in Colorado at the time",
 "SB 86": "a bill to make social media companies publish their rules and remove drug, gun and sex-crime content quickly",
 "SB 77": "a bill to give governments five working days instead of three to answer most open records requests",
 "HB 1294": "which keeps the ban on charging court costs and fees to children and their parents from expiring",
 "HB 1244": "which lets migrant support grants serve people who arrived more than a year ago",
 "SB 62": "which bars city courts from making a missed court date a crime of its own",
 "HB 1277": "a bill to require a health and climate warning label on fuel sold at Colorado pumps",
 "SB 183": "which lets public employers cover abortion after voters repealed the constitutional ban on public funding",
 "SB 129": "which strengthens the shield for abortion and gender-affirming care, letting pill labels name the clinic instead of the doctor",
 "SB 208": "which delays free prison phone calls by a year, to July 1, 2026",
 "SB 6": "which lets the state treasurer invest up to $50 million in bonds that finance affordable homes for sale",
 "HB 1010": "which lets the governor declare an emergency during market disruptions and treat steep price rises as price gouging",
 "HB 1234": "which bars the state from demanding a social security number from people applying for utility bill help",
 "HB 1182": "which makes home insurers share their wildfire risk models with regulators and credit homeowners who cut risk",
 "HB 1240": "which bars landlords from rejecting tenants who pay with a housing voucher or other subsidy",
 "HB 1113": "which bans decorative grass at new homes in developments of 12 units or more from 2028",
 "HB 1161": "which requires a yellow label on new gas stoves warning buyers about indoor air quality",
 "HB 1168": "which bars evicting tenants for lease breaches caused by domestic violence, stalking or sexual assault",
 "SB 31": "which makes emergency alerts go out in the minority languages widely spoken in an area from July 2027",
 "SB 63": "which makes every school district adopt written policies for choosing and reconsidering library books",
 "HB 1158": "a bill to treat targeted ads in school digital research collections as a broken contract",
 "HB 1049": "which gives people in custody the right to hear from their lawyer by visit, phone or video call",
 "HB 1211": "which requires water district tap fees to be reasonably related to the cost of providing service",
 "HB 1248": "which limits when public schools may restrain or seclude students to narrow named cases",
 "HB 1043": "which makes a homeowners association follow its own bylaws and state law before collecting money from an owner",
 "HB 1188": "which bars child abuse reports based only on a family being poor, unhoused, disabled, or their race",
 "SB 154": "which lets teaching candidates meet coursework standards in more than one way",
 "SB 2": "which orders regional building codes for factory-built homes, which cost less than homes built on site",
 "HB 1117": "which makes vehicle booting companies photograph the car and the reason before booting it",
 "HB 1147": "a bill to cap city court jail terms at what state law allows for the same conduct",
 "SB 70": "which makes online marketplaces alert police when a seller is offering stolen goods in Colorado",
 "SB 145": "which makes sellers offer a one-click online link to cancel a self-renewing subscription",
 "HB 1290": "which makes wrongly interfering with a transit worker doing their job a harassment offense",
 "SB 226": "which keeps running the chiropractic, massage and acupuncture program for people with spinal cord injuries",
 "SB 20": "which lets the attorney general enforce Colorado's tenant protection laws",
 "SB 79": "which caps cryptocurrency kiosk spending at $2,000 a day for new customers and requires on-screen warnings",
 "SB 196": "which keeps free preventive care in health plans even if federal expert advice is repealed",
 "SB 144": "which gives parents of newborns in intensive care up to 12 more weeks of paid family leave",
 "HB 1329": "which makes lawsuit funders owned by foreign governments of concern file with the attorney general",
 "SB 182": "which lets special district energy loans also pay for lower-carbon building materials",
 "SB 81": "which creates a state authority to finance transport, energy, water and public building projects",
 "SB 205": "which lets gun dealers ask police to check a firearm's serial number before buying it from a private seller",
 "HB 1322": "which makes home insurers pay $50 a day when they miss the 30-day deadline for sending a policy copy",
 "HB 1328": "which makes the state study health benefits for direct care workers and how to pay for them",
 "SB 53": "which treats wild bison as wildlife, making it illegal to take one without state permission",
 "SB 1": "which creates the Colorado Voting Rights Act, barring local election rules that weaken minority voters' power",
 "HB 1159": "which ties the child support low-income adjustment to the state minimum wage",
 "HB 1079": "a bill to put school boards and special districts under the state ethics board",
 "HB 1235": "a bill to give landlords and tenants a right to a jury trial in eviction cases",
 "SB 190": "which lets people who post bail stay overnight so jail staff can link them to services",
 "SB 8": "which makes the state run the free birth certificate and ID document program itself from July 2027",
 "SB 158": "which makes the state buy firearms only from licensed contractors that report federal gun-trace requests",
 "SB 126": "which makes big company mergers reported to federal regulators also go to the Colorado attorney general",
 "HB 1149": "which adds Black history and culture to the standards Colorado schools teach",
 "HB 1225": "which makes it illegal to threaten or scare a person for voting, helping others vote, or running an election",
 "HB 1004": "a bill to ban rent-setting software that pools competing landlords' price data",
 "HB 1026": "a bill to end the fee prisoners pay to see a doctor, dentist or counselor",
 "HB 1239": "which widens the remedies for discrimination in public places to include legal fees and a choice of payouts",
 "HB 1097": "which requires a written transition plan before a foster child is moved between placements",
 "HB 1154": "which folds state services for blind, deaf and deafblind people into one self-funded enterprise",
 "SB 118": "which makes maternity health plans cover up to three prenatal visits with no copay or deductible",
 "SB 50": "which makes government forms asking race offer Middle Eastern, North African and South Asian choices",
 "SB 167": "which adds helping Colorado communities to the investment goals of two public funds",
 "SB 289": "which creates a state program letting pharmacies and clinics donate unused medicine to people who need it",
 "SB 313": "which tightens how Proposition 123 affordable housing money can be spent",
 "SB 162": "which makes the state watch center tell rail regulators at once when a railroad reports a train emergency",
 "HB 1013": "which gives people in state prisons a right to social visits, phone calls and video calls",
 "HB 1098": "which sets up an automated system to tell protected people the dates and terms of their protection orders",
 "HB 1319": "which sends some county board vacancies in larger counties to a vacancy election instead of a party committee",
 "HB 1327": "which makes statewide ballot measure titles carry a fiscal impact description and bars repeat draft filings",
 "SB 130": "which writes into state law a hospital's duty to examine and stabilize anyone seeking emergency care",
 "SB 286": "which lets the state fine retailers up to $5,000 a day for selling gasoline that fails clean-air standards",
 "SB 276": "which bars schools, clinics and libraries from asking a person's birthplace or immigration status",
 "SB 34": "which lets a person voluntarily give up their own right to buy a firearm through a state portal",
 "SB 163": "which makes battery makers fund and run a statewide battery recycling program",
 "SB 5": "a bill to drop the second worker vote Colorado requires before a union security clause",
 "SB 299": "which gives home solar buyers written disclosures and a window to cancel without penalty",
 "SB 124": "a bill to make larger nonprofit hospitals spend most of their federal drug discount gains on low-income care",
 "SB 288": "which lets people shown in shared intimate images, including computer-made ones, sue whoever shared them",
 "SB 48": "which makes large employer health plans cover obesity and pre-diabetes treatment",
 "HB 1312": "the Kelly Loving Act, which counts a person's chosen name as protected gender expression",
 "HB 1249": "which makes landlords return security deposits within 30 days and show receipts for any money kept",
 "HB 1259": "which writes a right to fertility care, including IVF and surrogacy, into state law",
 "HB 1292": "which sets a state review process for high voltage power lines inside highway rights-of-way",
 "HB 1094": "which limits pharmacy benefit managers to a flat fee per prescription, not pay tied to drug prices",
 "HB 1001": "which strengthens wage theft enforcement and counts owners of a quarter of a company as employers",
 "HB 1267": "which sets minimum standards for public electric vehicle chargers by July 2026",
 "SB 321": "which orders new emissions inspection rules for areas failing federal air quality standards",
 "HB 1295": "which makes local governments accept a food truck fire safety permit issued elsewhere in Colorado",
 "HB 1269": "which creates a fee-funded enterprise offering large building owners help to cut energy use",
 "SB 7": "which creates a state fund to pay damage claims when a prescribed burn causes harm",
 "SB 72": "which makes selling kratom to anyone under 21 a deceptive trade practice",
 "HB 1300": "which makes workers' compensation insurers answer treatment requests using state care standards",
 "SB 161": "which sets performance planning and reporting rules for the Denver area's transit agency",
 "HB 1309": "which makes state-regulated health plans cover gender-affirming care",
 "HB 1273": "which makes large cities allow buildings up to five stories with a single stairway by December 2027",
 "HB 1003": "which ends the lower premium tax rate for insurers with a home office in Colorado from 2026",
 "HB 1002": "which adds Hong Kong, Ireland, the Netherlands and others to the list of presumed corporate tax havens",
 "HB 1006": "which puts $100 million toward individual health plan premiums if Congress lets federal help lapse",
 "HB 1045": "which writes the old federal guidance on renters' assistance animals into Colorado law",
 "HB 1071": "a bill to let local governments put speed cameras on designated stretches of state highway",
 "HB 1070": "which bars third parties from using a dentist's agreed discount rates without written consent",
 "HB 1096": "a bill to let Medicaid members pay for direct primary care themselves",
 "HB 1017": "which makes court-ordered restitution go first to the direct crime victim, not insurers",
 "HB 1099": "which makes builders pay for a 30-year reserve study before handing a homeowners association over",
 "HB 1134": "which makes city courts hold a hearing within 48 hours for people held only on a city charge",
 "HB 1039": "which makes city jails meet state jail standards from July 2027",
 "HB 1145": "which widens when the state can order a mobile home park owner to fix unsafe drinking water",
 "HB 1265": "which makes every Colorado police force join the federal gun tracing system by September 2026",
 "HB 1202": "which orders a statewide plan for preventing and ending homelessness by January 2027",
 "HB 1005": "a bill to scrap the second worker vote required before a union security clause",
 "HB 1192": "which puts the state housing division directly in charge of the homeless prevention program",
 "HB 1137": "a bill to bar campaign consultants from working for opposing candidates without consent",
 "SB 13": "which removes living together from Colorado's bigamy offense",
 "HB 1107": "which requires every licensed dementia care home to fill in a standard comparison form by July 2027",
 "HB 1064": "which refocuses the youthful offender system on treatment, with a plan and case manager for everyone",
 "HB 1139": "which makes health insurers' artificial intelligence review tools judge from a patient's own medical history",
 "HB 1203": "a bill to make five-member commissioner boards the rule in counties over 70,000 people",
 "SB 32": "which has the state board of health set its own list of recommended adult vaccines",
 "SB 16": "which bars facilities from discharging plastic pellets, flakes or powders into Colorado waters or land",
 "HB 1126": "which makes firearms dealers hold a state permit to move guns into or out of Colorado",
 "HB 1308": "a bill to make larger jurisdictions approve splitting a house lot in two administratively",
 "HB 1193": "which adds pre-kindergarten to the grades where schools test children's sight",
 "HB 1144": "which makes it a crime to 3-D print or mill a working gun or gun part without a license",
 "HB 1232": "which bars courts from charging time payment fees to children or their parents",
 "HB 1302": "which lets the state set gun background check desk hours to match demand",
 "SB 47": "which lets firefighter collective bargaining votes happen at coordinated elections too",
 "HB 1127": "which replaces coroners' monthly crash death reports with quarterly electronic ones",
 "SB 18": "which seals name change court records for people under 18 from July 2026",
 "SB 87": "a bill to give state legislators a right to leave from their outside job during session",
 "SB 21": "which lets the clean fleet program help small fleets replace pre-2010 diesel trucks",
 "HB 1044": "which makes hospitals give every birthing parent a written notice of their right to respectful care",
 "HB 1268": "which lets cities put property tax growth on old mine and landfill sites toward renewable energy projects",
 "HB 1007": "which bars utilities from charging fees for small plug-in balcony solar panels",
 "HB 1081": "which pushes utilities to use better wire and other tools that carry more power on existing lines",
 "HB 1135": "which requires a cancer or birth defect warning label on hair relaxers and hairpieces from July 2027",
 "HB 1120": "which makes counties sell a tax lien on a mobile home with unpaid taxes instead of seizing the home",
 "SB 121": "which gives farm workers overtime pay after 56 hours a week from 2027",
 "HB 1224": "which lets mobile home park landlords end a tenancy over a local rule only after a government ruling",
 "SB 104": "which makes every Colorado school fit an outside key box for police by July 2030",
 "SB 109": "which updates the accessible home requirement for bigger housing projects to the 2017 national standard",
 "SB 40": "which widens who qualifies for state down payment help, allowing housing costs up to 38% of income",
 "HB 1196": "which makes every rental application say what data the landlord pulls and weighs from 2027",
 "SB 19": "which rebuilds early childhood councils as one statewide system from July 2026",
 "HB 1038": "which moves county commissioner district lines from sitting commissioners to independent commissions",
 "HB 1321": "a bill to limit school safety training grants to Colorado-based nonprofits",
 "HB 1245": "a bill to make it theft when a contractor carelessly spends a customer's advance payment elsewhere",
 "HB 1227": "which confirms a child in a state care case is a party in their own right through appeal",
 "HB 1314": "which makes counties record their efforts to place removed children with relatives",
 "SB 59": "which bars a state legislator from holding another elected office while serving",
 "HB 1342": "which makes knowingly leaving food out where a bear is likely to come an offense",
 "HB 1143": "which bars background checks for internships and placements from requiring a social security number",
 "HB 1130": "a bill to require diaper changing tables in public building restrooms from 2028",
 "HB 1335": "which makes college student health centers give students access to abortion medication from August 2027",
 "HB 1206": "a bill to let public housing authorities ask voters for a sales tax to build deeply affordable housing",
 "HB 1281": "a bill to narrow the extreme indifference murder charge to cases where more than one person died",
 "HB 1414": "which caps what a hospital may charge a patient's lawyer for medical records at $400",
 "SB 159": "which raises the monthly good behavior sentence credit for most inmates from 12 days to 14",
 "SB 51": "which makes app stores ask a user's age at account setup and pass that signal to apps from July 2028",
 "SB 150": "which cuts the Denver transit board to five elected seats plus four governor appointees from 2028",
 "HB 1019": "which makes health plans cover a yearly kidney check at no charge to the patient",
 "HB 1318": "which sets a school zone as every road within 1,000 feet of school grounds",
 "HB 1283": "which bars employers from keeping a worker's government ID card for more than 10 hours",
 "HB 1008": "which gives the parks and wildlife division a formal job of planning outdoor recreation",
 "HB 1320": "which makes ballot measure titles use plain words the widest audience can follow",
 "SB 141": "which adds an optional $5 vehicle registration fee to pay for wildlife crossings",
 "HB 1054": "a bill to create a Colorado Worker Safety Act with a state duty to keep workplaces free of known hazards",
 "SB 160": "which stops employers deducting safety gear costs from pay and guarantees meat plant toilet breaks",
 "SB 113": "which makes running a sober living home without a state license unlawful from July 2027",
 "SB 134": "a bill to bar card networks from charging swipe fees on the sales tax part of a purchase",
 "SB 146": "a bill to make restaurants and delivery apps ask before handing out single-use cutlery",
 "HB 1207": "which makes employers of 100 or more file staff counts by race and sex with the state from 2027",
 "HB 1123": "which limits when jail staff may strip search someone and requires body camera filming",
 "HB 1425": "which requires a state license to practice applied behavior analysis therapy",
 "SB 138": "which sets one uniform application for hospital discounted care for low-income patients",
 "SB 36": "which triggers prison overcrowding steps at a four percent vacancy rate and widens who gets told",
 "SB 177": "which lets a homeowner ask a court for access to a neighbor's land to repair a shared wall",
 "HB 1226": "which orders pollution limits for coal power plant units that keep running past 2034",
 "HB 1084": "which softens the tax-cut warning in ballot measure titles to say funding is likely to fall",
 "HB 1210": "a bill to ban setting a price or wage for each customer from data gathered about them",
 "HB 1028": "which widens how students can earn a seal of biliteracy and adds a lower seal for speaking and listening",
 "SB 174": "which makes lead generation marketing for legal services a deceptive trade practice",
 "SB 93": "which makes building permit applicants on jobs over $1 million swear every worker has injury insurance",
 "SB 131": "which bans sportsbook push alerts urging a bet and caps deposits at six a day",
 "SB 172": "which redraws the front range passenger rail district boundary along whole municipalities",
 "SB 115": "which lets prisoners aged 60 or over who served 20 years ask the court to review their sentence",
 "HB 1112": "a bill to let Colorado seek federal authority to regulate three classes of injection wells",
 "HB 1138": "which sets up a grant fund and board to fight organized retail theft",
 "SB 184": "a bill to presume a covered firefighter's cancer was caused by the job",
 "SB 35": "which adds extra license points for repeat serious speeding and driving at 100 miles an hour or more",
 "SB 155": "which creates an insurer-funded grant program to make homes stand up to hail, wind and wildfire",
 "SB 178": "which lets the reinsurance program that holds down individual premiums borrow up to $100 million",
 "SB 103": "which makes every school district adopt a policy sending community help to at-risk students by July 2027",
 "SB 152": "which defines which traffic cameras count as mobile and how they may be used",
 "HB 1263": "which makes public chatbot operators check whether a user is a child and owe extra duties to children",
 "HB 1111": "which creates a fee-funded state program to dispose of leftover pesticide from 2027",
 "HB 1276": "which lets state and local health agencies inspect immigration detention facilities",
 "HB 1016": "which keeps the state report on free course materials running through 2031",
 "HB 1100": "which writes a bill of rights for adults under guardianship into Colorado law",
 "HB 1345": "which funds co-located degree partnerships so rural campuses keep their students",
 "HB 1033": "the Tamale Act, which lets home cooks sell packaged foods that need heating or chilling",
 "HB 1141": "which spells out how the ban on unfair treatment in public places applies to schools and colleges",
 "HB 1255": "a bill to make large social media platforms staff a warrant hotline at all times",
 "SB 125": "which writes federal protections for students with disabilities into Colorado law",
 "SB 80": "which creates grants linking early childhood, school and work help in high-poverty areas",
 "HB 1223": "which adds a state income tax credit for families with children from 2027, paid for by taxing software",
 "HB 1424": "which makes ride-hailing companies run driver background checks every six months",
 "HB 1236": "a bill to void arbitration clauses that charge workers or shoppers fees far above court fees",
 "HB 1272": "which makes the state publish a model plan for protecting workers from extreme heat and cold by July 2028",
 "HB 1418": "a bill to fund youth mental health with a fee on in-game purchases",
 "HB 1015": "which extends the tax credit for donations to homelessness charities through 2030",
 "HB 1065": "which lets the state reinvest its sales tax growth near transit stations into sidewalks and crossings",
 "SB 185": "a bill to let a home's first buyer sue the builder for construction defects",
 "SB 157": "a bill to make it easier for older people, veterans and disabled people to sue over scams",
 "SB 83": "which voids non-compete clauses for doctors, nurses, midwives and dentists however much they earn",
 "HB 1062": "which makes stealing a firearm a class 6 felony whatever the gun is worth",
 "HB 1122": "a bill to require a licensed driver in every self-driving commercial truck",
 "HB 1291": "a bill to make ride-hailing companies run private criminal checks on drivers every six months",
 "SB 43": "a bill to require gun barrel sales to go through a licensed dealer in person",
 "SB 140": "a bill to exempt rare disease drugs and blood products from state drug price caps",
 "SB 90": "a bill to exempt critical infrastructure gear from Colorado's right to repair law",
 "SB 66": "a bill to require safety confirmations before selling compounded weight-loss drugs",
 "SB 166": "a bill to bar people with violent or drug distribution felonies from school boards for ten years",
 "SB 91": "a bill saying a newspaper route's ordinary demands alone do not make a deliverer an employee",
 "SB 142": "which lets towns build shared underground heating and cooling networks with private buildings",
 "HB 1256": "which stops the state deducting fees from the $100 a person gets on leaving prison",
 "HB 1286": "a bill to require a licensed commercial driver in the cab of self-driving heavy trucks",
}
