EFFECTS = {
 "HB 7066": "which makes every school name an administrator to handle contacts with federal immigration officers",
 "HB 7042": "which lets people sue gun makers and sellers that fail to keep reasonable controls over sales",
 "HB 5004": "which sets new state targets for cutting greenhouse gases and creates a Clean Economy Council",
 "HB 6907": "a bill to limit production quotas at large warehouse distribution centers",
 "HB 7248": "a bill to let the public health commissioner put water cross-connection rules into effect early",
 "HB 6477": "a bill to require a plan for translating state forms for people with limited English",
 "HB 7158": "a bill to let a provider send a minor's safety plan to the child's school with consent",
 "HB 7065": "a bill to take possession of small amounts of psilocybin out of criminal penalties",
 "SB 1234": "which bars publicly funded libraries from e-book deals that restrict everyday lending",
 "HB 7035": "a bill to bar any town from banning multifamily housing or duplexes outright",
 "HB 7210": "a bill to make halfway house contracts follow each resident's discharge plan",
 "HB 6844": "a bill to stop towns cutting a retiree's pension over workers' compensation disability benefits",
 "SB 1367": "which bars bail bond agents from seizing someone at a hospital, school or house of worship",
 "HB 5002": "a bill to make towns allow small multi-unit housing on business-zoned land and rewrite zoning law",
 "SB 9": "which makes insurers and lenders tell customers about flood risk and flood insurance",
 "SB 1221": "which expands the state retirement savings program to home care aides from July 2026",
 "SB 7": "a bill to protect access to emergency and reproductive health care if federal rules weaken",
 "SB 3": "which requires advertised prices to include every fee and creates a right to repair",
 "SB 1": "which creates a permanent fund for early childhood education and adds special education money",
 "SB 1328": "which bars private companies from owning or running state prisons",
 "SB 1427": "a bill to open paid family and medical leave to certain school employees",
 "SB 1444": "which lets towns fast-track turning commercial buildings into housing",
 "SB 1542": "which bars police from handcuffing a child under 14 except for public safety",
 "HB 7087": "a bill to set the rules for community solar subscriptions",
 "SB 8": "a bill to let striking workers claim unemployment benefits after fourteen days",
 "SB 1187": "which limits when a sewer authority can take a person's home over unpaid bills",
 "SB 1312": "which changes several unemployment and workplace rules, including a shorter employer protest window",
 "HB 5269": "a bill to tighten online gambling rules, including one account per platform and no credit cards",
 "HB 8002": "which requires every town to adopt a housing growth plan and creates first-time homebuyer savings accounts",
 "SB 6": "a bill to expand state supports for children under five and disconnected youth",
 "SB 1356": "a bill to widen the consumer data privacy law to more companies, data brokers and social media",
 "SB 1222": "a bill to extend workers' compensation to public works employees traveling to emergency call-ins",
 "SB 1488": "a bill to let the Comptroller withhold payment from contractors under a prevailing wage stop work order",
 "SB 1371": "a bill to require just cause and a neutral hearing officer before firing a tenured teacher",
 "SB 1481": "a bill to make Medicaid providers agree in writing not to discriminate",
 "HB 6913": "which bars nursing homes and assisted living communities from discriminating against residents",
 "SB 1358": "which makes state agencies raise nonprofit human services contract rates with inflation from 2027",
}
