EFFECTS = {
 "HB 67": ("House Bill 67", "which caps private-lot towing charges at $250 for the tow and $50 a day for storage"),
 "HB 62": ("House Bill 62", "which bars utilities from shutting off a home's power or gas over the holidays, on freezing or extreme-heat days, or without 14 days' notice"),
 "HB 56": ("House Bill 56", "which makes health plans and Medicaid cover surgery to remove excess skin when a doctor finds it medically needed"),
 "HB 130": ("House Bill 130", "which gives public employee unions new workers' contact details and lets them meet workers in public buildings"),
 "HB 119": ("House Bill 119", "the Freedom to Read Act, which bars public and school libraries from pulling books because of the author or the ideas in them"),
 "HB 105": ("House Bill 105", "which makes employers with 26 or more workers state the pay range and benefits in every job ad"),
 "HB 205": ("House Bill 205", "which shields Delaware health care providers from other states' penalties for care that is legal in Delaware"),
 "HB 48": ("House Bill 48", "which requires permits and inspections for disabled parking spaces and raises the fine for parking in one illegally from $200 to $250"),
 "HB 37": ("House Bill 37", "which makes clear that state and local government agencies must follow Delaware's ban on discrimination in public places"),
 "HB 153": ("House Bill 153", "which ends citizen's arrests in Delaware, so only people a law names may arrest or hold someone"),
 "HB 182": ("House Bill 182", "which bars Delaware police from signing federal 287(g) deals to do civil immigration enforcement or hold immigration detainees"),
 "HB 210": ("House Bill 210", "the Pollution Accountability Act, which raises the daily fines for breaking Delaware environmental laws to as much as $40,000"),
 "SB 60": ("Senate Bill 60", "which bars utilities from billing customers for lobbying, political donations, or image advertising"),
 "SB 24": ("Senate Bill 24", "which lets a public employee union be certified without an election once more than half the workers sign cards for it"),
 "HB 50": ("House Bill 50", "which creates the Delaware Energy Fund to help households under 350% of the poverty level pay energy bills"),
 "HB 116": ("House Bill 116", "which lets regulators approve power and gas delivery rates 20% below standard for low-income households"),
 "HB 70": ("House Bill 70", "which requires rental homes built before 1978 to pass a lead paint inspection, with state grants and loans to help landlords pay"),
 "HB 150": ("House Bill 150", "which bars civil (non-criminal) arrests of people going to or from Delaware courthouses"),
 "HB 94": ("House Bill 94", "which bars Delaware police from helping federal immigration arrests at schools, colleges, places of worship, and health care sites"),
 "HB 151": ("House Bill 151", "which bars Delaware and its local governments from paying private companies to run jails or detention centers"),
 "SB 250": ("Senate Bill 250", "which rewrites Delaware's parentage law so a child's legal parents are defined the same way whatever the parents' gender or marital status"),
 "HB 348": ("House Bill 348", "which removes the dollar caps and the $50,000 price limit on Delaware's electric car rebates and lets the state set the amounts"),
 "SB 201": ("Senate Bill 201", "which requires a state license for people who flip home purchase contracts and gives sellers 21 days to cancel such a deal"),
 "HB 369": ("House Bill 369", "which writes the state Office of Gun Violence Prevention and Community Safety into law so a future governor cannot undo it by order"),
 "HB 380": ("House Bill 380", "which extends Delaware's personal data privacy law to companies holding data on 10,000 or more Delawareans, down from 35,000"),
 "HB 344": ("House Bill 344", "which tightens campaign finance rules: five-year record keeping, written loans, mandatory training, and a filing freeze for ignored late notices"),
 "HB 418": ("House Bill 418", "which gives owners of untraceable ghost guns six months to get a serial number stamped on them or make them unusable"),
 "HB 423": ("House Bill 423", "which enrolls new state workers in a retirement savings plan by default, taking 3% to 15% of pay unless they opt out"),
 "HB 368": ("House Bill 368", "which bars Delaware police from holding people on immigration requests no judge signed, except violent felons and some repeat offenders"),
 "HB 444": ("House Bill 444", "the Delaware John Lewis Voting Rights Act, which lets voters sue over rules that hold back minority voters and requires voting help in other languages"),
 "SB 23": ("Senate Bill 23", "the Housing for Every Delawarean Act, which makes counties and towns plan for 20% affordable housing and allow denser housing"),
 "HB 427": ("House Bill 427", "which lets 16- and 17-year-olds target shoot and hunt without an adult present, with a parent's permission and a hunter safety course"),
 "SB 13": ("Senate Bill 13", "which makes hospitals give free medically necessary care to Delaware residents earning up to three times the poverty level, with discounts above that"),
 "SB 300": ("Senate Bill 300", "which requires gun dealers to hold a state license with cameras, alarms, employee background checks, and staff training"),
 "SB 326": ("Senate Bill 326", "which tightens oversight of power and gas companies, including regular management reviews and limits on collecting rate hikes before approval"),
 "HB 233": ("House Bill 233", "which makes data centers and other very large power users pay their own hookup and rate costs so other customers do not"),
 "HB 310": ("House Bill 310", "which takes Delaware's job-creation tax break away from data centers and other very large power users unless they run on clean energy"),
 "SB 82": ("Senate Bill 82", "which lets courts order a person found dangerous to give up their guns for up to five years, up from one year"),
 "HB 36": ("House Bill 36", "which extends every ground covered by Delaware's main anti-discrimination laws to its smaller anti-discrimination rules"),
 "HB 154": ("House Bill 154", "which protects charities and police from lawsuits when they give away free gun locks and safes"),
 "HB 91": ("House Bill 91", "which makes school breakfast free for every student at public schools in the federal breakfast program, with the state paying the gap"),
 "HB 269": ("House Bill 269", "which makes power companies adopt the national standard rules for connecting rooftop solar to the grid"),
}
