OPEN = {
 1531585: ("Voted to accept the House's version of Senate Bill 1", "Voted against the House's version of Senate Bill 1"),
 1358055: ("Voted to pass House Bill 1EX", "Voted against House Bill 1EX"),
 1361975: ("Voted to pass House Bill 1EX", "Voted against House Bill 1EX"),
 1361973: ("Voted to pass Senate Bill 1EX", "Voted against Senate Bill 1EX"),
 1358054: ("Voted to pass Senate Bill 1EX", "Voted against Senate Bill 1EX"),
 1362081: ("Voted to pass Senate Bill 3EX", "Voted against Senate Bill 3EX"),
 1361977: ("Voted to pass Senate Bill 3EX", "Voted against Senate Bill 3EX"),
 1711338: ("Voted to pass the House rewrite of Senate Bill 3EX", "Voted against the House rewrite of Senate Bill 3EX"),
 1535196: ("Voted to accept the Senate's change to Senate Bill 40", "Voted against accepting the Senate's change to Senate Bill 40"),
 1674280: ("Voted to accept the Senate's changes to House Bill 1185", "Voted against accepting the Senate's changes to House Bill 1185"),
 1676408: ("Voted to accept the final version of House Bill 1247", "Voted against the final version of House Bill 1247"),
 1676409: ("Voted to accept the final version of House Bill 1247", "Voted against the final version of House Bill 1247"),
 1676416: ("Voted for the Senate's rewrite of House Bill 463", "Voted against the Senate's rewrite of House Bill 463"),
 1676417: ("Voted yes on the final version of House Bill 463", "Voted no on the final version of House Bill 463"),
 1537730: ("Voted to accept the House rewrite of Senate Bill 244", "Voted against the House rewrite of Senate Bill 244"),
 1665920: ("Voted to accept the House rewrite of Senate Bill 220", "Voted against the House rewrite of Senate Bill 220"),
 1672157: ("Voted to accept the House rewrite of Senate Bill 472", "Voted against the House rewrite of Senate Bill 472"),
 1670665: ("Voted to pass Senate Bill 472", "Voted against Senate Bill 472"),
}
CLOSE = {
 1531612: "The House agreed 120-42, and it became law as Act 10.",
 1535196: "The House agreed 91-63, and it became law as Act 278.",
 1670665: "The Georgia House passed it 96-58, and it became law as Act 722.",
 1674280: "The Georgia House agreed 97-65, and it became law as Act 460.",
 1676408: "The Georgia House agreed 98-70, and it became law as Act 718.",
 1676416: "The Georgia House agreed 104-71, and it became law as Act 465.",
 1524305: "The Senate agreed 34-21, and it became law as Act 9.",
 1531585: "The Georgia Senate agreed 34-20, and it became law as Act 11.",
 1531612: "The House agreed 120-42, and it became law as Act 10.",
 1537730: "The Georgia Senate agreed 35-18, and it became law as Act 361.",
 1665920: "The Georgia Senate agreed 38-14, and it became law as Act 712.",
 1672157: "The Georgia Senate agreed 29-17, and it became law as Act 722.",
 1676409: "The Georgia Senate agreed 34-18, and it became law as Act 718.",
 1676417: "The Georgia Senate agreed 33-20, and it became law as Act 465.",
}
IDX = {
 14: {"eff": "a new map of Georgia's state Senate districts to replace the 2021 map a federal court struck down"},
 44: {"eff": "a new map of Georgia's state Senate districts to replace the 2021 map a federal court struck down"},
 18: {"eff": "the Riley Gaines Act of 2025, which bars males from female school sports teams and sets facilities aside by sex"},
 51: {"eff": "the Riley Gaines Act of 2025, which bars males from female school sports teams and sets facilities aside by sex"},
 15: {"eff": "a new map of Georgia's congressional districts to replace the 2021 map a federal court struck down"},
 46: {"eff": "a new map of Georgia's congressional districts to replace the 2021 map a federal court struck down"},
 30: {"eff": "which sets up a committee to design a hand-marked paper ballot voting system and orders hand recounts in close races"},
 58: {"eff": "which sets up a committee to design a hand-marked paper ballot voting system and orders hand recounts in close races"},
}
EFFECTS = {
 "HB 500": "which creates the crime of arson of a law enforcement vehicle, with five to 20 years in prison",
 "SB 140": "which bans hormone therapy and sex reassignment surgery for minors treated for gender dysphoria",
 "SB 44": "which sets a prison term of at least five years for recruiting someone into a criminal street gang",
 "SB 159": "which raises penalties for inmates caught with banned items and for staff who bring them in",
 "SB 222": "which bars election officials from taking private donations and makes the State Election Board its own agency",
 "SB 63": "which requires money bail for a longer list of offenses and caps how many cash bonds a person may post",
 "HB 557": "which lets nurse practitioners and physician assistants prescribe some Schedule II drugs",
 "HB 1018": "which bars banks from using a merchant code that marks gun shops and bars any registry of gun owners",
 "SB 362": "which strips economic development incentives from employers that accept a union on signed cards alone",
 "HB 1339": "which loosens the certificate of need rules for new hospitals and raises the rural hospital tax credit",
 "SB 420": "which bars companies and agents of foreign adversary governments from buying Georgia farmland",
 "SB 351": "which bars social media accounts for children under 16 without a parent's consent",
 "HB 1105": "which requires jails to check immigration status and honor federal detainer requests",
 "HB 1": "a new map of Georgia's state House districts to replace the 2021 map a federal court struck down",
 "SB 144": "which lets a federally approved pesticide label satisfy the maker's health-warning duty",
 "SB 68": "which limits pain-and-suffering arguments, allows seat-belt evidence and tightens other lawsuit rules",
 "SB 69": "which makes companies that fund other people's lawsuits register with the state and limits what they may do",
 "SB 212": "which bars schools giving student directory information to campaigns and makes leaking voter data a felony",
 "SB 40": "which puts catalytic converters under the scrap metal law and bans cash for them",
 "SB 244": "which pays wrongly imprisoned people $75,000 per year and makes counties cover defense costs after prosecutor misconduct",
 "HB 1164": "which requires state audits of high-risk school systems and more public financial notices",
 "SB 443": "which makes blocking a highway after a police order a high and aggravated misdemeanor",
 "SB 472": "which lets the State Board of Education ask the governor to suspend school board members over money mismanagement",
 "HB 1185": "which makes it harder for shareholders to sue companies and see company records",
 "SB 552": "the True Patriotism and Universal Student Access Act, which lets students form political clubs at school",
 "HB 1247": "the Georgia Bureaucratic Deference Elimination Act, which bars courts from deferring to an agency's reading of the law",
 "HB 463": "which cuts the personal income tax rate from 5.19 to 4.99 percent in 2026 with further cuts to 3.99 percent",
 "SB 517": "which gives police officers immunity from charges and lawsuits when their use of force was lawful",
 "HB 1015": "which cut the personal income tax rate to 5.39 percent for 2024 with yearly cuts toward 4.99 percent",
 "SB 414": "which bars agencies from collecting or releasing lists of nonprofit members, supporters or donors",
 "SB 185": "which bars state money for prisoners' sex-change surgery or hormone therapy",
 "SB 220": "the Putting Georgia's Patients First Act, which lets medical cannabis patients get the plant, oils and extracts",
}
