EFFECTS = {
 "SF 418": "which defines sex by a person's body at birth and removes gender identity from the Iowa Civil Rights Act",
 "HF 299": "which makes schools and child care centers tell parents about legal vaccine exemptions",
 "HF 316": "which adds career planning lessons in grades five and six",
 "HF 398": "which shifts power over Iowa's prisons from the Board of Corrections to the department's director",
 "HF 546": "a bill to set a minimum $100,000 bond at first court appearance for six violent or gun crimes",
 "HF 401": "a bill to set general education requirements, including western and American heritage courses, at public universities",
 "HF 295": "which bars an accrediting agency from punishing an Iowa public college for following state law",
 "HF 440": "which requires 30 days' notice of proposed tuition increases at Iowa's public universities",
 "HF 437": "which creates a Center for Intellectual Freedom at the University of Iowa",
 "HF 269": "a bill to bar public universities from requiring diversity or critical race theory courses for a degree",
 "SF 603": "which reorganizes the state workforce agency and bars cities from setting pay rules for contractors",
 "HF 928": "which limits election recounts to very close margins and rewrites how contests are run",
 "HF 946": "a bill to penalize police and sheriffs who refuse to follow Iowa's immigration enforcement law",
 "HF 792": "a bill to make giving someone fentanyl that causes their death first-degree murder",
 "HF 785": "which lets United States citizens from outside Iowa sit on charter school boards",
 "HF 767": "which changes the private sector drug testing law in employers' favor",
 "SF 369": "which makes passing a civics test a condition of graduating from high school",
 "SF 175": "which adds fetal development lessons, including an ultrasound video, in grades five and six",
 "HF 516": "which requires 80 percent of University of Iowa medical and dental students to be Iowans",
 "HF 856": "which bars governments and public colleges from spending money on diversity, equity and inclusion programs",
 "SF 615": "which requires most adults on Medicaid expansion to work 80 hours a month to keep coverage",
 "HF 2488": "a bill to bar private colleges whose students get state tuition grants from running diversity offices",
 "HF 2584": "a bill to make the area within 300 feet of a homeless shelter a drug-free zone",
 "HF 2296": "which bans cities and counties from issuing their own identification cards",
 "HF 2102": "a bill to require every driver's license test to be given in English",
 "HF 2527": "which shields farms, fuel makers and other businesses from climate change lawsuits",
 "HF 2529": "a bill to make farm equipment makers share repair tools for diesel exhaust fluid systems",
 "HF 2244": "a bill to expand civics teaching in Iowa schools",
 "HF 2539": "which repeals several higher education programs, including minority educator vouchers",
 "HF 2513": "a bill to bar Iowa colleges from hiring certain H-1B visa holders",
 "HF 2711": "which removes affirmative action from Iowa law",
 "HF 2718": "a bill to bar state and local agencies from enforcing any red flag gun law",
 "HF 2557": "a bill to say raising a child consistent with the child's sex is not child abuse",
 "SF 579": "which stops cities and counties from passing civil rights laws broader than state law",
 "HF 2624": "a bill to require DNA samples from people arrested for a felony",
 "HF 2487": "a bill to give the attorney general new power to enforce the ban on diversity offices",
 "HF 2329": "which raises the interest that licensed lenders may charge on regulated loans",
 "HF 2133": "a bill to list kratom as a Schedule I controlled substance",
 "HF 571": "which creates the Medical Ethics Defense Act, letting providers refuse care that goes against their conscience",
 "HF 2501": "which makes several changes to how Iowa runs elections, including cancelling registrations with matching records",
 "HF 2254": "which bans noncompete clauses at the University of Iowa Hospitals and Clinics",
 "SF 2399": "which makes it harder to be released before trial by limiting bail below the uniform bond schedule",
 "SF 304": "which takes away a minor's ability to get a sexually transmitted infection vaccine without a parent's consent",
 "SF 2263": "a bill to let people keep guns in their vehicles in public parking lots",
 "SF 473": "which bars the state from ruling out foster parents over their beliefs about sexual orientation or gender identity",
 "HF 2670": "which rewrites parts of what Iowa schools must teach, dropping the multicultural and gender-fair approach",
 "HF 2788": "which adds rules for abortion drugs, including an in-person exam and signed consent",
 "HF 2763": "a bill to make farm equipment makers share manuals, parts and tools with owners and repair shops",
 "SF 2480": "which taxes and regulates electronic cigarettes and other tobacco-free nicotine products",
 "SF 469": "which creates an emeritus medical license for doctors 60 and older who train residents",
 "SF 472": "which tightens the rule that public employee unions must win a new election before each contract ends",
 "SF 2218": "which bans employing anyone the employer knows gave a Social Security number that is not theirs",
 "SF 394": "a bill to shield pesticide makers from failure-to-warn lawsuits when the label was federally approved",
 "SF 180": "a bill to let people refuse emergency-use vaccines or drugs for reasons of conscience",
 "HF 924": "which lowers the minimum age for a permit to carry a handgun from 21 to 18",
 "HF 706": "which raises the fines for officials who break Iowa's open meetings law",
 "SF 383": "which regulates pharmacy benefit managers, setting a floor on what they pay Iowa pharmacies",
 "SF 2203": "a bill to check every registered voter's citizenship against a federal database",
 "SF 2274": "a bill to repeal Iowa's ban on selling devices that make a gun fire faster",
 "SF 2442": "a bill to bar counties from restricting housing of up to 12 units outside city limits",
 "SF 2444": "a bill to exempt cigar bars from Iowa's indoor smoking ban",
 "HF 2694": "which bars the governor from closing or placing any requirement on places of worship",
 "SF 2284": "a bill to set new limits on automatic license plate readers",
 "SF 2422": "which tightens eligibility rules for food assistance and Medicaid",
 "SF 378": "which raises Iowa's default speed limit from 55 to 60 miles per hour",
 "HF 2230": "which changes how Iowa trains and licenses teachers from July 2027",
 "HF 2724": "which creates new teaching endorsements in fine arts, mathematics and science",
}
