EFFECTS = {
 "H 7": "which sets a minimum $300 fine for adults convicted of possessing a small amount of marijuana",
 "H 35": "which requires multifactor login security across Idaho state government",
 "H 32": "which bans mask mandates by any state or local body in Idaho",
 "H 79": "which raises the cap on community college tuition from $2,500 to $3,250 a year",
 "H 187": "which sets out what people on felony probation and parole must be told and agree to",
 "H 245": "which raises the age limit for extended foster care from 21 to 23",
 "H 294": "which removes the caps on civil penalties for breaking pipeline safety laws",
 "H 240": "which opens outdoor campus areas at public colleges to speech and bans free speech zones",
 "H 290": "which moves school and daycare vaccine requirements from health board rules into state law",
 "S 1069": "which requires literacy training for every teacher and elementary administrator of young children",
 "H 135": "which removes exemptions from the lawful presence check for public benefits",
 "S 1139": "which limits the automatic felony bar on becoming a police officer to serious felonies",
 "H 398": "which rewrites Idaho's lobbying rules and widens what counts as lobbying",
 "H 136": "which makes hospitals and clinics report what they earn from the 340B discount drug program",
 "S 1183": "which presumes a utility was not negligent in a wildfire if it followed an approved mitigation plan",
 "H 271": "which makes it a misdemeanor to advertise a product or service that is illegal where offered",
 "H 109": "which orders the state to seek a federal waiver removing candy and soda from food stamps",
 "H 180": "which puts city and county decisions on broadband and cell tower permits on a clock",
 "S 1198": "which bans diversity, equity and inclusion offices and required training at public colleges",
 "H 253": "which lets agencies treat public records requests from non-residents differently",
 "S 1180": "which sets rules for how agencies may use automated license plate readers",
 "S 1210": "the Idaho Medical Freedom Act, which bars almost every medical requirement in the state",
 "H 583": "which narrows what cities and counties may do about short-term rentals",
 "H 667": "which ends Idaho's non-domiciled commercial driver's license program",
 "H 723": "which adds state oversight and inspection of children's residential care facilities",
 "H 562": "which raises insurance cancellation notice from 30 to 60 days",
 "H 849": "which credits industry experience to raise pay for career technical education teachers",
 "H 752": "which makes using a restroom or changing room meant for the opposite sex a misdemeanor",
 "S 1257": "which limits face-to-face visits in child protection cases involving abuse",
 "S 1269": "which sets up a state cloud seeding program",
 "H 508": "which widens when highway districts may build bike lanes and sidewalks",
 "H 776": "which requires child protection checks within twelve hours for babies in risky homes",
 "H 929": "which lets an insured patient pay cash and still get credit toward their deductible",
 "H 930": "which requires campaigns to keep all money in a dedicated checking account",
 "S 1311": "which tightens ignition interlock rules for drunk driving offenders",
 "S 1288": "which creates a state fund to help schools pay for very expensive special education",
 "S 1300": "which lets the governor appoint the directors of Fish and Game, Transportation and Parks",
 "S 1294": "which requires every newborn to be screened for hearing loss",
 "S 1354": "which requires cities to allow accessory dwelling units on single-family lots",
 "S 1352": "which requires larger cities to allow small starter home subdivisions",
 "H 810": "which requires legislative candidates to have kept a fixed home inside the district",
 "H 516": "which bars school districts from deducting union dues or using public money to support teachers unions",
 "S 1046": "which requires a fetal development lesson with an ultrasound video in grades five through twelve",
 "S 1099": "which raises the penalty for vehicular manslaughter by a repeat drunk driver",
 "S 1007": "which lets residents speak at school board meetings on matters not on the agenda",
 "H 40": "which cuts the income tax rate from 5.695 to 5.3 percent and exempts military retirement pay",
 "H 86": "which bars governments from requiring electric vehicle charging in new buildings",
 "H 149": "which restricts lenders' use of mortgage trigger leads to solicit loan applicants",
 "H 146": "which requires new wind farms to seek radar systems that keep warning lights off until aircraft approach",
 "S 1141": "which bans camping and sleeping in public places across Idaho",
 "H 134": "which makes health plans pay for a yearly extra breast cancer screening for people at higher risk",
 "H 96": "which limits the flags a government body may fly to a short official list",
 "H 339": "which builds a monthly data feed of deaths and license changes to clean voter rolls",
 "S 1211": "which lets people buy ivermectin without a prescription",
 "S 1297": "the Conversational AI Safety Act, which makes chatbots disclose they are artificial intelligence",
 "H 542": "the Stop Harms from Addictive Social Media Act, which puts parents in control of a child's account",
 "H 561": "which tightens the 2025 flag rules for government property and adds a fine",
 "H 822": "the Pediatric Secretive Transitions Parental Rights Act, which requires schools and clinicians to tell parents",
 "H 706": "which lets cities allow apartment buildings with a single stairway",
}
