IDX = {
 86: {"yea": "Voted yes to accept the Senate's rewrite of House Bill 5090, which lets rideshare drivers organize and bargain as a group with the companies. The Illinois House agreed 83-28 and the bill became law as Public Act 104-0788."},
 78: {"close": "The House passed it 71-37; the Senate later narrowed and delayed it, and that version became law."},
 102: {"close": "The House passed it 73-34; the Senate later changed key definitions, and that version became law effective July 1, 2027."},
 100: {"close": "The House passed it 72-38, the Senate agreed, and it became law."},
 142: {"yea": "Voted to pass House Bill 460 in the Illinois Senate, which extends state college aid eligibility at city and county colleges to residents barred from federal aid, including undocumented students. The Senate passed it 34-18 and it became Public Act 104-164, effective January 1, 2026."},
 147: {"close": "The Senate accepted this larger Medicaid package 36-19, and it became law."},
 181: {"close": "The Senate passed it 38-20; the House later narrowed it, and that version became law."},
}
EFFECTS = {
 "HB 2397": "the Eddie Thomas Act, which makes state prisons publish a yearly report on hospice and end-of-life care for people in custody",
 "HB 1430": "which lets the State Treasurer make and buy loans that refinance student debt",
 "HB 1616": "which gives part-time employees the same 10 days of organ donor leave full-time employees already had",
 "HB 3489": "which lets pharmacists provide all forms of birth control, including emergency birth control, with Medicaid covering their services",
 "HB 1189": "which applies Illinois wage rules to federally funded construction run by an Illinois public body",
 "HB 1373": "which requires police to trace every crime gun through the federal eTrace system and share the results with other Illinois agencies",
 "HB 3046": "which lets a university and its employees' union agree to contract terms that give workers more rights than civil service rules",
 "HB 3751": "which makes the state's economic equity office support businesses that hire and train people facing serious barriers to work",
 "HB 2425": "which bars life insurers from denying or charging more for final-expense coverage because of a felony conviction",
 "HB 3566": "which lets a child wrongly named as a defendant in an eviction case recover attorney fees and $1,000 in damages",
 "HB 2517": "which requires health professionals to take an hour of hidden-bias training to renew a license, with maternal-care training added in 2026",
 "HB 2436": "which lets Cook County public defenders handle immigration cases for county residents wherever they are heard",
 "HB 3352": "which lets a person tell a collection agency in writing that a debt was coerced, such as by an abusive partner",
 "HB 2726": "which lets the Department of Natural Resources use rewilding, returning land to its natural state and bringing back native species",
 "HB 3097": "which requires every school district to help each high school student complete the federal or state student aid application",
 "HB 3309": "which makes schools send union member information to the statewide union as well as the local one",
 "HB 2464": "which caps what a family pays for out-of-network emergency intensive care for a newborn at in-network cost",
 "HB 460": "which bars limits on state college grants for covered students and requires the widest aid eligibility state law allows",
 "SB 19": "which lets a person with a protective order against a parole candidate submit a victim statement to the Prisoner Review Board",
 "SB 69": "which requires health plans issued after January 1, 2027 to cover equine therapy when a doctor says it is needed",
 "SB 191": "which requires lap-and-shoulder belts on every seat of new school buses bought from July 2031",
 "SB 212": "which requires employers to pay nursing mothers for pumping breaks and bars making them use paid leave for it",
 "SB 1261": "which creates a task force on community land trusts, a way of keeping homes affordable long term",
 "SB 175": "which requires health plans issued after January 1, 2027 to cover the tests used to diagnose Klinefelter syndrome",
 "SB 1173": "which bars notaries from charging a fee to notarize the form a homeless person uses to get a state ID",
 "SB 1441": "which requires employers to enroll every worker of 120 days or more in the state's Secure Choice retirement savings program",
 "SB 1560": "which gives schools model procedures for screening every student for mental health needs",
 "SB 1947": "which makes every Illinois teacher training college pilot the state's teacher performance assessment from 2026 to 2029",
 "SB 67": "which requires nurse staffing agencies to hold a state license to operate in Illinois",
 "SB 1181": "which extends the state's anti-SLAPP law to press freedom and makes frivolous filers pay the other side's legal fees",
 "SB 2164": "which raises the fee for employers that underpay workers and makes a final Labor Department order enforceable like a court judgment",
 "SB 405": "which requires public school counseling to serve every student regardless of citizenship status",
 "SB 1920": "which tells the State Board of Education to write statewide guidance on using artificial intelligence in schools",
 "SB 2280": "which makes the Office of Firearm Violence Prevention report which communities face concentrated gun violence and what is spent there",
 "SB 1859": "which creates a task force on how flooding, heat, and other climate damage push Illinois residents out of their homes",
 "SB 1519": "which requires school districts to report referrals of students to police and keep a written agreement with local police",
 "SB 8": "which requires gun owners to lock guns away from minors and at-risk people and report lost guns within 48 hours",
 "HB 3247": "which bars public schools from denying education or parent activities because of a child's or parent's immigration status",
 "SB 1797": "which requires companies that hold or trade cryptocurrency for Illinois residents to register with the state and follow consumer rules",
 "SB 1976": "which stops state agencies from weakening worker-pay or coal-mine safety rules below the federal protections in place in April 2025",
 "HB 2419": "which makes local officials weigh traffic pollution and existing pollution on nearby communities before approving a waste facility",
 "HB 3248": "which requires health plans issued after January 1, 2027 to cover medically necessary laser hair removal",
 "SB 453": "which extends fast-track first-contract bargaining rules to newly certified public employee unions of every size",
 "SB 2319": "which requires crypto cash machine operators to register with the state, cap fees, and give clear warnings and receipts",
 "SB 1344": "which applies prevailing wage rules to camera sewer inspections and penalizes contractors that skip certified payroll on public jobs",
 "HB 3385": "which requires every public college to give students access to at least three licensed mental health professionals",
 "HB 3709": "which requires public colleges to give students access to providers who can prescribe birth control and medication abortion",
 "SB 24": "which requires every police agency to take missing person reports without making families wait",
 "SB 2339": "which protects workers responding to federal work-eligibility mismatches, with Labor Department enforcement and private lawsuits",
 "HB 2516": "which bans cosmetics, dental floss, children's products, menstrual products, and underwear with added PFAS chemicals from 2032",
 "HB 3019": "which makes health insurers keep reporting how much of premiums goes to claims, and pay refunds, if federal rules end",
 "SB 2437": "which lets Medicaid patients bring a Medicaid doula to childbirth and covers several other Medicaid changes",
 "HB 3363": "which creates a State Public Defender Commission to plan a statewide Office of the State Public Defender",
 "HB 1083": "which makes marriage and property laws gender-neutral and waives deed fees for recording a legal name change",
 "HB 2987": "which requires every Illinois warehouse to write a yearly tornado safety plan and build new warehouses to withstand tornadoes",
 "HB 3026": "which makes the state guide schools on dual-language programs and plan to hire and keep bilingual teachers",
 "HB 4844": "which requires employers with more than 25 workers to pay regular wages during jury duty",
 "HB 4304": "which requires public colleges to keep classrooms free of unlawful bias and protect students' right to speak and gather",
 "HB 5024": "which bars immigration detention centers within 1,500 feet of a school, day care, park, home, or place of worship",
 "HB 1312": "which lets people sue immigration officers who knowingly violate constitutional rights and requires hospital immigration policies",
 "SB 3037": "the Dark Sky Act, which limits how much outdoor light from commercial buildings may spill past the property line",
 "HB 4571": "which lets large counties buy land, give grants, and sell property below market value for affordable housing",
 "SB 3341": "which lets any minor consent to birth control without a parent's approval",
 "HB 4533": "which requires money transfer companies to offer customers a voluntary donation to the Illinois DREAM Fund scholarship program",
 "HB 4273": "which bars home insurers from raising a renewal premium over 10% without 60 days' notice",
 "HB 4456": "which lets regulators approve low-income discounts covering an entire home gas or electric bill, funded by a fixed charge on other customers",
 "SB 4006": "which requires home insurers to say in writing whether flood coverage is available and disclose their climate risks",
 "SB 2972": "which requires liability insurance for motorboats over 10 horsepower, boats over 21 feet, and personal watercraft",
 "HB 4948": "which suspends the license of drivers with two speeding offenses in a year unless they drive with a speed-limiting device",
 "HB 3460": "which bars the state from delaying a barber, cosmetology, or nail technology license application because the applicant is in prison",
 "SB 3772": "which requires extra review of air pollution permits in communities already carrying unfair pollution burdens, starting 2027",
 "HB 4577": "which defines play-based learning in kindergarten in state law",
 "HB 4339": "which requires every high school district to give eligible graduating students a chance to register to vote",
 "HB 5492": "which requires health plans from 2028 to cover up to a six-month supply of prescribed hormone therapy at once",
 "SB 3465": "which sets sanitary requirements for construction sites, including menstrual hygiene products",
 "HB 4461": "which bars hospitals and medical-debt creditors from placing a lien on a patient's main home",
 "SB 1743": "which lets prescribing psychologists write prescriptions for patients over 65",
 "HB 4491": "which guarantees full gross pay for up to a year to police, firefighters, paramedics, and prison staff hurt on duty",
 "HB 5093": "which widens in-state college tuition and state aid by dropping a school-attendance condition",
 "SB 3565": "which lets a township spend its public aid money on food banks and food pantries",
 "HB 5390": "which requires hospitals to use one state financial assistance form and honor approvals for at least 12 months",
 "SB 3917": "which requires testing for PFAS forever chemicals at every major sewage plant and industrial discharger",
 "HB 4639": "which lets judges set up mediation programs for young people accused of crimes and consider restorative practices before sentencing",
 "SB 3222": "the Illinois Hemp Act, which requires a license to make or sell hemp products and lets the state order recalls",
 "HB 4606": "which lets the state build a program of short-term home visits for every family with a newborn",
 "SB 3020": "which rewrites what counts as harassment under the domestic violence and protective order laws, including electronic harassment",
 "HB 5090": "which lets rideshare drivers organize and bargain as a group with the companies, funded by a fee on each Illinois trip",
 "HB 4966": "the SECURE Act, which makes the child welfare agency guard records showing a child's sexual orientation",
 "HB 5284": "which requires health plans to cover medically necessary hormone and non-hormone treatment for menopause",
 "HB 4758": "which lets job ads require a driver's license only when driving is essential to the job",
 "HB 5095": "which lets people choose male, female, or X on a state ID or driver's license",
 "HB 4379": "which requires adult changing tables and accessible restroom space in certain new public buildings built from 2029",
 "HB 1836": "the Clean Slate Act, which automatically seals eligible criminal records and widens who qualifies",
 "SB 714": "which bars car insurers from raising a renewal premium more than 10% without 30 days' notice and lets the state review rates",
 "HB 3409": "which bans cosmetics containing listed harmful chemicals from July 2028",
 "HB 5460": "which widens who may receive a School Social Work scholarship",
 "HB 4217": "which lets a public defender also represent a client in the license suspension case that grew out of the same arrest",
 "HB 4862": "which requires every school board to adopt a written procedure supporting school employees' mental health by 2028",
 "SB 2762": "which requires health plans issued after January 1, 2029 to cover a prescribed seizure detection device",
 "HB 4834": "which removes testosterone, abortion pills, and hormone medicines from the state prescription-tracking program",
 "SB 3777": "which makes rules that unfairly harm protected groups a civil rights violation in jobs, credit, and public places",
 "SB 2914": "which requires a detailed written warning, a chance to respond, and arbitration rights before a tenured teacher can face dismissal",
 "HB 5295": "which makes health networks wall off abortion records from out-of-state sharing",
 "HB 4788": "which requires high school CPR training to use manikins with breasts as well as without, from the 2029-30 school year",
 "SB 25": "Illinois' 2025 energy law, which expands battery storage, rooftop solar rights, and EV charging",
 "HB 4418": "which requires the state to control plastic pellet pollution in stormwater from factories",
 "HB 3564": "which caps rental application fees at $50 and voids landlord fees not listed in the ad and lease",
 "HB 4890": "which lets a court take unaccompanied immigrant children in federal care under its protection, opening health and school services",
 "HB 4725": "which lets the attorney general investigate, inspect workplaces, and interview workers before suing over worker protections",
 "HB 4702": "the Diaper Labeling Act, which requires makers to list what is in a diaper",
 "HB 4514": "which requires utilities seeking a rate increase to tell customers they may request a public forum on it",
 "SB 3487": "which requires hospitals to offer flu shots from September through March and pneumonia shots at admission or discharge",
 "HB 5070": "which bars the state Pollution Control Board from adopting a federal rule weaker than one it already has",
 "HB 4420": "which makes media produced at state colleges a public forum and bars officials from reviewing content before publication",
 "HB 4277": "which lets a person with a felony conviction become a notary 10 years after finishing their sentence",
 "HB 5316": "which lets the state emergency agency enter private land to sample soil, water, and air after a radioactive release",
 "SB 4025": "which requires landowners statewide to let the water utility replace lead service lines for free",
 "SB 3314": "which requires a yearly public report on how many credit hours full-time faculty teach at Illinois public colleges",
 "SB 4041": "which requires airports to publish a noise contour study every five years starting by 2030",
 "SB 3066": "the Service Appointment Fairness Act, which makes breaking its appointment booking rules a consumer fraud violation",
 "HB 1859": "which requires community college courses to be taught by qualified faculty, not artificial intelligence alone",
 "HB 2568": "which gives children equal parentage rights regardless of their parents' marriage, gender, or use of assisted reproduction",
 "HB 4397": "which raises the training required to work as a school psychologist to a 60-hour graduate degree and 1,200 supervised hours",
}
