EFFECTS = {
 "HB 1041": "which makes colleges label sports teams by sex and bars males from women's teams",
 "SB 424": "which lets electric utilities charge customers for planning a small nuclear reactor before holding a permit",
 "SB 450": "which sets rules for Indiana's delegates to any constitutional convention",
 "SB 365": "which makes the state track whether career course graduates end up in matching jobs",
 "SB 2": "which requires Healthy Indiana Plan adults to work, train or volunteer at least 20 hours a week",
 "SB 423": "which sets up a program for building small nuclear reactors with early costs on customer bills",
 "HB 1393": "which makes jails alert the sheriff when they book someone believed to be in the country unlawfully",
 "HB 1079": "which cuts the wait before a storage firm may sell a tenant's belongings from 90 days to 45",
 "HB 1037": "which stops local governments setting stricter building site run-off rules than the state",
 "HB 1680": "which requires proof of citizenship for some voter registrations and adds regular election checks",
 "SB 289": "which bars public employers and schools from using race or sex in hiring, admissions or aid",
 "HB 1003": "which makes labs and scan centers post cash prices for 50 common services and cuts some patient bills",
 "SB 526": "which changes how absentee ballots that must be rejected are handled in voting machine tests",
 "SB 358": "which raises school reading standards and tightens a school choice fund",
 "SB 475": "which bans new noncompete deals that stop doctors working for a rival after leaving a hospital",
 "HB 1274": "which stops insurers making customers post no-gun signs",
 "SB 258": "which removes Indiana's own permit system for nuclear power plants",
 "SB 112": "which treats a candidate's withdrawal papers as a request to update their voter address",
 "SB 76": "which makes local governments help enforce federal immigration law, including honoring holds",
 "HB 1150": "which limits what homeowners groups and local governments may regulate, including flag displays",
 "HB 1355": "which puts state review of large livestock farms on a 90-day clock",
 "SB 277": "which repeals 84 sections of environment law and turns many agency duties into choices",
 "SB 284": "which limits civilian police oversight boards to an advisory role",
 "SB 285": "which makes camping or sleeping on government land a crime after a warning",
 "HB 1273": "which makes shareholder advisory firms disclose when advice against management lacks a financial study",
 "HB 1001": "which requires yearly local housing reports from 2027 and changes what builders must fit",
 "HB 1302": "which loosens several labor and safety rules, including minor employment registration",
 "HB 1193": "which stops the Civil Rights Commission acting as a person's lawyer in discrimination cases",
 "HB 1368": "which rebuilds the rules for storing carbon dioxide underground so the state can take over permits",
 "SB 409": "which protects a parent's job when they attend a school attendance or special education meeting",
 "HB 1634": "which adds math screening for kindergarten through second grade from the 2026-2027 school year",
 "HB 1004": "which caps what big hospital groups may charge employers at 260 percent of Medicare",
 "SB 140": "which sets network and payment rules for pharmacy benefit managers",
 "HB 1424": "which lets small food producers with up to $1.5 million in sales sell without a license or inspection",
 "SB 78": "which extends the school phone ban to the whole school day",
 "SB 270": "which forces many townships to merge or close based on a state points system",
}
