EFFECTS = {
 "SB 63": "the Help Not Harm Act, which bars puberty blockers, cross-sex hormones and surgery for minors",
 "HB 2106": "which bars foreign money from campaigns over changes to the Kansas constitution",
 "HB 2101": "which stops cities and counties running a guaranteed income program with tax money",
 "SB 137": "which lets police sell guns they have seized instead of destroying them",
 "HB 2109": "which shields power and phone companies from lawsuits over police gear on their poles",
 "HB 2304": "which makes cities and counties report the tax breaks and subsidies they hand out",
 "SB 4": "which requires mailed early ballots to arrive by 7:00 p.m. on election day from 2026",
 "HB 2088": "which puts a 60-day clock on local building permits for houses",
 "SB 35": "which ends two statewide property taxes that paid for state university and institution buildings",
 "HB 2054": "which doubles the caps on contributions to Kansas candidates and parties",
 "HB 2033": "which lets more reading help be paid for out of a school district's at-risk fund",
 "HB 2062": "which counts an unborn child for child support and for state income tax",
 "HB 2382": "which makes schools show a video on how a fetus grows in human development classes",
 "HB 2217": "which lets the state inspector general investigate cash and food assistance fraud",
 "HB 2311": "which protects religious belief in foster care and adoption decisions",
 "SB 269": "which sets up automatic future income tax rate cuts when revenue beats 2024 levels",
 "SB 29": "which takes away the power of local health officials to stop public gatherings",
 "SB 244": "which makes every shared restroom and locker room in a public building open to one sex only",
 "SB 299": "which opens the records of the commission that picks supreme court nominees",
 "HB 2635": "which stops government making pregnancy centers take part in abortion",
 "HB 2593": "which makes local governments explain in public before hiring contingent fee lawyers",
 "HB 2437": "the SAVE Kansas Act, which matches voter lists against federal citizenship data twice a year",
 "HB 2333": "which makes outdoor college campus areas public forums and bans free speech zones",
 "SB 30": "which gives the Legislature the last word on new job licenses from 2026",
 "HB 2727": "which lets people suing over abortion consent rules choose a fixed $5,000 award",
 "SB 375": "which makes proxy advisers say whether a financial analysis backs advice against management",
 "SB 391": "which stops cities and counties passing four kinds of renting rule, including voucher protections",
}
