EFFECTS = {
 "HB 137": "which lets air pollution enforcement rest only on data gathered by federally approved methods",
 "HB 520": "which lowers the bar for police to refuse a public records request",
 "SB 202": "which puts intoxicating hemp drinks under alcohol control, capped at 5 milligrams per serving and 21 to buy",
 "HB 455": "which creates an election investigations unit in the Attorney General's office",
 "HB 6": "which bars state agencies from issuing most new regulations after March 2025 without a certified exception",
 "SB 84": "which tells courts to decide what a law means themselves instead of deferring to the agency's reading",
 "HB 136": "which makes the prison system report far more each year about people leaving prison",
 "HB 424": "which lets public colleges remove tenured faculty for failing performance requirements",
 "HB 695": "which bars changing Medicaid eligibility or coverage without legislative approval and seeks work requirements",
 "HB 399": "which creates new crimes for disrupting the General Assembly, rising to a felony for a third offense",
 "SB 65": "which cancels five proposed agency regulations that legislative committees found deficient",
 "SB 183": "which sets rules for the firms that vote public pension funds' shares, requiring analysis before voting against boards",
 "SB 89": "which narrows which waters Kentucky's environmental protection law covers to four categories",
 "HB 90": "which licenses freestanding birth centers and lists nine procedures a doctor may perform under the abortion law",
 "HB 2": "which voids sales tax notices on currency and bullion sold after August 2024 and lets buyers sue for refunds",
 "HB 495": "which bars Medicaid money for cross-sex hormones or gender surgery and cancels the conversion therapy order",
 "HB 398": "which bars state workplace safety rules for private employers stricter than federal rules",
 "HB 694": "which redirects teacher retiree health money into the pension fund once the health fund is full",
 "HB 216": "which exempts most Department of Agriculture employees from the ban on receiving farm funds from their agency",
 "HB 4": "which bars public colleges from spending money on diversity, equity and inclusion and from treating people differently by race or sex",
 "HB 664": "which lets a police officer in a highway work zone ticket speeders with a camera device",
 "HB 662": "which lets judges and their families have personal details removed from public agency records within 72 hours",
 "HB 606": "which lets local governments in different counties jointly develop large job sites with their own taxing district",
 "HB 7": "which lets school districts put cameras on bus stop arms and fine drivers who pass a stopped bus",
 "HB 1": "which enrolls Kentucky in a federal tax credit for donations to school scholarship organizations",
 "SB 104": "which creates the crime of impeding a first responder within 25 feet after a warning",
 "SB 195": "which shields road contractors from most lawsuits once a government accepts a finished road project",
 "SB 29": "which bars counties from charging fees or requiring permits from out-of-county landfills handling their waste",
 "HB 58": "which limits automated license plate readers to listed uses and caps data storage at 90 days",
 "HB 627": "which caps auto insurance payments for crash medical care at the workers' compensation fee schedule",
 "HB 677": "which sets up the permit system for storing carbon dioxide underground",
 "SB 199": "which makes a federally approved pesticide label a sufficient warning, blocking most failure-to-warn lawsuits",
 "SB 251": "which lets the prison system set death penalty procedures by internal policy instead of public regulation",
 "HB 490": "which lets public college boards remove faculty for financial reasons such as low enrollment",
 "SB 4": "which creates a required principal leadership practicum and redraws the Jefferson County school board",
 "HB 10": "which requires Attorney General approval of large state settlements in the 180 days before a new Governor",
 "HB 355": "which gives one year to sue a real property appraiser and replaces the appraisers board",
 "SB 100": "which gives the Attorney General two seats on the commission that reviews power plant retirements",
 "SB 77": "which creates a state fund for clinical trials of ibogaine as a treatment for opioid addiction",
 "SB 1": "which applies state school board rules to Jefferson County and caps superintendent budget transfers",
 "HB 387": "which exempts veterinarians from reporting controlled substances to the state drug monitoring system",
 "HB 139": "which bars buying voting equipment that records votes with barcodes or QR codes",
 "SB 173": "which makes the Medicaid agency post its plans online and send every proposed change to the legislature",
 "HB 312": "which creates a concealed carry license for people aged 18 to 20",
 "SB 59": "which bars using public money, buildings or employees to campaign on ballot questions",
 "HB 78": "which bars most lawsuits against gun makers and sellers over crimes committed with their guns",
 "SB 324": "which lets unused film tax credit money carry forward and adds video games and commercials",
 "SB 66": "which adds clonazepam, cyclobenzaprine and fentanyl to the drugs that make driving illegal at any amount",
 "SB 2": "which bars public money for cosmetic or elective procedures, including gender surgery, for prisoners",
 "SB 9": "which requires school districts to give staff who give birth up to 30 days of paid maternity leave",
 "HB 45": "which bars foreign nationals from giving to or spending on Kentucky ballot question campaigns",
 "HB 241": "which lets districts make up storm days with longer school days and caps online school enrollment",
 "HJR 15": "which orders the Ten Commandments monument returned to permanent display at the Capitol",
 "SB 28": "which creates a Department of Agriculture grant and loan program for farm and agribusiness projects",
 "SB 137": "which lets foreign-trained doctors get a provisional license to work in underserved areas",
 "HB 189": "which makes it illegal to sit, stand or stay on a state road right-of-way not marked for pedestrians",
 "SB 101": "which requires expelling students in grades 6 to 12 for at least a year for injuring a school employee",
 "SB 219": "which raises the payday loan limit from $500 to $600 with yearly inflation adjustments up to $850",
 "SB 291": "which requires every scrap metal recycler to hold a state license and log every transaction",
}
