EFFECTS = {
 "HB 4": "which limits how far a community association can restrict rooftop solar, defining any rule that raises install cost 5% or cuts output 10% as unreasonable",
 "HB 199": "which changes when the state contacts permanent absentee voters to confirm they still want ballots mailed to them",
 "HB 39": "the Carlton R. Smith Act, which repealed Maryland's crime of knowingly passing on HIV",
 "HB 297": "which made state health insurance subsidies for young adults buying plans on the exchange permanent",
 "HB 277": "which requires water bottle filling stations in new and renovated buildings wherever a drinking fountain is required",
 "HB 324": "which makes every county school board member complete an antibias training course during their term",
 "HB 367": "which stops health licensing boards demanding extra proof of English from applicants already licensed in another state that required it",
 "HB 197": "which makes the state write a plan for restorative practices schools, a discipline model built on relationships and accountability",
 "HB 249": "which bars counties and towns from penalizing landlords or tenants because 911 was called to a rental home",
 "HB 390": "which lets a county waive property tax on a rental building whose owner keeps at least a quarter of units affordable for 15 years",
 "HB 933": "which puts Medicaid nursing home spending under yearly state review of how much goes to front-line staff pay",
 "HB 1380": "which makes minimum childbirth care standards a condition of every hospital's license",
 "HB 1045": "which extends Maryland's medical privacy shield to gender-affirming care records so they cannot be handed to another state",
 "HB 666": "which requires insurers and Medicaid to cover a calcium score heart scan that gauges heart disease risk",
 "HB 1082": "which sets up state subsidies to cushion rising health plan premiums on the state exchange in 2026 and 2027",
 "HB 783": "which adds implicit bias and structural racism to the training licensed health workers must complete",
 "HB 765": "which lets hospitals sell patient debt only to a government or nonprofit buyer that cancels it",
 "HB 1294": "which brings pay advance apps under Maryland's consumer lending law, requiring licenses and limiting fees and tips",
 "HB 881": "which sends more collected child support straight to families on cash assistance, rising to 100% by fiscal 2031",
 "HB 1085": "which extends a property tax exemption to housing built by the nonprofit arms of every housing authority in the state",
 "HB 731": "which creates a state coalition to build wildlife crossings and cut collisions between animals and vehicles",
 "HB 1111": "which opens a state solar incentive to panels built over retention ponds and old quarries",
 "HB 1315": "which locks pharmacist vaccine rules and insurance coverage to the federal recommendations in force at the end of 2024",
 "HB 102": "which delays the start of Maryland's paid family and medical leave program, with contributions beginning January 1, 2027",
 "SB 848": "which created a state grant program to help people get abortion care, funded from leftover insurer abortion accounts",
 "SB 432": "the Expungement Reform Act of 2025, which starts the waiting period to erase an old record when the full sentence ends and adds qualifying offenses",
 "HB 161": "which lets the state force local school curriculum into line with new statewide content standards",
 "HB 983": "which requires election help in another language, including access to a translator, in counties with a real need",
 "HB 1378": "which cut how much money child sexual abuse victims can win from the state, local governments, and school boards in reopened cases",
 "SB 856": "the Maryland Tenant Mold Protection Act, which puts mold duties on landlords and creates a state mold information website",
 "HB 15": "which creates a legal form for worker cooperatives, businesses owned and controlled by the people who work there",
 "HB 424": "which gives the state Prescription Drug Affordability Board more power to cap what Marylanders pay for high-priced drugs",
 "SB 901": "which makes the companies behind packaging and paper products pay for and run the recycling of what they sell",
 "SB 425": "which raises the fees coal ash producers pay and tightens the rules on storing it",
 "SB 154": "which keeps $14 million a year flowing to free lawyers for tenants facing eviction through fiscal 2028",
 "HB 431": "which voids consumer contract clauses that shorten the time a person has to sue",
 "HB 974": "which locks in no-cost coverage of preventive care as the federal rules stood at the end of 2024",
 "HB 634": "which gives recently released prisoners a way to pay off or clear old state tax debt from years they were incarcerated",
 "HB 502": "which makes the state a model employer of people with disabilities through a new office and hiring initiative",
 "HB 1020": "the Fair Medical Debt Reporting Act, which keeps medical debt off credit reports and out of loan decisions",
 "HB 1424": "the Protect Our Federal Workers Act, which opens state emergency loans and aid to Marylanders who lost federal jobs",
 "SB 250": "which raises environmental fees and penalties and tightens the rules on dams",
 "HB 1222": "the Maryland Values Act, which keeps federal immigration agents out of the non-public parts of schools, libraries, courthouses, and public clinics",
 "SB 767": "which gives Calvert County deputy sheriffs and correctional deputies the right to unionize and bargain over pay and benefits",
 "SB 93": "which makes local election boards remind voters that they can request a mail-in ballot",
 "SB 842": "which lets the state seize illegally sold vapes without a warrant",
 "HB 861": "which makes ride-hailing companies such as Uber and Lyft show drivers a weekly summary of fares collected and the driver's share",
 "HB 1046": "which stops vehicle repair contracts from excluding defects the manufacturer already knew about",
 "SB 666": "which guarantees $250,000 a year in operating grants for local anti-poverty community action agencies through fiscal 2030",
 "HB 1473": "which widens state agencies' duty to serve people with limited English or a disability, with more translated forms and notices",
 "HB 444": "which bans state and local 287(g) agreements that let local officers enforce federal civil immigration law",
 "HB 220": "which caps what landlords with water submeters can charge tenants at what the water provider actually charged",
 "HB 372": "which writes federal emergency care rules for pregnancy into state law, including ending a pregnancy when needed to stabilize the patient",
 "HB 263": "which makes local buses stop at the door of early voting centers within half a mile of their route",
 "HB 85": "which creates a legal path to permanently affordable co-op housing with capped resale prices",
 "HB 557": "which lets people check in advance whether their criminal record disqualifies them from an occupational license, for up to $100",
 "HB 200": "which requires home sellers to give buyers flood-risk information before signing a contract, starting July 2027",
 "HB 252": "which lets the state require lead paint removal contractors to carry a bond or liability insurance",
 "HB 280": "which writes federal mental health parity rules into state law so insurers treat mental health care no worse than physical care",
 "HB 480": "which requires ride-hailing companies to keep a written deactivation policy with an appeal process for drivers they cut off",
 "HB 1490": "which stops cash assistance being cut off when a parent has good cause not to cooperate with child support enforcement",
 "HB 115": "which requires prisons to send monthly release lists to election officials so eligible people get their voter registration restored",
 "HB 250": "which lets the environment department fine violators of water use, reservoir, and dam safety rules",
 "HB 254": "the Supporting Inclusive Community Adaptation Act, which creates a state climate resilience grant fund and brings communities into project planning",
 "HB 1530": "which cuts the Maryland tax filing history undocumented students need for in-state tuition from three years to two",
 "HB 1148": "which helps heirs keep an inherited home out of tax sale through a new Legacy Protection Program",
 "HB 1249": "which stops certified recovery homes from turning away people on addiction treatment medication such as buprenorphine or methadone",
 "HB 637": "which gives Maryland its own vaccine and screening recommendations, issued by the state health secretary rather than federal advisers",
 "HB 405": "which stops condo and homeowners association rules from blocking electric vehicle chargers in shared parking spaces",
 "HB 734": "which keeps the farmland property tax break for community solar projects approved by the end of 2030",
 "HB 711": "the Data Privacy Act, which bars companies from selling personal data to government bodies engaged in civil immigration enforcement",
 "HB 1578": "which extends Maryland's minority business contracting program to July 2031",
 "SB 831": "which strengthens labor protections, including a ban on employer-run employee organizations outside federal labor law",
 "SB 656": "which lets people harmed by banned cosmetic ingredients sue and creates a restitution fund for victims of harmful hair chemicals",
 "SB 475": "the PACE Act, which bars prosecutors from using a defendant's song lyrics or other creative work as evidence unless strict tests are met",
 "SB 417": "the Maryland Worker Freedom Act, which lets workers skip employer meetings about politics or religion without punishment",
 "SB 136": "which gives police officers of the Alcohol, Tobacco, and Cannabis Commission collective bargaining rights",
 "SB 334": "which bans selling pistols that a small add-on part can quickly turn into machine guns, starting January 2027",
 "HB 284": "which requires gun dealers to report a break-in or theft of guns to the State Police within 24 hours",
 "HB 578": "which tightens endangered species protections, including state-designated essential habitats",
 "HB 1135": "which lets pharmacists order a vaccine for anyone three or older so someone else can give it",
 "HB 994": "which requires travel sellers to carry at least $1 million in liability insurance and file proof yearly",
 "SB 305": "which extends $1 million a year through fiscal 2029 for job training in auto repair for formerly incarcerated people",
 "HB 351": "the No Kings Act, which lets people sue federal officers in state court for violating their rights",
 "SB 523": "which makes the state map and protect vernal pools, seasonal wetlands where amphibians breed",
 "HB 497": "which extends a temporary protective order in abuse cases to 14 days from issuance, up from 7 days from service",
 "SB 792": "which makes every hospital adopt a policy on what it does during an immigration enforcement action on site",
 "HB 1016": "which voids noncompete clauses binding architects at large firms that move out of Maryland",
 "SB 791": "the Community Trust Act, which requires a judicial warrant before local jails hold someone for federal immigration enforcement",
 "HB 895": "which bans grocery stores and delivery services from using a shopper's personal data to charge them a higher price on food",
 "HB 624": "the Safe Staffing Act of 2026, which gives hospital staff seats on committees that set staffing levels",
 "HB 315": "which bars landlords from rejecting housing voucher holders over their income or credit history",
 "SB 187": "which reclassifies the women's prerelease unit as a prerelease facility that prepares incarcerated women for release",
 "SB 937": "the Maryland Fair Chance Housing Act, which limits when landlords with five or more units may screen applicants' criminal records",
 "HB 1076": "which makes community colleges offer over-the-counter birth control on campus and public colleges report yearly on access to it",
 "SB 1": "which bars police from covering their faces on duty except undercover and requires them to wear identification",
 "SB 12": "which requires landlords of buildings with 10 or more units to provide air conditioning from June 1 through September 30",
 "SB 729": "which extends free eviction lawyers to mobile home park residents",
 "SB 810": "the Maryland Values Act of 2026, which widens the places immigration agents may not freely enter and bars schools from aiding enforcement",
 "HB 571": "which extends the housing authority tax exemption to subsidiaries of nonprofit housing corporations",
 "HB 1017": "which bans privately run jails, prisons, and immigration detention facilities in Maryland",
 "HB 963": "which lets non-citizens be appointed to settle a relative's estate",
 "SB 775": "which requires guns handed in at buyback programs to be destroyed",
 "HB 573": "which lets housing discrimination be proven by a practice's effect on a protected group, not just intent",
 "HB 894": "which stops local governments from requiring off-street parking for housing built within a quarter mile of a rail station",
 "SB 249": "which requires a separate state license to make, distribute, or sell vapes",
 "SB 322": "which restores jury eligibility once a person finishes a prison sentence, parole, or probation",
 "SB 141": "which makes it a crime to knowingly spread an election deepfake carrying false information to sway or block votes",
 "HB 191": "which makes shops accept cash for everyday essentials such as food, medicine, and fuel on in-person sales under $300",
 "SB 872": "which widens which rental units fall under the lead paint law for housing built before 1978",
 "HB 103": "which bars consumer contracts from waiving or limiting the remedies state and federal law give consumers",
 "SB 94": "which bans tips on pay advances and consumer loans and brings pay advance providers under consumer protection law",
 "HB 168": "which opens state housing funds to housing built for teachers and lets school land be used for it",
 "SB 949": "which writes absentee ballot deadlines into state law, including rules when federal law sets a different deadline",
 "HB 862": "which sets a minimum crew of two on freight trains sharing a corridor with passenger trains, with fines up to $25,000",
 "SB 599": "which restores $5 million a year for behavioral health crisis response grants for fiscal years 2027 through 2029",
 "HB 452": "which extends state dark-sky lighting rules to state parks and trails",
 "HB 1310": "which widens the program that redistributes donated prescription drugs, adding over-the-counter drugs and out-of-state donors",
 "SB 608": "which eases the paperwork crime victims need for a U visa, letting a lawyer request the certification form",
 "HB 795": "which makes public employers count hours in the way that helps workers qualify for federal Public Service Loan Forgiveness",
 "SB 439": "which protects firefighters and medics from discipline for holding a medical cannabis certification or testing positive while holding one",
 "HB 969": "which requires public EV chargers to bill by the kilowatt-hour with any service fee itemized on the receipt",
 "SB 237": "which binds Maryland's presidential electors to vote for the candidate who nominated them",
 "HB 548": "the Maryland Housing Certainty Act, which judges housing applications only by the rules in force when filed and vests approvals for five years",
 "SB 255": "the Voting Rights Act of 2026, which lets voters challenge local election systems that weaken minority groups' ability to elect their candidates",
}
