OPEN = {
 1587268: ("Voted to accept the Senate's version of LD 598", "Voted against accepting the Senate's version of LD 598"),
 1587988: ("Voted to accept the committee's ought-to-pass report on LD 1016", "Voted against accepting the committee's ought-to-pass report on LD 1016"),
 1588941: ("Voted to accept the House's final version of LD 1016", "Voted against accepting the House's final version of LD 1016"),
 1594835: ("Voted yes to accept the Senate's version of LD 1126", "Voted no on accepting the Senate's version of LD 1126"),
}
CLOSE = {
 1594835: "The Maine House agreed 73-67, and it became law without the governor's signature in January 2026.",
}
EFFECTS = {
 "LD 1185": "which bars anyone under 18 from marrying",
 "LD 585": "which widens what Efficiency Maine may spend its power-grid money on beyond heat pumps",
 "LD 163": "which makes health insurance cover over-the-counter birth control with no copay",
 "LD 54": "which makes employers with 10 or more workers list the pay range in every job posting",
 "LD 1080": "which bars utilities from demanding a deposit based on how much a new customer earns",
 "LD 538": "which lets pharmacies print a facility name instead of the prescriber on abortion pill labels",
 "LD 21": "which reframes school threat assessment policies around students who may pose a threat of violence",
 "LD 784": "which limits insurance denials for first responders' medical screening tests",
 "LD 61": "which makes employers tell workers before watching them with electronic monitoring",
 "LD 493": "which adds forever chemicals to recommended well water tests and requires landlords to test",
 "LD 1366": "which ends the sentencing split between crack and powder cocaine",
 "LD 589": "which makes farm workers subject to the state minimum wage",
 "LD 1768": "which lets the state housing fund be spent on keeping mobile home parks affordable",
 "LD 1900": "which lets four tribes form power districts on their land with the same rights as towns",
 "LD 1117": "which lets preapprenticeship grants pay for child care, transportation, tools and stipends",
 "LD 1078": "which lets needle exchange programs run mobile sites and deliver syringes",
 "LD 1145": "which gives mobile home park residents a real chance to buy the park before it is sold",
 "LD 598": "which makes employers with 10 or more workers pay two hours' wages for a cancelled shift",
 "LD 537": "which lets a family sue someone who shares a child's private information",
 "LD 1016": "which charges buyers of a mobile home park $10,000 per lot for a new state fund",
 "LD 215": "which caps general assistance for people living in large recovery homes",
 "LD 913": "which makes ticket sellers show the full price up front and bans ticket bots",
 "LD 1934": "which requires shielded, down-pointing outdoor lighting on new public installations from October 2026",
 "LD 1723": "which requires 90 days' written notice before raising lot rent in manufactured housing communities",
 "LD 911": "which keeps ranked-choice elections ranked when a candidate drops out fewer than 70 days before",
 "LD 1784": "which makes every police agency publish its rules in plain language on a public website",
 "LD 613": "which shortens the waiting period in Maine's Death with Dignity law",
 "LD 1868": "a clean electricity bill making sellers buy a rising share of clean power, 10 percent by 2040",
 "LD 670": "which adds coercion to what counts as abuse for domestic abuse protection orders",
 "LD 427": "which caps town parking rules at one off-street space per home in growth areas",
 "LD 1871": "which lets victims of sex trafficking ask a court to seal convictions caused by the trafficking",
 "LD 1937": "which makes hospitals give free care to patients with family income at or below twice the poverty level",
 "LD 93": "which opens the state's bulk vaccine purchase program to every Maine resident, adults included",
 "LD 1849": "which bars charging a child under 11 with a juvenile crime except for murder or manslaughter",
 "LD 1971": "which bars local police and jails from spending money or time helping enforce federal civil immigration law",
 "LD 556": "which bars towns from stopping a person picking any safe heating or energy system on the market",
 "LD 1126": "a gun serial-number bill barring guns with no serial number and requiring background checks for frames",
 "LD 166": "which bars pharmacies from holding a license to sell tobacco",
 "LD 2037": "which sets a new schedule for cutting carbon dioxide limits on power plants",
 "LD 1587": "which lets the Bureau of Labor Standards open investigations and issue subpoenas on its own",
 "LD 517": "which requires a warning on political ads that use fake audio, video or images of a candidate",
 "LD 1949": "which makes utility regulators weigh the effect on household bills when carrying out their duties",
 "LD 2114": "which lets public preschool take 3-year-olds, not just 4-year-olds",
 "LD 1730": "which lets residents plug small solar panels into an ordinary outlet to offset home electricity use",
 "LD 2107": "which sets up security grants for nonprofits to protect against hate crimes and terror attacks",
 "LD 2057": "which lets the state housing authority make construction loans for low-income housing on its own",
 "LD 2051": "which pays for food help for some lawfully present immigrants who cannot get SNAP",
 "LD 2058": "which frees jails from holding people solely for civil violations of federal immigration law",
 "LD 2146": "which makes the state vaccine board also weigh national doctors' groups when picking vaccines",
 "LD 1966": "which makes electric bills show more charges and changes how small solar is billed",
 "LD 2176": "which bars landlords from handing out tenants' private information to pressure them into moving",
 "LD 2231": "which limits mobile home park lot rent increases to once a year and lets residents force mediation",
 "LD 2106": "which bars staff at schools, clinics and libraries from voluntarily letting immigration agents into private areas",
 "LD 785": "which lets the Mi'kmaq Nation elect a representative to the Maine House from 2026",
 "LD 1519": "which makes e-cigarette brand owners pay for programs that collect and dispose of used devices",
}
