EFFECTS = {
 "HB 4052": "a bill to bar legislators and their staff from signing nondisclosure agreements about official work",
 "HB 4170": "a bill to cut the state income tax rate from 4.25% to 4.05% and make future automatic cuts permanent",
 "HB 4159": "a bill to base early grade reading standards on the science of reading",
 "HB 4027": "the zoning half of a plan to repeal the 2023 state siting law for large wind and solar projects",
 "HB 4028": "a bill to repeal the 2023 law letting the state override local zoning for large wind and solar projects",
 "HB 4242": "a bill to make health professionals keep patient records physically in the United States or Canada",
 "HB 4283": "a bill to let a utility running pre-2024 gas engines in the Upper Peninsula skip clean energy filings",
 "HB 4222": "a bill to make every school have a crisis team and review emergency plans every three years",
 "HB 4315": "a bill to make the State Police build and hand out school safety training each year",
 "HB 4340": "a bill to bar people who are not citizens or qualified immigrants from most public assistance",
 "HB 4341": "a bill to bar people who are not citizens or qualified immigrants from state housing programs",
 "HB 4338": "a bill to void city and township rules that limit cooperation with federal immigration officials",
 "HB 4342": "a bill to withhold revenue sharing from local governments that limit immigration cooperation",
 "HB 4339": "a bill to void county rules that limit cooperation with federal immigration officials",
 "HB 4066": "a bill to make schools label sports teams by sex as listed on the original birth certificate",
 "HB 4469": "a bill to let schools decide who plays school sports by biological sex at birth",
 "HB 4356": "a bill to mail notices to voters who have not voted in 8 years and make them confirm their address",
 "HB 4369": "a bill to bar schools from serving food with certain dyes and additives from July 2028",
 "HB 4024": "the student restroom privacy act, a bill to require school restrooms to be used by sex at birth",
 "HB 4664": "a bill to make blocking traffic during a highway protest a crime carrying up to 93 days in jail",
 "HB 4515": "a bill to put the recipient's photo and signature on the Bridge card for food and cash aid",
 "HB 4746": "which makes the state give every food or cash aid recipient a chip-enabled Bridge Card within a year",
 "HB 4602": "a bill to let local election boards build their own test ballots from any source",
 "HB 4160": "a bill to bar state rules stricter than federal standards without a finding of clear need",
 "HB 4951": "which sets a new 24 percent wholesale tax on marijuana to pay for road work",
 "HB 4747": "a bill to let taxpayers deduct contributions to other states' college and disability savings plans",
 "HB 4915": "a bill to bar requiring implicit bias training for health professional licenses",
 "HB 4933": "a bill to repeal state licensing of fee-charging personnel agencies",
 "HB 4486": "a bill to bar local governments from banning natural gas or propane",
 "HB 4492": "a bill to let employers require tipped workers to share tips",
 "HB 4445": "a bill to let hunters bait deer anywhere in Michigan during open deer seasons",
 "HB 5037": "a bill to set a 15-year time limit for charging the new fertility fraud crime",
 "HB 5035": "a bill to let people harmed by fertility fraud sue for three times their damages",
 "HB 5036": "a bill to make fertility fraud a felony carrying up to 5 years in prison",
 "HB 5298": "a bill to make a passenger's own auto insurance pay first for injuries in limousines and charter buses",
 "HB 4949": "a bill to widen the shield protecting sport shooting ranges from noise lawsuits",
 "HB 4582": "a bill to restore the rule that property owners owe no duty to warn visitors of open and obvious dangers",
 "HB 5652": "a bill to bar neighbors within 5 miles of an existing motor racing track from suing it",
 "HB 4765": "a bill to make the state check every voter registrant's citizenship against databases",
 "HB 4720": "a bill to bar voting systems with parts from companies on the federal security threat list",
 "HB 5710": "the utility-rules half of a plan to repeal Michigan's clean energy standards",
 "HB 5711": "a bill to repeal Michigan's clean energy standards, including 100% clean energy by 2040",
 "HB 5744": "a bill to make shooting at an occupied vehicle a felony carrying up to 10 years",
 "HB 5505": "a bill to create a digital oversight office in the Legislature",
 "HB 5504": "a bill to create a State Digital Service Office to review big state software projects",
 "HB 5520": "a bill to bring back holding third graders back for reading from the 2027-2028 school year",
 "HB 6013": "a bill to suspend Bridge cards used outside Michigan for more than 90 days in a row",
 "HB 5812": "a bill to bar the state from waiving food assistance work requirements without legislative approval",
 "HB 4467": "a bill to bar puberty blockers, cross-sex hormones and gender surgery for minors",
 "HB 4466": "a bill to let the state discipline health professionals who break the proposed minor gender care ban",
 "HB 5536": "a bill to narrow state wetland protection to wetlands connected to federally protected waters",
 "HB 5574": "a bill to make it a crime to ignore a first responder's warning and come within 25 feet to interfere",
 "HB 5820": "a bill to move up the deadline for teacher training courses to add dyslexia instruction",
 "HB 5934": "a bill to refund building permit fees when the state misses its decision deadline",
 "HB 5935": "a bill to make the state cite the rule behind any building permit denial",
 "HB 5819": "a bill to move up the required start of standards-based reading materials to July 2026",
 "HB 5933": "a bill to change how the state handles building and trade permit applications",
 "HB 5069": "a bill to ban food containing certain dyes and additives from 2029",
 "HB 6038": "a bill to limit when the state can ask for changes to a wetland permit application",
 "HB 5845": "a bill to keep electronic poll book data for 22 months after an election",
 "HB 5081": "a bill to make every school district employ a dyslexia teacher by 2027",
 "HB 5145": "a bill to bar accepting an applicant's own statement as proof of identity or income for public assistance",
 "HB 5936": "a bill to make the state refund the full fee when it misses an environmental permit deadline",
 "HB 5502": "a bill to exempt wetlands created by accident from state regulation",
 "HB 5938": "a bill to require wetland permit hearings within 30 days of a complete application",
 "HB 5707": "a bill to let landowners dig a pond under 1 acre for home use without a state permit",
 "HB 5974": "a bill to give parents the right to see a minor's medical records",
 "HB 5937": "a bill to cut the time the state has to say whether a permit application is complete from 30 days to 7",
 "HB 5082": "a bill to make the state assess whether land is a wetland within 60 days, for free",
 "SB 294": "which lets agencies require a care deposit from the owner of an animal seized in a torture case",
 "SB 723": "which widens the transformational brownfield program, allowing another $80 million a year of tax capture",
 "HB 4350": "which lets people put out small amounts of feed for wild birds near home despite deer feeding bans",
 "SB 293": "which lets agencies require a care deposit from the owner of an animal seized in a cruelty case",
 "SB 111": "a bill to create a personal protection order for older and vulnerable adults",
 "SB 31": "a bill to make hospitals let a birthing patient have a partner and a doula present from 2027",
 "SB 29": "a bill to make the state health disparities plan address biased care for pregnant patients",
 "SB 30": "the biased and unjust care reporting act, a bill to collect reports of biased care from pregnant patients",
 "SB 34": "a bill to add lactating status to Michigan's civil rights law",
 "SB 37": "a bill to make insurers cover pregnancy care given at home by in-network providers",
 "SB 33": "a bill to let an advance directive say which treatment a person wants if pregnant",
 "SB 3": "a bill to create a state prescription drug affordability board that can cap drug prices",
 "SB 234": "a bill to make every school adopt a policy limiting student cellphone use during school hours",
 "SB 257": "a bill to give survivors of criminal sexual conduct more time to sue",
 "SB 260": "a bill to end governmental immunity for schools sued over sexual abuse they negligently allowed",
 "SB 78": "a bill to let people convicted of felonies before age 18 ask a court to set them aside after 15 years",
 "SB 134": "a bill to widen Michigan's consumer protection law and raise fines to $25,000 per person misled",
 "SB 154": "a bill to make it a crime to use force or threats to interfere with reproductive health care",
 "SB 225": "a bill to bar concealed pistols in the State Capitol and legislative office buildings",
 "SB 331": "a bill to bar guns without serial numbers and unlicensed 3D-printed guns",
 "SB 226": "a bill to bar all guns in the State Capitol and legislative office buildings",
 "SB 224": "a bill to ban bump stocks and multiburst trigger activators",
 "SB 319": "a bill to make minimum staffing a required bargaining topic for police and firefighters",
 "SB 46": "a bill to let the state investigate unsafe water complaints in mobile home parks with their own pipes",
 "SB 360": "a bill to require reasonable security safeguards for personal information held by businesses and agencies",
 "SB 247": "a bill to charge hazardous waste disposal wells a per-gallon fee for host community grants",
 "SB 246": "a bill to pause new hazardous waste disposal licenses for 5 years",
 "SB 533": "a bill to fine people up to $1,000 for lying about election rules to stop someone voting",
 "SB 576": "a bill to create a revolving fund for energy-saving projects in state facilities",
 "SB 579": "which pushes back to October 2029 the end dates for a set of state environmental fees",
 "HB 4183": "which raises the state motor fuel tax from 31 cents a gallon to at least 51 cents from 2026 for roads",
 "SB 577": "which extends the fees that pay to train and certify public water supply operators to 2029",
 "SB 578": "which creates the Neighborhood Roads Fund and the Infrastructure Projects Authority Fund",
 "SB 515": "a bill to make landlords install a carbon monoxide detector in rentals with fuel-burning appliances",
 "HB 5055": "which lets legislative sergeants at arms with police commissions enforce state law to guard lawmakers",
 "SB 462": "a bill to require a state license to sell tobacco and vaping products at retail",
 "SB 232": "a bill to let the state lower the Michigan Reconnect grant age from 25 to as low as 21",
 "SB 451": "a bill to bar medical debt from credit reports",
 "SB 296": "a bill to bar hospitals from requiring nurses to work beyond scheduled hours from June 2027",
 "SB 145": "a bill to bar employers from asking job applicants about past pay or credit history",
 "SB 760": "a bill to bar AI chatbots from acting as friends or partners for minors",
 "SB 758": "a bill to make online services set minors' accounts to the most private settings by default",
 "SB 757": "a bill to bar social media apps from showing minors algorithm-chosen feeds without parental consent",
 "SB 311": "a bill to raise child care subsidy payments to providers each year with inflation from 2027",
 "SB 310": "a bill to write the Tri-Share child care program into law",
 "SB 807": "a bill to create a state-run retirement savings program for workers without an employer plan",
 "SB 961": "the State Voting Rights Act, a bill to bar election rules that hold back a protected class of voters",
 "SB 963": "the Language Assistance for Elections Act, a bill to require election help in other languages where needed",
 "SB 962": "a bill to create a Michigan voting and elections database and institute with public universities",
 "SB 964": "a bill to make local governments report election changes to the Secretary of State from 2028",
 "SB 977": "a bill to seek a federal waiver for a reinsurance program that lowers individual market premiums",
 "SB 967": "a bill to let developers claim a new state low-income housing tax credit from 2027",
 "SB 973": "a bill to create a Michigan-run health insurance exchange by 2028",
 "SB 49": "a bill to raise Michigan's workplace safety fines to match federal fines",
 "SB 1041": "a bill to bar hotels from raising prices more than 20% during a declared emergency",
 "SB 1043": "a bill to bar fuel sellers from raising prices more than 20% during a market disruption",
 "SB 1042": "a bill to bar sellers from raising prices on food and supplies more than 20% during an emergency",
 "SB 947": "a bill to overhaul Michigan's dam safety law with registration and safety plans for every dam",
 "HB 5807": "which lets qualifying out-of-state insurers use the new housing tax credit against the retaliatory tax",
 "HB 4187": "which cuts the income tax money set aside for the Renew Michigan cleanup fund for three years",
 "HB 4064": "which bars a sitting state lawmaker from taking pay to lobby government officials",
 "SB 373": "a bill to bar leases that charge an extra fee on every allowed way of paying rent",
 "HB 5806": "which creates a state housing opportunity tax credit for low-income housing projects from 2027",
 "HB 6043": "which writes the Tri-Share child care program into law",
 "SB 81": "which extends the Indigent Defense Commission's work to young people in juvenile courts",
 "SB 903": "which sets conditions school districts must meet to keep extra funding for students who need more help",
 "SB 966": "which tells the state housing authority to run a housing opportunity tax credit program from 2027",
}
