EFFECTS = {
 "HB 544": "a bill to let a federally approved pesticide label satisfy any state cancer warning requirement",
 "HB 68": "a bill to cut the deadline for most personal injury lawsuits from five years to two",
 "HB 742": "a bill to bar state departments from spending on diversity, equity and inclusion programs",
 "HB 875": "a bill to stop public colleges denying recognition or funding to student groups over their beliefs",
 "HB 269": "a bill to create three tax credits for child care donors, employers and providers",
 "HB 495": "which put the St. Louis police department back under a state-appointed board",
 "SB 4": "which let electric utilities charge customers for new gas power plants while still building them",
 "HB 567": "which repealed the voter-approved paid sick time law and froze the minimum wage after 2026",
 "HB 1175": "a bill to bring back the Second Amendment Preservation Act declaring some federal gun laws invalid",
 "HB 195": "a bill to give a child born alive during an abortion the same rights as any newborn",
 "HB 437": "a bill to rewrite the rules for settlement demands in injury and wrongful death claims",
 "HB 794": "a bill to bar foreign money in ballot measure campaigns and add party challengers at ballot counting",
 "HB 493": "a bill to exempt certain used personal property from state sales tax",
 "HB 344": "a bill to give the state sole control over tobacco and vaping sales rules",
 "HB 565": "a bill to narrow when horse and livestock activity sponsors can be sued for ordinary carelessness",
 "HB 126": "a bill to end no-excuse absentee voting",
 "HJR 73": "a proposed constitutional amendment repealing the 2024 reproductive-freedom right and restricting abortion",
 "HB 1264": "a bill to treat a building permit as approved if a city or county does not answer within thirty days",
 "HB 918": "a bill to make injured people prove the defendant made the exact product involved",
 "SB 71": "which made breaking into a vehicle or restricted business area second degree burglary",
 "HB 595": "which stopped cities and counties from passing several kinds of renter protection",
 "HB 594": "which let individuals deduct 100 percent of capital gains from state income tax from 2025",
 "HB 145": "which closed several kinds of government records, including minors' details and utility billing",
 "SB 152": "which barred foreign nationals from funding or steering ballot measure campaigns",
 "HJR 3": "a proposed constitutional amendment requiring a majority in every congressional district to pass initiatives",
 "HB 1": "which redrew Missouri's eight congressional districts in the middle of the decade",
}
