OPEN = {
 1508577: ("Voted for House Bill 801", "Voted against House Bill 801"),
 1554386: ("Voted for House Bill 801", "Voted against House Bill 801"),
 1561886: ("Voted for House Bill 231", "Voted against House Bill 231"),
 1562488: ("Voted for House Bill 231", "Voted against House Bill 231"),
 1562501: ("Voted for Senate Bill 542", "Voted against Senate Bill 542"),
}
EFFECTS = {
 "HB 39": "which lets political parties give money to candidates for judge",
 "HB 74": "which makes private fish pond owners hold a license and raises the application fee from $10 to $600",
 "HB 121": "which makes public buildings, schools, prisons and shelters set restrooms and changing rooms aside by sex",
 "HB 179": "which says signing a petition does not move a voter off the inactive voter list",
 "HB 184": "which replaces the phrase hearing impaired with deaf or hard of hearing throughout state law and widens two rights",
 "HB 300": "which bars schools from letting males take part in sports programs set aside for females",
 "HB 215": "which ends the duty to seek gender balance and minority representation on state boards",
 "HB 245": "which keeps Montana's Medicaid expansion going with no expiry date and changes its job help",
 "HB 214": "which lets Montana charge people held for federal immigration reasons with state crimes",
 "HB 278": "which lets an officer check a person's immigration status during a lawful traffic stop",
 "HB 342": "which says a foreseeable risk does not raise the standard of care in a medical malpractice case",
 "HB 291": "which bars the state from setting air pollution limits tighter than the federal Clean Air Act",
 "HB 365": "which stops a court weighing how the legislature behaved when awarding legal costs against the state",
 "HB 400": "the Free to Speak Act, which bars punishing students or staff who refuse to use a name or pronoun not matching a person's sex",
 "HB 388": "which bars government from making pregnancy centers offer abortion, abortion drugs or birth control",
 "HB 393": "which makes towns of more than 300 people record public meetings and post the audio online",
 "HB 467": "which adds saliva swab testing to Montana's drunk and drugged driving rules",
 "HB 416": "which makes a homeowners' association get the owner's permission before entering a member's land",
 "HB 413": "which says moving to Montana for temporary work, training or school does not make a person a resident for voting",
 "HB 575": "which lets a court give a parent a public defender in a case to end their parental rights",
 "HB 443": "which scraps the state-set county license for door-to-door and pop-up sellers",
 "HB 396": "which bars bail for people brought back on an out-of-state warrant until they see the issuing judge",
 "HB 687": "which extends the 80-hour monthly work rule for expanded Medicaid to adults up to age 62",
 "HB 509": "which widens state student loan help to every newly hired public school teacher",
 "HB 471": "which requires written parental permission before a child attends lessons on sexual orientation or gender identity",
 "HB 625": "which docks a county's state money if its county attorney does not report child abuse cases on time",
 "HB 685": "which drops the cost-benefit test for permission to pollute Montana water that is cleaner than the law requires",
 "HB 531": "which bars courts from reviewing the rules the legislature writes for its own proceedings",
 "HB 819": "which limits flags on public property to a set list, such as the United States, Montana, state and tribal flags",
 "HB 587": "which raises the bar for proving a coal mine has harmed water, requiring a blocked water use",
 "HB 801": "the Montana Firearms Liability Clarification Act, which limits lawsuits over how guns and ammunition are sold and advertised",
 "HB 719": "which makes voters give a date of birth when registering and on mail ballot envelopes",
 "HB 711": "which limits who the Supreme Court may pick to chair the redistricting commission",
 "HB 664": "which repeals Montana's numeric limits on nitrogen and phosphorus in water",
 "HB 521": "which bars someone convicted of a crime from suing over injuries they got committing it",
 "HB 599": "which makes schools get a parent's permission before collecting data that names a child",
 "HB 638": "which bars state and local agencies from asking for a diversity statement",
 "HB 770": "which makes candidates file campaign finance reports even when they raised and spent nothing",
 "HB 690": "which says raising a child in line with the child's biological sex is not abuse or neglect",
 "HB 655": "which protects adoption and foster care providers that act on religious belief from state action",
 "HB 694": "which discourages placing a Montana foster child with a family abroad",
 "HB 809": "which bars city and county governments from adopting or enforcing red flag gun orders",
 "HB 476": "which funds grants for newborn safety devices where a parent may legally leave a baby",
 "HB 197": "which lets a workers' compensation insurer stop disability pay sooner once a doctor clears the worker for full duty",
 "SB 113": "which stops tow firms holding an insured owner's belongings once a towing claim is filed",
 "SB 172": "which lets resort towns spend their extra resort tax on housing for local workers",
 "SB 170": "which makes the community health aide program permanent",
 "HB 20": "which makes local property tax ballot questions name a fixed dollar amount, not mills",
 "HB 411": "which exempts farm and forest land from open space levies",
 "SB 249": "which lets carers give evidence in every child abuse and neglect case",
 "HB 808": "which creates the Montana Brownfields Revitalization Act and a fund to clean up contaminated land",
 "SB 143": "which cuts the deadline for suing on a written contract from 8 years to 6",
 "SB 105": "which extends the ban on campaigning within 100 feet to anywhere ballots are available, for all open hours",
 "HB 201": "which makes paid petition signature gatherers say they are paid and wear a badge",
 "HB 337": "which cuts the top state income tax rate from 5.9% to 5.65% in 2026 and 5.4% in 2027",
 "HB 168": "which lets state school money follow preschool children with disabilities from age 3",
 "HB 499": "which sends grow-your-own teacher training grants to colleges that partner with school districts",
 "HB 869": "which makes schools prepare for a young athlete's cardiac arrest, with coach training and guidance",
 "HB 931": "which lets state trust land be leased for single-family or apartment housing",
 "HB 891": "which lets the state health department's inspector general demand records without a judge",
 "HB 953": "which lets Montana Medicaid cover direct primary care, where a set fee replaces per-visit pay",
 "SB 181": "which strengthens Indian Education for All, requiring tribal consultation and yearly reporting",
 "SB 149": "which makes it harder to prove the need for an emotional support animal to a landlord",
 "SB 221": "which lets agencies assess greenhouse gases in environmental reviews again",
 "SB 154": "which bans selling human bodies and widens the ban on selling body parts",
 "SB 440": "which adds a public ballot-count reconciliation report to every county's election",
 "SB 48": "which lets a person speak publicly about a complaint they filed against a judge",
 "SB 30": "which stops a conflicted judge staying on a case when other judges are available",
 "HB 259": "which makes the wildlife commission set looser wolf harvest rules where wolves are most numerous",
 "SB 457": "which lets the legislature hold someone in contempt for ignoring a subpoena",
 "SB 214": "which tips unclear zoning arguments in favor of the landowner's existing use",
 "SB 511": "which regulates outside lawsuit funders and bars money from hostile foreign governments",
 "SB 38": "which stops someone recovering legal costs after forcing a veto-override poll that fails",
 "SB 492": "which narrows what elected state officials must disclose about their business interests",
 "SB 390": "which brings vaping under Montana's indoor smoking ban",
 "SB 508": "which sets a zero tolerance rule for THC in drivers under 21",
 "SB 41": "which makes replacement judges be picked at random when a judge leaves a case",
 "SB 193": "which gives the chief justice alone the power to appoint the board that examines bar applicants",
 "SB 39": "which sets rules for what a lawyer may charge the losing side, billed in tenths of an hour",
 "SB 194": "which abolishes the Board of Public Assistance and sends benefit appeals to the health department",
 "SB 213": "which lets apartment buildings of up to six stories be built with a single staircase",
 "SB 218": "which lets someone sue a clinician over gender dysphoria treatment they had as a child",
 "SB 276": "which makes voter ID cards be current and readable and lets a state university photo card count alone",
 "SB 133": "which removes the extra 5 percent local governments could add to impact fees on new building",
 "SB 97": "which moves lawsuits over new Montana laws to the sponsoring legislator's home district",
 "SB 168": "which gives governments 3 years to sue over a dock, boat house or wall on a lakeshore",
 "SB 520": "which makes state land mining leases run at least 10 years and continue while the mine is profitable",
 "SB 262": "which drops environmental review from state water and sewer approval for subdivisions",
 "SB 278": "which creates a school job guiding pupils toward college and work opportunities",
 "HB 270": "which limits a judge to sending a flawed environmental study back rather than canceling the permit",
 "HB 344": "which creates a drugged driving offense based on set blood levels of nine drugs without a prescription",
 "HB 285": "which rewrites the Montana Environmental Policy Act and repeals its broad environmental policy statement",
 "HB 311": "which makes property managers refund rental application fees when no lease results",
 "SB 117": "which lets local governments raise property tax levies by the full inflation rate, capped at 4 percent",
 "HB 427": "which makes a building department explain in writing why it held up a permit or stopped work",
 "HB 586": "which bases car seat and booster seat rules on a child's age",
 "SB 74": "which taxes marijuana on the discounted price customers actually pay",
 "HB 492": "which caps required parking at one space per home and none in the larger cities",
 "HB 650": "which lets the state borrow money to build broadband where service is poor or missing",
 "HB 207": "which makes candidates file before the primary and bars primary losers from write-in runs",
 "SB 91": "which puts an eagle mark on driver's licenses issued to United States citizens from 2026",
 "HB 723": "which makes medical facilities report yearly on infants born alive after an abortion",
 "HB 740": "which bars pharmacy benefit managers from stopping pharmacists telling patients about cheaper options",
 "HB 804": "which sets the lobbying registration threshold at $3,000 for 2025",
 "HB 791": "which narrows public nuisance law to land use and blocked roads, putting products beyond it",
 "HB 759": "which bars firms taxed as corporations from giving money to candidates",
 "HB 736": "which lets a discharge permit holder meet nutrient limits by counting verified cuts elsewhere in the drainage",
 "HB 703": "which drops greenhouse gases from appliances and out-of-state sources from state environmental reviews",
 "HB 55": "which makes power companies hold four public meetings before filing a long-range plan",
 "SB 532": "which makes counties with zoning allow a second small home on any single-family plot",
 "SB 333": "which extends the coal severance tax break for washed coal by two years",
 "SB 253": "which makes private school scholarship charities get state certification",
 "SB 560": "which makes nonprofit hospitals report from 2027 what they give back for their property tax exemption",
 "SB 534": "which frees new internet and mobile phone equipment from property tax for 5 years",
 "SB 337": "which lets a builder pause property tax while building a new subdivision",
 "HB 515": "which puts more state money into school buildings and technology",
 "SB 326": "which extends and widens Montana's film tax credits through 2045",
 "SB 553": "which stops airline travel credits expiring",
 "HB 59": "which raises the bond a licensed water well contractor must post from $4,000 to $25,000",
 "SB 535": "which creates a licensed industry of experimental treatment centers in Montana",
 "HB 446": "which creates an indecent exposure offense based on exposure to people of the opposite sex at birth",
 "HB 818": "which bars foreign nationals from giving to or spending on statewide ballot measure campaigns",
 "HB 231": "one of two 2025 property tax bills, which set the home tax rate at 0.76% of the first $400,000 of value",
 "SB 319": "which requires a state license to work as a doula from 2027",
 "HB 682": "which lets people who had gender transition treatment as children sue until age 25 or later",
 "SB 182": "which gives tribes more freedom in how the Indian language program partnerships are set up",
 "SB 110": "which sets yearly inspection rules for amusement rides that stay in one place more than 30 days",
 "SB 275": "which makes it easier to build on farmland taken into a town",
 "SB 104": "which triples how much debt the Montana Facility Finance Authority may take on in two years",
 "SB 342": "which puts the state court administrator under the chief justice alone",
 "SB 310": "which splits trail grant money by law between motorized, non-motorized and shared projects",
 "SB 495": "which abolishes the board that oversaw Montana's tobacco prevention spending",
 "HB 211": "which lets shops deliver beer and wine to your door and licenses third-party delivery firms",
 "HB 78": "which makes pet insurance sellers explain in plain terms what a policy does not cover",
 "HB 15": "which raises 21 dollar figures in Montana's school funding formula",
 "SB 95": "which sets aside $300,000 for suicide prevention aimed at veterans and serving military members",
 "SB 471": "which creates an offense of endangering people at a flashing pedestrian crossing",
 "HB 165": "which removes the notary step from signing over a vehicle title",
 "HB 254": "which drops fingerprint background checks for professional employer organizations",
 "HB 128": "which stops an employer sacking someone for volunteering as an emergency responder",
 "HB 399": "which bars insurers from requiring prior authorization for most generic pills and inhalers",
 "HB 588": "which brings motorized scooters into Montana's traffic laws",
 "HB 162": "which lets resort towns spend their extra resort tax on workforce and community housing",
 "HB 667": "which protects an employee who runs for or holds public office from being punished by their employer",
 "HB 621": "which lets local emergency services offer confidential peer support to their staff",
 "HB 764": "which lets a county commission start a public transport district by its own resolution",
 "HB 338": "which widens early screening for young children from reading alone to reading and math",
 "HB 825": "which lets a hospital patient name someone they trust to make health decisions for them",
 "HB 601": "which creates an online tool by May 2026 for helpers to track Medicaid applications",
 "HB 810": "which bars landlords from charging a tenant an extra fee based on how the rent is paid",
 "HB 358": "which raises the volunteer firefighter pension from $175 to $200 a month",
 "HB 442": "which removes two duties to report a doctor to the licensing board",
 "HB 466": "which lets state agencies exempt whole groups of actions from environmental review",
 "HB 56": "which puts a 5.75% state fee on private ground ambulance companies to raise Medicaid ambulance rates",
 "HB 573": "which replaces the transformational learning school grant program with a phase two program",
 "HB 147": "which helps a homeowner argue that a neighborhood rule was not enforced evenly and has been dropped",
 "HB 665": "which protects unpaid officers of small charities from personal liability for unpaid payroll tax",
 "HB 543": "which makes permanent the duty of health care employers to report violence against staff",
 "SB 375": "which bars shops from selling hemp products that contain THC",
 "SB 147": "which stops Montana's Indian Child Welfare Act from expiring",
 "HB 855": "which funds wildlife crossings over and under highways through a special license plate",
 "HB 888": "which bars a local health board from requiring anyone to be vaccinated",
 "HB 710": "which lets judges order companies to hand over records to child exploitation investigators",
 "HB 908": "which makes the job growth tax credit permanent and extends it to building trade apprentices",
 "HB 239": "which moves construction contractors from a simple registration to a full state license",
 "HB 372": "which raises hunting license prices and puts more of the money into bird habitat",
 "HB 421": "which raises the wildfire protection fee forest landowners pay",
 "HB 129": "which gives volunteer emergency responders an extra $3,000 state income tax deduction",
 "HB 932": "which sends marijuana tax money to a new wildlife habitat account",
 "HB 853": "which raises license fees for restaurants, food businesses, hotels and campgrounds",
 "SB 542": "Montana's 2025 property tax law, which sent homeowners a rebate of up to $400 and set a sliding home tax rate",
 "HB 669": "which clarifies how tuition is worked out for children schooled while in hospital for emotional problems",
}
