EFFECTS = {
 "H 58": "which let Scotland County commissioners set the 2025-2026 school budget without a court fight",
 "H 123": "a bill to make knowingly destroying or falsifying a patient's medical record a crime",
 "H 636": "a bill to make every school system set up a parent and staff committee to review library materials",
 "H 38": "a bill to bar credit card networks from coding stores as gun sellers or keeping gun owner lists",
 "H 261": "a bill to raise punishment for crimes committed with others to help gang activity",
 "H 606": "a bill to give people until age 28 to sue over gender transition care and bar state money for it in prisons",
 "H 519": "a bill to cut back the care a minor can agree to alone, keeping only pregnancy care",
 "H 690": "a bill to cut off state benefits, public housing and unemployment pay for people without legal status",
 "H 781": "a bill to bar cities and counties from letting people camp or sleep overnight on public land",
 "H 859": "a bill to bar cities and counties from running guaranteed income programs",
 "S 50": "the Freedom to Carry Act, a bill to let citizens 18 and older carry a hidden handgun without a permit",
 "H 568": "a labor law bill that limits when state safety inspectors testify and eases workplace notice rules",
 "S 442": "the Parents Protection Act, which bars abuse cases based on raising a child as their birth sex",
 "H 768": "which drops the firefighter radio system rule for some buildings and puts water permit reviews on a clock",
 "S 472": "a coastal bill that makes the state lose its say on water permits it misses deadlines on",
 "H 694": "a water bill that folds three river basins into the Cape Fear and Neuse basins and eases transfers",
 "H 193": "a gun bill that lets private school staff carry with permission and permit holders carry in some churches",
 "H 805": "which sets one fixed meaning of sex in state rules and bars state money for gender transition care for minors",
 "H 318": "an immigration bill that makes jails check status and hold people up to 48 hours for federal agents",
 "S 266": "an energy bill that erases the 2030 carbon cut goal and lets utilities raise rates for plants under construction",
 "H 307": "known as Iryna's Law, which ends release on a written promise and restarts executions",
 "S 249": "which redrew U.S. House Districts 1 and 3 in eastern North Carolina",
 "S 378": "a bill to drop Planned Parenthood as a Medicaid provider",
 "S 261": "a bill to drop the 2030 carbon cut goal and let utilities charge for plants under construction",
 "S 554": "a bill to bar state banks from refusing service to farmers over greenhouse gas emissions",
 "H 171": "a bill to stop state agencies and local governments running diversity, equity and inclusion programs",
 "S 153": "the North Carolina Border Protection Act, which makes state agencies do federal immigration work",
 "S 558": "which bars public colleges from keeping diversity offices or teaching what the law calls divisive concepts",
 "S 227": "which bars public schools from running diversity offices or teaching what the law calls divisive concepts",
 "S 1080": "which puts a 2026 ballot question lowering the maximum income tax rate from 7 to 3.5 percent",
 "S 1082": "a bill to ask voters to add a right to work rule to the state constitution",
 "H 1089": "which puts a 2026 ballot question ordering limits on local property tax growth",
 "H 936": "a bill to rewrite the phone sales law around robocalls and spam texts",
 "H 437": "a bill to raise penalties for selling drugs near homeless shelters and bar public camping",
 "S 1057": "a bill to make proxy advisers disclose the basis for advice against company management",
}
