CLOSE = {
 1547459: "The North Dakota House passed it 49-45, but the Governor vetoed it and the override failed, so it did not become law.",
}
EFFECTS = {
 "HB 1585": "a bill to make police report people they believed were in the country illegally to federal agents",
 "HB 1496": "a bill to set 68 degrees as the heat a landlord must keep in a rented home",
 "HB 1477": "a bill to write a right to fertility treatment into state law",
 "HB 1145": "a bill to require the Ten Commandments to be displayed in public schools and colleges",
 "HB 1478": "a bill to write a right to birth control into state law",
 "HB 1456": "a bill to let public schools bring in chaplains",
 "HB 1583": "a bill to widen the crime of running a false political ad to reckless disregard for the truth",
 "HB 1455": "a bill to make the state consult tribes about bills that affect them",
 "HB 1217": "which repeals the law making it a crime to willfully transfer a body fluid containing HIV",
 "HB 1114": "which caps what a person pays out of pocket for a 30-day insulin supply at $25",
 "HB 1475": "a bill to make school breakfast and lunch free for every student",
 "HB 1411": "a bill to ban red flag gun orders across North Dakota",
 "HB 1283": "a bill to stop the state employee health plan charging for follow-up breast scans",
 "SB 2352": "which lets a child of 18 months or younger live with their mother at the Heart River correctional center",
 "HB 1341": "which makes assaulting a hospital worker a felony",
 "HB 1058": "which sets the state's first rules for aboveground fuel tanks",
 "SB 2159": "which lifts the ban on nuclear waste research at the state energy research center",
 "SB 2307": "a bill to make libraries and schools keep sexual material away from minors",
 "HB 1318": "which limits when a pesticide maker can be sued for failing to warn about health risks",
 "SB 2339": "which bars courts from holding an electric utility strictly liable for wildfire damage",
 "HB 1600": "which sets up an immigration law clinic at the University of North Dakota school of law",
 "HB 1225": "which adds a new felony level for reckless endangerment with a firearm",
 "SB 2213": "which requires new elementary and secondary teachers to show competence in direct math instruction",
 "HB 1216": "which makes health plans count drug maker coupons toward a person's deductible and out-of-pocket maximum",
 "SB 2258": "which makes an agency cite the law behind an enforcement action within ten days when asked",
 "SB 2350": "a bill to close public employee discipline records to the public for a time",
 "SB 2355": "a bill to put intelligent design into the state's science standards",
 "HB 1178": "which requires school districts to let students old enough to vote leave campus to do so",
 "HB 1497": "which lets school districts take some younger children into four-year-old programs",
 "HB 1500": "which protects the right to rebuild a home that no longer fits current zoning",
 "SB 2069": "which makes newspapers post legal notices on the statewide legal notices website at no extra charge",
}
