CLOSE = {
 1273524: "The New Mexico House passed it 50-18. The governor then vetoed most of it, and only the rebates, the bigger child tax credit and a few other parts became law.",
}
EFFECTS = {
 "HB 42": "which makes health plans pay pharmacists the same as other providers for the same care",
 "HB 50": "which lets cities and counties use industrial revenue bonds to pay for electric transmission lines",
 "HB 83": "which builds a permanent fund for early childhood education and care from excess oil and gas taxes",
 "HB 100": "which makes the state health insurance exchange offer standardized plans shoppers can compare",
 "HB 126": "which requires health plans to cover a heart artery calcium scan for certain people",
 "SB 5": "the Extreme Risk Firearm Protection Order Act, a red flag law letting courts order a dangerous person to give up guns",
 "SB 137": "which lets the state license a person for a job or profession whatever their immigration status",
 "HB 364": "which strengthens collective bargaining for public employees",
 "SB 75": "the Wildlife Trafficking Act, which makes it a crime to buy or sell parts of animals threatened with extinction",
 "SB 131": "the Tobacco Products Act, which raises the tobacco age to 21 and requires sellers to hold a state license",
 "SB 29": "which brings back the solar tax credit, worth 10 percent of the system price up to $6,000",
 "SB 98": "which tightens wage rules on public building jobs and raises fines for underpaying",
 "SB 117": "which clarifies the property tax break for low-income people with disabilities",
 "HB 5": "which set up a Civil Rights Commission to study ending qualified immunity",
 "SB 4": "which set special rules for the 2020 general election during the pandemic, including mailed ballot applications",
 "SB 8": "which makes police wear body cameras when they deal with the public",
 "HB 4": "the New Mexico Civil Rights Act, which lets people sue public bodies for breaking state constitutional rights",
 "SB 10": "which repealed New Mexico's 1969 abortion ban",
 "HB 51": "the Environmental Database Act, which requires a public website for looking up environmental data",
 "HB 20": "the Healthy Workplaces Act, which gives workers paid sick leave of up to 64 hours a year",
 "HB 15": "which set up a new round of sustainable building tax credits for 2021",
 "HB 291": "which raises the low-income tax rebate and lifts the working families tax credit",
 "HB 76": "which lets the state deny an air permit to a company with a bad compliance record",
 "HB 266": "which adds a fifteen-week apprenticeship to the alternative special education teaching license",
 "SB 112": "which creates a task force to plan moving the economy away from oil and gas dependence",
 "SB 219": "which ends the rule that people show proof of citizenship to get certain job licenses",
 "SB 71": "the Patients' Debt Collection Protection Act, which bars hospitals from chasing patients too poor to pay",
 "SB 32": "the Wildlife Conservation and Public Safety Act, which bans traps, snares and poisons on public land",
 "SB 317": "which raises the tax on health insurance to 3.75 percent to bring down coverage costs",
 "SB 17": "the Family Income Index Act, which sends extra money to schools serving the poorest families",
 "HB 2": "the Cannabis Regulation Act, which legalized cannabis for adults 21 and older",
 "HB 37": "which starts a grant program to make low-income homes use less energy",
 "HB 132": "which caps small loan interest rates at 36 percent a year",
 "HB 22": "which requires every state department to make its programs usable by people who do not speak English well",
 "SB 140": "the Opportunity Scholarship Act, which writes the state's free tuition promise into law",
 "HB 9": "which makes it a crime to store a gun carelessly where a minor can get it and do harm",
 "HB 31": "which drops the rule that a person changing their legal name must publish a newspaper notice",
 "HB 169": "which lets people talk publicly about ethics complaints they file against state lawmakers",
 "HB 7": "the Reproductive and Gender-Affirming Health Care Freedom Act, which bars local governments from blocking that care",
 "HB 207": "which widens the Human Rights Act to cover governments and adds gender as a protected class",
 "HB 139": "which cuts court fees and jail time for people who cannot pay",
 "HB 533": "which raises what school districts pay toward employees' health insurance premiums",
 "HB 134": "which requires free menstrual products in public school bathrooms",
 "SB 1": "the Regional Water System Resiliency Act, which lets local governments form regional water authorities",
 "HB 481": "which makes the state reading materials fund support science of reading materials",
 "SB 64": "which bars sentencing a child to life in prison without parole",
 "HB 547": "the 2023 tax package, which sent $500 rebates and raised the child tax credit",
 "SB 180": "a large rewrite of election law, with vote centers, poll watcher training and new mailed ballot rules",
 "SB 72": "which creates a wildlife corridors fund for safe highway crossings",
 "SB 397": "which puts school-based health centers into state law",
 "SB 181": "which makes prescribers of a five-day opioid supply also prescribe naloxone",
 "SB 13": "which shields patients and providers of lawful reproductive or gender-affirming care from punishment",
 "SB 273": "which requires health plans to treat mental health like other medical care",
 "SB 280": "the Cybersecurity Act, which sets up a state office to guard New Mexico's computer systems",
 "HB 129": "which requires a seven-day wait between a gun sale and handing the gun over",
 "HB 41": "which sets up a clean transportation fuel standard cutting fuel emissions 20 percent by 2030",
 "HB 151": "which tells state-funded colleges to write affirmative consent rules for sexual activity",
 "HB 195": "which lets the New Mexico Finance Authority lend money for affordable housing",
 "HB 252": "which rewrote the income tax brackets from 2025 with a 1.5 percent bottom rate",
 "SB 153": "which raises the yearly payout from the early childhood fund to at least $250 million",
 "HB 182": "which requires disclaimers on campaign ads using fake audio or video and makes deceptive use a crime",
 "SB 159": "which moves $959 million into a permanent savings fund for higher education",
 "SB 15": "which gives state regulators a say when a hospital is bought or merged",
 "SB 96": "which raises the prison term for second degree murder to 18 years",
 "HB 8": "a public safety package that lets courts send some defendants to community programs instead of jail",
 "HB 6": "which extends the prevailing wage law to projects financed with industrial revenue bonds",
 "HB 91": "which lets the utility board approve special rates for large new customers",
 "HB 12": "which lets police seek an extreme risk firearm order based on their own information",
 "HB 89": "which opens state graduate scholarships to residents regardless of citizenship",
 "HB 128": "which creates a fund for grants to local governments and tribes to install solar power",
 "HB 78": "which bars drug makers from blocking clinics' access to 340B discounted medicine",
 "HB 586": "which keeps and widens the state's review of health care mergers",
 "SB 57": "which keeps records naming public health workers who provide abortion care out of public records requests",
 "SB 36": "which limits what state workers may do with people's private details such as immigration status",
 "SB 7": "which lets a city run a storm water system as a municipal utility with fees",
 "SB 21": "which lets New Mexico run its own water pollution permit program instead of the federal government",
 "SB 48": "which creates a community benefit fund for projects that cut greenhouse gases",
 "SB 124": "which lets the insurance superintendent issue subpoenas during an investigation",
 "SB 83": "which creates a fund to help agencies plan for net zero emissions",
 "SB 23": "which raises the royalty on new oil and gas leases on the most productive state land",
 "SB 267": "which caps rental screening fees at $50 and requires listings to state every fee",
 "HB 493": "which sets audit rules a local government must meet before getting a state building grant",
 "SB 37": "which creates a strategic water reserve fund of up to $15 million",
 "SB 16": "which lets voters with no party vote in a major party's primary election",
 "SB 59": "which extends public works minimum wage rules to off-site shops making ductwork for the job",
 "SB 9": "which raises the fines for breaking oil and gas pipeline rules to match federal fines",
 "SB 376": "which makes the state pay 80 percent of every worker's health insurance cost from July 2025",
 "SB 88": "which creates a Medicaid trust fund that pays out once it holds $500 million",
 "SB 45": "which lets counties pay poor residents' insurance premiums from their health care assistance fund",
 "SB 120": "which permanently bars health plans from charging out of pocket for behavioral health care",
 "SB 364": "which lets non-citizens with federal work authorization be hired as police officers",
 "SB 3": "which moved control of New Mexico's vaccine rules to the state Department of Health",
 "SB 2": "which lets the state borrow $1.5 billion more for highways, paid for by higher truck taxes and fees",
 "HB 247": "which tightens the rules for capital outlay money for building projects",
 "HB 156": "which keeps the Department of Health in charge of school vaccine rules",
 "HB 124": "which creates a New Americans Division in the state workforce department",
 "HB 200": "which creates a loan program for first-time buyers of newly built starter homes",
 "HB 270": "which widens who must pay into apprentice training programs on public building work",
 "SB 30": "which repeals the requirement that every abortion be reported to the state registrar",
 "SB 40": "the Driver Privacy and Safety Act, which bars sharing license plate camera data for immigration enforcement",
 "SB 264": "which bars armed troops at polling places or within 50 feet of ballot drop boxes",
 "SB 241": "which writes the child care assistance program into law",
 "SB 152": "which creates a program to help low-income households pay for phone and internet service",
 "SB 111": "which keeps a driver's sex, gender identity, immigration status and national origin private",
}
