CLOSE = {
 1550524: "The Nevada Assembly passed an earlier version 29-13, and the bill was later signed into law.",
 1551589: "The Nevada Assembly passed an earlier version 28-14, and the bill was later signed into law with Senate changes.",
 1553680: "The Nevada Assembly passed an earlier version 27-15, and the bill was later signed into law with Senate changes.",
 1568169: "The Nevada Assembly passed it 26-15, but the governor vetoed the final version, so it never became law.",
 1578609: "The Nevada Senate passed it 13-7, but the Senate never voted on the Assembly's changed version, so it never became law.",
 1578740: "The Nevada Senate passed it 13-8, but the Senate never voted on the Assembly's changed version, so it never became law.",
 1575479: "The Nevada Senate passed the debt-wiping version 14-7, and the bill was later signed into law as a ban on collecting the debt.",
}
EFFECTS = {
 "AB 90": "which extends the rights of children in state custody to regional treatment facilities",
 "AB 96": "which makes counties of 100,000 or more people include an extreme heat plan in their master plan",
 "AB 119": "a bill to let the Attorney General sue to stop private armed paramilitary groups",
 "AB 235": "which lets reproductive health workers and others hide their home address in public records",
 "AB 217": "a bill to bar schools from letting federal immigration officers on school grounds without a warrant",
 "AB 306": "a bill to require at least 10 mail ballot drop-off sites in Clark County and 5 in Washoe County",
 "AB 241": "which requires every county and city to allow apartment buildings on land zoned for business",
 "AB 185": "a bill to stop homeowners associations banning licensed child care homes",
 "AB 155": "a bill to make student-teacher ratios something school districts must negotiate with unions",
 "AB 140": "a bill to end the fixed four-year life of a driver authorization card",
 "AB 194": "which bans releasing balloons that float away, with fines up to $250",
 "AB 496": "a bill to make county clerks publish daily mail ballot counts and names of voters with questioned signatures",
 "AB 445": "a bill to give library staff immunity for good faith acts of providing access to library materials",
 "AB 121": "which makes landlords offer a fee-free way to pay rent and list rent as one figure including all fees",
 "AB 280": "a bill to make landlords refund application fees when they rent to someone else without doing the check",
 "AB 283": "a bill to make landlords, not tenants, file first in fast-track eviction cases",
 "AB 44": "a bill to make manipulating the price of food, housing, fuel or medicine an illegal restraint of trade",
 "AB 112": "a bill to let union-covered workers use earned sick leave to care for family members",
 "AB 488": "a bill to widen when a human trafficking victim can have a conviction erased",
 "AB 223": "a bill to give renters a faster court route to force repairs and hold back rent",
 "AB 201": "a bill to seal more eviction court records from public view",
 "AB 209": "a bill to give people in prostitution immunity from prosecution when evidence came from their own call for help",
 "AB 282": "a bill to make hospitals and doctors investigate disputed medical bill charges within 30 days",
 "AB 245": "a bill to bar people under 21 from having a semiautomatic shotgun or centerfire rifle",
 "AB 343": "which makes hospitals publish their standard charges and a list of 300 shoppable services",
 "AB 89": "which limits strip searches of children in juvenile facilities to cases of reasonable suspicion",
 "AB 434": "a bill to bar employers from punishing workers who skip meetings pushing the employer's religious or political views",
 "AB 480": "a bill to write the disparate impact standard into Nevada's fair housing law",
 "AB 411": "a bill to let abortion pill prescription labels carry the practice name instead of the prescriber's",
 "SB 352": "a bill to widen the ban on discrimination by health insurers to race, age, disability and sex",
 "SB 99": "a bill to let Lake Tahoe local governments charge builders a fee on large new homes for affordable housing",
 "AB 416": "a bill to stop schools and public libraries removing library materials because of their content",
 "SB 102": "a bill to make filing a false election document or serving as a fake presidential elector a felony",
 "SB 155": "a bill to let non-citizens authorized to work who served as police elsewhere be hired as peace officers",
 "SB 166": "which bars insurers from refusing or repricing a policy based on a dog's breed",
 "SB 347": "which sets rules for taking and returning guns when someone is placed on a mental health crisis hold",
 "SB 183": "which caps a child welfare permanency caseworker at 30 children",
 "SB 246": "which lets women get gynecological and pregnancy care without a referral or prior approval",
 "SB 301": "a bill to let state peace officers outside the civil service join state employee collective bargaining",
 "SB 171": "a bill to shield providers of lawful gender-affirming care from licensing punishment and out-of-state probes",
 "SB 161": "which gives teachers' unions and school districts a binding arbitration option when a contract expires",
 "SB 443": "which requires prevailing wages on large utility projects such as gas pipeline replacements and power plants",
 "SB 414": "a bill to make public officials disclose any company stock worth $5,000 or more",
 "SB 298": "which bars denying a police officer a raise or seniority increase as punishment during an investigation",
 "SB 89": "a bill to bar people convicted of hate crimes from buying or owning a gun",
 "AB 105": "a bill to make carrying a gun at or within 100 feet of a polling place a crime",
 "AB 589": "a bill to bar governments from collecting or sharing data identifying people with autism",
 "AB 259": "a bill to bar charging more than the Medicare negotiated price for those drugs in Nevada",
 "AB 483": "which moves health license applications to the front of the line for people committed to working in underserved communities",
 "AB 91": "a bill to let the parole board give a second look to people serving time for serious felonies after ten years",
 "AB 204": "a bill to bar medical debt collectors from threatening arrest, home liens or bank account seizures",
 "AB 123": "which makes threatening a candidate for public office a crime",
 "AB 414": "a bill to add air quality duties to the safety programs of large warehouse-type workplaces",
 "AB 597": "a bill to let voters with no party pick one major party's primary ballot",
 "SB 156": "a bill to create a Special Counsel for the Prevention of Gun Violence in the Attorney General's office",
 "SB 128": "a bill to bar health insurers from relying on artificial intelligence alone to deny care",
 "SB 85": "a bill to make Nevada's collection of traffic stop data permanent",
 "SB 182": "a bill to write maximum patients per nurse into law for large Clark and Washoe County hospitals",
 "SB 173": "a bill to ban added PFAS chemicals from carpets, food packaging, cosmetics and children's products",
 "SB 63": "a bill to require parental consent before online services handle data of children under 13",
 "SB 442": "which makes utilities publish quarterly reports on how often they shut off power, gas or water at homes",
 "SB 217": "a bill to protect assisted reproduction and require most large health plans to cover infertility treatment",
 "SB 260": "which starts state rules protecting workers from wildfire smoke when the air quality index reaches 150",
 "SB 157": "which makes independent laboratory testing of cannabis a requirement rather than a choice",
 "SB 370": "which puts a deadline on replacing the ownership papers for a manufactured home",
 "SB 141": "a bill to make every jail write a policy for transgender, non-binary and intersex prisoners",
 "SB 324": "a bill to ban selling water in small disposable plastic bottles in communities bordering Lake Tahoe",
 "SB 188": "which requires health providers to give free, accurate language help to patients who do not speak English well",
 "SB 284": "which stops the state using a foster child's own Social Security or veterans benefits to pay for their care",
 "SB 410": "a bill to make dependents' insurance part of what local governments must negotiate with unions",
 "SB 88": "which bars collecting medical debt from people after they leave prison",
 "AB 244": "a bill to ban polystyrene foam food containers, starting with large restaurant chains in October 2025",
 "AB 420": "which makes school districts publish a yearly report on force used by their own police",
 "SB 39": "which sets up a state loan fund for work that reduces damage from disasters",
 "AB 527": "which lets school districts put cameras on school buses to catch drivers who pass a stopped bus",
 "SB 172": "the Agricultural Workers' Bill of Rights, a bill to give farm workers earlier meal breaks and visitor access",
 "SB 424": "which charges private ambulance companies a fee and returns the money as higher Medicaid rates",
 "SB 76": "which sets up a state fund paying up to $25,000 to people cheated in securities fraud",
 "SB 391": "a bill to cap corporate purchases of Nevada homes at 100 a year",
 "SB 193": "a bill to put $10 million into lowering mortgage rates for first-time buyers",
 "AB 460": "which gives parents a form for naming a guardian to raise their child if they cannot",
 "AB 540": "which puts $133 million of state money into a new attainable housing fund",
}
