EFFECTS = {
 "S 36": "which lets abortion pill prescription labels name a health care practice instead of the prescriber",
 "S 801": "which puts electric car charging requirements for new buildings into the state building code",
 "S 745": "which takes ammunition sellers out of the payment card merchant code rule",
 "S 743": "which makes the gun dealer suicide-risk warning cover rifles and shotguns, not only handguns",
 "S 744": "which adds pistol converters to the list of banned rapid-fire modification devices",
 "A 1820": "which makes sellers strike racist covenants from property deeds",
 "A 387": "which makes every general hospital run a free language assistance program",
 "S 952": "which caps rent stabilized security deposits at one month's rent and requires full return",
 "S 3072": "which bars employers from using a person's credit record in hiring, pay or treatment at work",
 "A 4040": "which lets housing discrimination be proved by a practice's effect without proof of intent",
 "S 7882": "which bans landlords setting rents with software that pools rival landlords' private data",
 "S 123": "which bans the sale of infant walkers in New York",
 "S 1985": "which makes police take guns found in plain sight when answering a family violence call",
 "S 4906": "which lets assault victims at hospitals and care facilities give their statement at work",
 "S 1353": "which helps people forced into debt by an abuser get that coerced debt cleared",
 "S 1069": "which bars oil and gas drilling on state forests, wildlife areas and other state land",
 "S 4914": "which shields people who give or get reproductive and gender-affirming care from other states' courts",
 "S 8417": "which ends the cost break for extending a gas line to a building without gas",
 "S 8416": "the FAIR Business Practices Act, which bans unfair and abusive business acts, not only deceptive ones",
 "S 8420": "which makes advertisers say when a person in an ad is computer-made and not real",
 "S 6997": "which sets up a way to report unsafe work on utility poles",
 "S 2551": "which raises the top fine for a company convicted of a felony from $10,000 to $80,000",
 "A 10710": "which makes health plans cover vaccines recommended by the state health commissioner",
 "A 10711": "which lets state standards, not only federal ones, set the vaccines required for children",
 "S 3294": "which abolishes the medical cannabis registry card and lengthens certifications to two years",
 "A 6558": "which makes food shops label major allergens on food they pack themselves",
 "S 8311": "which makes the New York City Housing Authority put its lease succession rules in writing",
 "A 584": "which bans contracts that make a worker repay training costs to quit",
}
