EFFECTS = {
 "SB 460": "which makes natural gas the state's preferred fuel for new power plants with no end date",
 "SB 713": "which makes wind farms fit warning lights that stay off until a plane is near",
 "SB 889": "which makes hospitals publish their prices and bars those that do not from chasing patients for payment",
 "SB 109": "which makes health plans pay for cancer gene tests and scans for people at higher risk",
 "HB 1727": "which opens the Oklahoma's Promise scholarship to more teachers' children",
 "HB 2263": "which bans holding a phone while driving through a school zone or work zone",
 "SB 631": "which adds firing a gun into a home or building to the crimes requiring 85 percent of the sentence served",
 "SB 212": "which sets up a two-year trial of new routes into teaching called TeachForwardOK",
 "SB 250": "which lets tips cover more of a tipped worker's minimum wage",
 "SB 1027": "which requires plain-word summaries on citizen petition signature pages",
 "HB 1601": "which lets school staff add their own sick days to paid maternity leave",
 "HB 2764": "which cuts the top income tax rate from 4.75 to 4.5 percent from 2026 and sets a path for more cuts",
 "SB 942": "which bans discrimination in schools and colleges and treats anti-Semitism as a form of it",
 "SB 364": "which widens the ban on paddling students with disabilities",
 "SB 743": "which raises the penalty for disturbing a religious service and adds a buffer zone outside",
 "SB 139": "which made every school district ban student phones for the 2025-2026 school year",
 "HB 1393": "which requires signed parental consent before a special education child is moved to alternate tests",
 "HB 1003": "which raises the age below which sex is always a crime to under 18 with a close-in-age rule",
 "SB 758": "which stops online lesson days counting as class time from the 2026-2027 school year",
 "SB 991": "which adopts the International Holocaust Remembrance Alliance definition of anti-Semitism",
 "SB 998": "which lets electric companies charge customers for new plants sooner and with less review",
 "SB 176": "which lets people pick up several months of birth control at a time",
 "SB 658": "which stops the child welfare agency ruling out foster parents over their beliefs about sexual orientation",
 "HB 3151": "which raises the minimum number of school days for districts that count instruction in hours",
 "HB 4071": "which sets up a one-time $250 state deposit into a child's federal Trump Account",
 "SB 137": "which bars one more group of inmates from serving time at home on an electronic monitor",
 "SB 1833": "which orders the state to seek a federal waiver barring candy and soda from food aid",
 "SB 1344": "which pays a drug maker to produce a cheaper fast-acting insulin",
 "SB 1618": "which makes a court use a risk report before setting release terms in a violent case",
 "SB 1443": "which tells health plans to weigh how sick a patient is when paying for anesthesia",
 "HB 3644": "the Blake Burgess Act, which sets rules for hospitals to spot and treat dangerous blood clots",
 "HB 3834": "which lets the state help pay for trials of ibogaine as an addiction treatment",
 "SB 504": "which ends marriage before the age of 18",
 "SB 2084": "which caps what a state college may pay a professor to settle a state-law wrongful firing claim",
 "HB 1576": "which makes Medicaid cover rapid whole genome testing for very ill children",
 "HB 2049": "which makes the state check that Medicaid plans cover mental health care as fully as other care",
 "HB 1087": "which adds a day to the school year and extends the teacher pay scale for long-serving teachers",
 "SB 54": "which widens the crime of aggravated drunk driving and makes it a felony",
 "SB 20": "which adds immigration and English language checks for commercial truck drivers",
 "SB 1847": "which widens who can get Medicaid care at home instead of in a nursing home",
 "HB 3467": "which extends paid maternity leave for school staff to parents who adopt",
 "HB 3985": "which lets property owners in big cities claim money when local government stops enforcing camping laws",
 "HB 1168": "which makes it a felony to supply abortion pills for an illegal abortion",
 "SB 259": "which tightens rules on wasting groundwater and bars data centers from cooling with evaporating groundwater",
 "SB 1451": "which asks people registering to vote where they were registered before so the old record can be removed",
}
