EFFECTS = {
 "HB 2010": "which keeps two health insurance charges that fund the Oregon Reinsurance Program alive through 2032",
 "HB 3024": "which ends the extra penalty that cut a year's total jobless pay for workers fired for misconduct",
 "HB 2586": "which lets people seeking asylum pay in-state tuition at Oregon's public universities",
 "HB 3550": "which takes unionized minor league baseball players out of Oregon's minimum wage and workplace rules",
 "HB 3025": "which changes how Oregon sets the size of its main college grant for students with financial need",
 "HB 2563": "which gives home insurance customers the right to a plain written explanation of why their premium rose",
 "HB 3863": "which opens standard utility power purchase terms to larger small solar, wind and hydro projects",
 "HB 2964": "which creates state loans for the early planning costs of building affordable homes",
 "HB 3187": "which bars employers from asking an applicant's age or graduation dates before the first interview",
 "HB 3233": "which pushes Oregon to plan passenger rail with Washington and British Columbia and report on it",
 "HB 3054": "which caps yearly rent increases at six percent in larger manufactured home parks and floating home marinas",
 "HB 3521": "which stops landlords keeping a holding deposit when the applicant walks away over serious defects",
 "HB 3646": "which lets state and local agencies favor employee-owned firms when buying goods or services",
 "HB 3932": "which bars hunting or trapping beavers for sport in and beside Oregon's most polluted public waters",
 "HB 2081": "which makes the state treat climate change as a risk to the public employee pension fund",
 "SB 91": "which bars fire departments from using firefighting foam that contains forever chemicals",
 "HB 3409": "which limits when a drug plan may force a low-income clinic to tag discount drug claims",
 "HB 2931": "which updates the law for replacing the Interstate 5 bridge between Oregon and Washington",
 "SB 867": "which gives the State Board of Education more ways to act when a school is found to have discriminated",
 "SB 295": "which lets pharmacists keep testing for and treating COVID-19 with no end date",
 "SB 599": "which bars landlords from asking about the immigration or citizenship status of tenants or applicants",
 "SB 1191": "which says telling someone their civil or constitutional rights is not a crime",
 "SB 827": "which widens the solar rebate to cover a home battery added to panels installed earlier",
 "SB 906": "which makes employers give every new hire a written guide to the pay and deductions on a pay stub",
 "SB 551": "which closes the loophole that let stores hand out thick plastic bags at the register from 2027",
 "HB 2944": "which sets required fines for public employers that keep breaking the rules on union dues",
 "SB 982": "which sets conditions before a school district may place a student in an out-of-state residential facility",
 "SB 951": "which stops outside investors from running medical practices through a management company",
 "SB 426": "which makes the main contractor on a building job answer for wages a subcontractor fails to pay",
 "SB 430": "which requires online sellers to show the full price up front, including every fee",
 "SB 605": "which bars medical debt from credit reports and from being reported to credit bureaus",
 "SB 726": "which makes the Benton County landfill find and plug methane leaks",
 "HB 2385": "which stops drug makers blocking the discount drug program for clinics serving low-income patients",
 "SB 150": "which bars charging veterans for help with a benefits claim",
 "HB 3546": "which puts data centers and other very large power users in a rate class of their own",
 "SB 1098": "which stops schools rejecting library books because of who wrote them or whose story they tell",
 "HB 3825": "which wipes out old court debts from small marijuana possession convictions before July 2015",
 "SB 916": "which lets locked-out workers draw unemployment pay at once and striking workers after one week",
 "HB 2677": "which makes county juvenile departments apply to clear old juvenile records themselves",
 "HB 3336": "which makes big power companies show whether cheaper fixes could carry more power before building lines",
 "HB 2684": "which makes school boards keep their pest control plans current and posted online",
 "SB 141": "which sets statewide targets and a common yardstick for how Oregon school districts are doing",
 "HB 3365": "which requires Oregon schools to teach about climate change in six subjects",
 "HB 3194": "which strengthens the rules for farmworker housing camps and raises minimum damages",
 "HB 3644": "which sets up a statewide shelter program run by the state housing department",
 "HB 3148": "which adds up to $100 toward a computer to the Oregon Lifeline phone and internet help",
 "HB 3792": "which doubles the fund that helps low-income households pay power bills to at least $40 million a year",
 "HB 3410": "which closes gaps in the law that stops outside investors running medical practices",
 "SB 822": "which tightens the test for whether a health insurer has enough doctors in its network",
 "SB 243": "which bans bump stocks and other devices that make a gun fire faster",
 "HB 2688": "which extends Oregon's prevailing wage to custom work built off-site for public works projects",
 "SB 537": "which widens Oregon's rules on violence against health care workers to more employers",
 "HB 3069": "which pulls county public safety grants into one program run by the Criminal Justice Commission",
 "SB 1168": "which bars paying home health and home hospice staff by the visit instead of by the hour",
 "HB 3865": "which extends telemarketing rules to text messages and bars sales pitches before 8 a.m. or after 8 p.m.",
 "SB 476": "which helps people trained abroad get licensed to work in Oregon, including a starter license for doctors",
 "HB 2138": "which makes larger cities allow duplexes, fourplexes and cottage clusters on any residential lot",
 "SB 1154": "which adds an early warning step to how Oregon deals with polluted ground water",
 "HB 3525": "which makes landlords test the drinking water yearly at rentals on small private wells in ground water management areas",
 "SB 1173": "which shields hospitals and clinics from product liability claims over items they hand a patient",
 "SB 824": "which makes health insurers report how they treat mental health claims next to medical ones",
 "HB 4013": "which stops state limits on child working hours being looser than the federal ones as of 2026",
 "HB 4031": "which lets some renewable power projects with local approval skip the state siting certificate",
 "HB 4088": "which shields reproductive and gender-affirming health care that is legal in Oregon",
 "HB 4079": "which makes schools tell families when federal immigration officers have come onto school grounds",
 "HB 4069": "which makes mental health and addiction treatment employers write a safety plan for lone workers",
 "HB 4116": "which pulls Oregon out of a federal rule that let lenders charge rates Oregon does not allow",
 "HB 4111": "which keeps a person's immigration status out of most civil lawsuits in Oregon",
 "HB 4134": "which raises the state lodging tax from 1.5 to 2.75 percent and sends the extra money to wildlife",
 "SB 1512": "which reshapes the Prosperity 10,000 job program as grants to local workforce boards",
 "SB 1507": "which makes Oregon tax income that new federal breaks had freed and pays some back to low-paid workers",
 "SB 1538": "which bars Oregon schools from treating students worse over their immigration or citizenship status",
 "HB 4089": "which sharpens the theft of services crime against employers who take work and do not pay for it",
 "SB 1576": "which lets the state set stricter accessibility standards than federal law for housing",
 "SB 1587": "which stops government bodies handing personal data to data brokers for immigration enforcement",
 "SB 1570": "which makes hospitals write a plan for responding when police arrive",
 "SB 1590": "which bars Oregon governments from helping sell off federal public land",
 "SB 1594": "which makes the state write its immigration request rules with immigrant families in mind",
 "SB 1598": "which makes health plans cover more preventive care at no charge, using the June 2025 federal list",
 "HB 4016": "which makes big state contractors certify they have paid their taxes before signing a contract",
 "HB 4036": "which sets up a bond-funded state fund to hold on to low-cost housing at risk of being lost",
 "HB 4127": "which keeps state money going to reproductive health clinics that federal law cut off from Medicaid",
 "HB 4076": "which makes it easier to add power generation at a site already hooked up to the grid",
 "HB 4153": "which allows farm stores and paid visitor attractions on land zoned for farming",
 "HB 4128": "which makes the biggest housing investors wait 90 days before buying a listed single-family home",
 "HB 4018": "which puts off Oregon's new campaign money disclosure rules by three years, to 2031",
 "SB 1515": "which makes it easier for a wrongly convicted person to be paid for the years taken from them",
 "HB 4075": "which makes the State Treasurer guarantee a loan to keep a rural hospital afloat by April 2027",
 "HB 4138": "which requires officers on enforcement duty to wear a uniform showing their name or number and agency",
 "HB 4159": "which changes who sits on Oregon's ethics board and keeps legal privilege for messages to it",
 "HB 4179": "which extends the state's legal shield to doctors at nonprofits set up by Oregon Health and Science University",
 "SB 1032": "which bars stores from selling aerosol dusters containing the gas DFE to anyone under 18",
 "HB 2530": "which helps schools run cameras that catch drivers passing a stopped school bus",
 "HB 3144": "which voids new deed and homeowner group rules that block manufactured homes on a house lot",
 "HB 2957": "which bars employers from making workers agree to shorter deadlines for labor law claims",
 "HB 3912": "which makes anyone calling themselves a doctor in health work say what field their doctorate is in",
 "SB 598": "which makes drug plans cover at least one non-opioid pain drug for each opioid they cover",
 "HB 3179": "which makes utility regulators weigh what a rate rise does to household bills already piled up",
 "SB 1523": "which stops a landlord making an online portal the only way to apply for a home",
 "SB 1575": "which pauses new hospice licenses in Oregon while the state writes tougher rules",
 "HB 4060": "which lets school districts and some others keep buying fluorescent lamps despite the mercury ban",
 "HB 4115": "which makes caregiver criminal records checks last three years instead of 18 months",
 "SB 1568": "which widens what the Oregon Health Plan and private plans must cover around birth, including doulas",
 "HB 4142": "Ryan's Law, which lets patients use medical marijuana in care facilities where they live",
 "HB 4114": "which lets people sue an official who enters their property without a warrant",
 "HB 4144": "which makes battery makers pay to collect and recycle what they sell in Oregon",
}
