CLOSE = {1567196: "The Pennsylvania House passed this version 148-55; the Senate tightened it, the House agreed 201-2, and it became law as Act 28 of 2025.",
 1567634: "The Pennsylvania House passed it 102-101, but a Senate committee voted 3-7 on May 13, 2025 not to advance it, and it went no further.",
 1707969: "The Pennsylvania Senate defeated it 23-27, then voted the same day to reconsider, leaving the bill pending as of August 2026."}
OPEN = {1570575: ("Voted for House Bill 1396", "Voted against House Bill 1396")}
EFFECTS = {
 "HB 77": "a bill to make every food business post allergen information for staff and tell customers which allergens its menu items contain",
 "HB 111": "a bill to bar life insurers from denying, cancelling, or repricing coverage because someone picked up a naloxone prescription",
 "HB 118": "a bill to double the criminal fines for breaking the child labor law, to $1,000 for a first violation and $3,000 after that",
 "HB 404": "a bill to put the right to stay on a parent's health insurance until age 26 into state law",
 "HB 535": "a bill to bar insurers from capping yearly or lifetime payouts for core benefits if the federal protection is ever repealed",
 "HB 755": "a bill to make health plans cover preventive care, screenings, and recommended vaccines with no copay or deductible",
 "HB 618": "a bill to bar insurers from denying coverage or charging more for a pre-existing condition if the federal protection is ever repealed",
 "HB 183": "a bill to expand workers' compensation for permanent disfigurement, covering more injuries and paying injured workers more",
 "HB 308": "a bill to make the state write workplace safety standards for public employers, which private employers already follow under federal law",
 "HB 764": "a bill to create a state financing program that brings grocery stores and fresh food to areas that lack them",
 "HB 819": "a bill to make schools open Advanced Placement, dual credit, and other college-level classes to more students",
 "HB 316": "a bill to let a town deny a permit to a company with unpaid property taxes, unpaid town bills, or an unfixed serious code violation",
 "HB 273": "a bill to let counties adopt and enforce their own property maintenance codes, with state grants of up to $100,000 per town to start enforcement",
 "HB 743": "a bill to let a town hand a long-abandoned, blighted property to a land bank that returns vacant property to use",
 "HB 643": "a bill to raise the realty transfer tax money flowing into the state housing affordability fund by $10 million, to $110 million a year",
 "HB 630": "a bill to extend the equal pay law to race and ethnicity, protect workers who discuss pay, and bar setting wages from past pay",
 "HB 734": "a bill to make landlords provide a habitable home and act within 60 hours when a rental is condemned",
 "HB 193": "a bill to require at least one defibrillator in every state building, plus one more for every 70,000 square feet",
 "HB 81": "a bill to ban charging customers extra for a paper bill or for paying by mail",
 "HB 789": "a bill to let electric vehicle charging projects use the state's clean energy financing program for business property",
 "HB 926": "a bill to make every hospital, nursing home, and other health care site run a program to prevent violence against staff",
 "HB 265": "a bill to let school aides, bus drivers, and cafeteria workers collect unemployment benefits over summer break",
 "HB 103": "which lets towns and police remove abandoned or sunken boats from Pennsylvania waters at the owner's expense",
 "HB 986": "a bill to void unfair long-term real estate service agreements and let consumers sue over them",
 "HB 504": "a bill to allow shared community solar projects, letting people subscribe to a shared site and get credit on their electric bill",
 "HB 1200": "a bill to legalize cannabis for adults 21 and over through state-run stores and clear past minor cannabis convictions",
 "HB 1062": "a bill to create a public registry of owners with serious property code violations left unfixed for a year, with $1,000 fines per violation",
 "HB 721": "a bill to bar contractors who deliberately misclassify workers from public works contracts for at least three years",
 "HB 67": "a bill to stop condo and homeowners associations from unreasonably banning outdoor clothes drying on a member's own lot",
 "HB 1263": "a bill to create Keystone Saves, automatically enrolling workers with no retirement plan at work in a state-run savings account they can opt out of",
 "HB 1396": "a broad election code rewrite to create in-person early voting in every county and require at least two ballot drop boxes per county",
 "HB 359": "a bill to let towns spend some tax increment financing money on keeping current residents from being pushed out by new development",
 "HB 1140": "a bill to make health insurers, Medicaid, and the state children's health plan cover birth control and adult sterilization at no out-of-pocket cost",
 "HB 858": "which makes every county keep a contact list for property whose owner lives elsewhere, so code violations reach someone who can fix them",
 "HB 282": "a bill to use Medicaid to start addiction treatment for people in county jails in the weeks before release",
 "HB 1089": "a bill to ban driveway and parking lot sealants high in PAH chemicals, with fines of up to $2,500 per violation",
 "HB 464": "a proposed constitutional amendment to open a two-year window to sue over childhood sexual abuse despite old filing deadlines",
 "HB 462": "a bill to open a two-year window for adults abused as children to sue even though the normal deadline has passed",
 "HB 846": "a bill to extend the prevailing wage law to HVAC duct cleaning and off-site custom work and to ban split pay rates on public jobs",
 "HB 1189": "a bill to let the treasurer return unclaimed property under $10,000 to its owner without a claim and free up federal Solar for All money",
 "HB 1250": "a bill to cap yearly lot rent increases in manufactured home communities at the inflation rate, between 2% and 4%, with 90 days' notice",
 "HB 1088": "a bill to make health insurers cover a blood pressure monitor for pregnant and postpartum patients when a doctor orders one",
 "HB 1460": "a bill to let the attorney general review health care mergers and block those found against the public interest",
 "HB 967": "a bill to cap the fee on a resold event ticket at 5% of the ticket price",
 "HB 276": "a bill to let the revenue department share tax data with state labor offices investigating employers who misclassify workers as contractors",
 "HB 1549": "a bill to raise the minimum wage from $7.25 to $12 to $15 an hour by 2028, depending on the county",
 "HB 1364": "a bill to raise the share of state sales tax for public transit from 4.4% to 7.9% and fund $500 million in road work",
 "HB 350": "a bill to set one set of rules for who counts as a child's legal parent, whatever the parents' marital status or gender",
 "HB 1282": "a bill to make towns and counties tell affected property owners within 45 days when federal flood maps change",
 "HB 1095": "a bill to hide old eviction filings from public court records after seven years, or right away if the tenant won",
 "HB 1216": "a bill to make event tickets, hotel rooms, and food delivery show the full price with all mandatory fees up front",
 "HB 1048": "a bill to let towns use public money and crews to repair private water and sewer laterals when public health is at stake",
 "HB 205": "a bill to free drivers from early termination penalties on a leased vehicle when the state pulls their license for medical reasons",
 "HB 583": "a bill to restore Medicaid adult dental coverage at least to what was covered before September 2011",
 "HB 994": "a bill to ban buying or selling the parts and products of listed at-risk animal species",
 "HB 1534": "a bill to expand the child and dependent care tax credit, including for taxpayers who use a dependent care program at work",
 "HB 1445": "a bill to stop health insurers refusing to cover mental health care or speech therapy just because a student got it at school",
 "HB 506": "a bill to pay annual lump sums to child care providers so they can hire and keep staff",
 "HB 1100": "a bill to seek federal permission for food stamp and WIC recipients to buy diapers and period products with their benefits",
 "HB 1650": "a bill to create a state grant program helping local governments repair and improve existing homes",
 "HB 1553": "a bill to cap bank overdraft and insufficient funds fees at $15, limit them to three a day, and bar fees on declined transactions",
 "SB 95": "which makes pharmacists tell customers a drug's price on request and lets ambulance crews hand naloxone to a family member or friend",
 "HB 1234": "a bill to make Medicaid and the state children's health plan cover a home blood pressure monitor for pregnant and postpartum patients",
 "HB 1574": "a bill to let redevelopment agencies and land banks borrow up to $500,000 in startup money from the state",
 "HB 129": "a bill to set consumer protection rules for automatic renewals, roll-on subscriptions, and free trials that turn into paid plans",
 "HB 956": "a bill to cover county, city, and township employees under the aggravated assault law, which carries tougher penalties",
 "HB 1358": "a bill to make hotels with 100 or more rooms give a free two-way safety device to any employee working alone in a guest room",
 "HB 1093": "a bill to make drivers under 18 wear a seat belt and secure every passenger aged 8 to 17",
 "HB 1577": "a bill to limit restraints, seclusion, and strip searches on children in state-regulated institutions to last-resort cases",
 "HB 1697": "a bill to create a state false claims law making anyone who defrauds the state pay three times the loss plus a penalty",
 "HB 1788": "a bill to raise the share of state sales tax going to public transit from 4.4% to 6.15% and start a road and bridge fund",
 "HB 1099": "a bill to make it a felony to make, sell, or own an undetectable gun that airport screening or a metal detector cannot find",
 "HB 1593": "a bill to require a background check on every private gun sale, not just handguns",
 "HB 1859": "a bill to create red flag orders letting a judge take guns from someone found to pose a serious risk to themselves or others",
 "HB 1866": "a bill to ban machine gun conversion devices, with up to five years in prison for making, selling, or owning one",
 "HB 102": "a bill to make harassing a sports official over their calls a misdemeanor crime",
 "HB 78": "a bill to let people see, correct, and delete the personal data companies hold and opt out of targeted ads and data sales",
 "HB 997": "a bill to make companies report a data breach as soon as they discover it, including breaches of encrypted data that can be read",
 "HB 441": "a bill to let the state protect native insects and other land invertebrates as protected species",
 "HB 145": "a bill to let workers on strike or locked out collect unemployment benefits",
 "HB 664": "a bill to make the state publish a yearly road salt best practices guide to cut salt runoff",
 "HB 1701": "a bill to have the education department assess the condition of every public school building and help districts improve them",
 "HB 1512": "a bill to create a right to repair, making manufacturers sell repair shops and owners the manuals, parts, and tools to fix their equipment",
 "HB 1882": "a bill to require 16-point type in reverse mortgage contracts and license branch managers at non-bank mortgage lenders",
 "HB 1828": "a bill to make health insurers cover certain vaccines with no copay, deductible, or coinsurance",
 "HB 1995": "a bill to delay by two years the trigger that cuts unemployment benefits when the state's unemployment fund runs low",
 "HB 1233": "a bill to make companies that sell portable batteries pay into a recycling program or stop selling them in Pennsylvania",
 "HB 458": "a bill to let a veteran reopen a conviction or sentence that ignored evidence of a service-connected mental health disability",
 "HB 1425": "which sets up a state list of nicotine vapes that may be sold here, with yearly certification, a $50,000 bond, and fees for makers",
 "HB 1881": "a bill to let experienced pharmacy technicians register without a diploma and let the CDC set the rules pharmacists follow for shots",
 "HB 1825": "a bill to make employers write down their harassment, discrimination, and retaliation policies, with fines of $500 to $5,000 for violations",
 "HB 505": "a bill to expand the state energy efficiency program and raise the share of its money allowed for pilots and new technology to 5%",
 "HB 150": "a bill to let a court shorten the prison term of someone who is terminally ill or too ill or frail to care for themselves",
 "HB 1957": "a proposed constitutional amendment to guarantee a right to decide one's own reproductive care, including abortion before viability",
 "HB 1663": "a bill to mail one free book a month to every registered child under five",
 "HB 1526": "a bill to make natural gas utilities write yearly plans for finding and fixing worn-out pipelines",
 "HB 1909": "a bill to make assault, stalking, harassment, and similar crimes one level more serious when the offender also broke a protective order",
 "HB 660": "a bill to set minimum energy and water efficiency standards for appliances, faucets, showerheads, toilets, and similar products sold in the state",
 "HB 1935": "a bill to set tougher sentences for threatening a school or college and make offenders repay the cost of the emergency response",
 "HB 1923": "a bill to make meat packing and food processing plants with 100 or more workers run joint safety committees and train new workers",
 "HB 144": "a bill to let probation and court officers steer young people into diversion programs instead of formal charges",
 "HB 460": "a bill to expand what school staff must be trained to spot and report about child abuse",
 "HB 1936": "a bill to move young people into court-ordered placement faster and allow community alternatives to locking a child up",
 "HB 1260": "a bill to make large new warehouses solar-ready and let local governments give tax breaks for retrofitting existing buildings",
 "HB 2189": "a bill to raise the minimum wage from $7.25 to $15 an hour by 2029, then tie it to the cost of living",
 "HB 1800": "a bill to define marriage as a contract between two people and repeal the state law barring same-sex marriage",
 "HB 1718": "a bill to make home insurers warn customers that a homeowner policy does not cover flood damage",
 "HB 200": "a bill to create a state paid family and medical leave program funded by payroll contributions of up to 1% of wages",
 "HB 1191": "a bill to set rail safety rules: two-person crews, a train length limit, and $10,000 fines for blocking crossings against emergency vehicles",
 "HB 2150": "a bill to make large data centers report their yearly energy and water use to the state starting July 2027",
 "HB 2151": "a bill to have the state write a model zoning ordinance for data centers covering size, noise, water use, and emergency planning",
 "HB 1139": "a bill to require a lead-filtering water bottle filling station in new and renovated state buildings",
 "HB 1706": "a bill to make schools publish mental health warning-sign guidance and tell families twice a year what mental health services are available",
 "HB 1522": "a bill to require a fuel gas detector in any room with a gas-burning appliance when a home is sold or re-rented",
 "HB 1104": "a bill to cap at $200 what a patient can be charged for an electronic copy of their own medical records",
 "HB 2246": "a bill to let the state regulate and require permits for water used by data centers drawing more than 100,000 gallons a day",
 "SB 375": "which makes schools with sports teams keep a defibrillator at games and practices, plan for cardiac emergencies, and drill each year",
 "HB 2176": "a bill to add social media literacy to the state academic standards",
 "HB 2042": "a bill to extend youth sports concussion rules from school sports to official recreational leagues",
 "HB 2103": "a bill to ban discrimination in jobs, housing, and public places based on sexual orientation or gender identity",
 "HB 2218": "a bill to make every school district write and run a comprehensive school counseling plan",
 "HB 72": "a bill to let a tenant who is a victim of violence break a lease early, change the locks, and be protected from landlord retaliation",
 "HB 830": "a bill to strengthen what school anti-bullying policies must contain",
 "HB 2076": "a bill to create the first state permit rules for geothermal energy wells",
 "HB 558": "a bill to limit rental application fees to the actual cost of processing the application",
 "HB 2186": "a bill to allow one accessory dwelling unit, such as a basement apartment or backyard cottage, on any lot where a home is allowed",
 "HB 1814": "a bill to make every school district ban student cellphone use during the school day by the 2027-28 school year",
 "HB 1045": "a bill to make school nurses and staff who work with students take seizure first aid training every three years",
 "HB 916": "a bill to require blood lead testing for every child by age two and cover one lead test per pregnancy",
 "HB 2391": "a bill to let lenders charge prepayment penalties on investment property mortgages while keeping the ban for home loans",
 "HB 2300": "a bill to let the state route the tax filings of a business owing over $5,000 in overdue sales tax through a third party",
 "HB 2109": "a bill to stop towns from capping how many people can share a home based on family relationship, except for health and safety limits",
 "HB 1262": "a bill to make campaign finance reports be filed online with the state so anyone can search them",
 "HB 2429": "a bill to make electric utilities publish maps every two months showing where the grid can take on new solar and battery projects",
 "HB 37": "a bill to let counties start opening mail ballots up to seven days before election day",
 "HB 497": "a bill to bar foreign-influenced corporations from spending money on state elections and ballot questions",
 "HB 836": "a bill to bar state government from interfering with medically appropriate fertility treatment, including in vitro fertilization",
 "HB 2084": "a bill to create the Pennsylvania Promise scholarship, usable at any college in the state",
 "HB 2264": "a bill to make electric utilities run virtual power plant programs that link home batteries and solar panels to support the grid",
 "HB 95": "a bill to require a clear label on ads that use artificial intelligence to create or heavily alter images, video, or audio",
 "HB 1127": "a bill to join a multi-state agreement letting dentists and hygienists licensed elsewhere work in Pennsylvania",
 "HB 2037": "a bill to stop public officials from promoting a cryptocurrency or other digital asset they or their family profit from",
 "HB 2558": "a bill to ban noncompete agreements between broadcasters and their employees",
 "HB 1239": "a bill to stop homeowners associations from banning rooftop solar panels",
 "HB 1042": "a bill to end the automatic life sentence for second-degree murder, setting a minimum of at least 35 years and opening parole to current lifers",
 "SB 153": "a bill to deny unemployment benefits to a claimant who discourages their own hiring, such as skipping an interview without good reason",
 "SB 155": "a bill to make the state check death certificates every month against Medicaid and food stamp rolls",
 "SB 156": "a bill to make the state check wage records every three months against Medicaid and food stamp rolls",
 "SB 35": "a bill to pull seven counties, including Westmoreland, Luzerne, and Lackawanna, out of the stricter car emissions testing program",
 "SB 149": "a bill to exempt vehicles from emissions testing for their first five years",
 "SB 186": "a bill to repeal the state rules that make power plants pay for the carbon dioxide they release",
 "SB 471": "a bill to make prosecutors report a defendant to federal immigration officers whenever they suspect the person is not a citizen",
 "SB 490": "a bill to bar releasing a defendant without cash bail once a judge finds the person is a threat to public safety",
 "SB 96": "a bill to make threatening a school or college a felony and make offenders pay the cost of the emergency response",
 "SB 92": "a bill to set a 10-year mandatory minimum sentence for drug delivery resulting in death by sellers with two or more prior drug convictions",
 "SB 9": "a bill to bar transgender girls and women from women's sports teams at public schools and colleges, with a right to sue over violations",
 "SB 227": "a bill to bring the Pennsylvania School Boards Association under the state's open records law",
 "SB 226": "a bill to bring the Pennsylvania School Boards Association under the state's open records law",
 "SB 686": "a bill to make it a felony to destroy, hide, or alter a public record someone has requested under the open records law",
 "SB 444": "a bill to require a fresh review of any regulation costing more than $1 million a year, three years after it takes effect",
 "SB 333": "a bill to require a legislative vote before any regulation costing more than $1 million a year can take effect",
 "SB 311": "a bill to stop towns from blocking utility hookups based on the type of energy, ending local bans on new natural gas connections",
 "SB 114": "a bill to expand long-term care training for nurse aides and widen who may sit the nurse aide exam",
 "SB 6": "a bill to create a tracking system for permit applications and make every state agency review its permit process",
 "SB 1068": "a bill to repeal the state rules that make power plants pay for the carbon dioxide they release",
 "SB 712": "a bill to tighten how abandoned oil and gas wells must be sealed, requiring a confirmed cement plug at least 50 feet long",
 "SB 704": "a bill to have the state find and list good sites for new natural gas power plants",
 "SB 990": "a bill to bar state agencies and local governments from restricting vehicles based on what fuel powers them",
 "SB 614": "a bill to place medical, nursing, and dental students in rotations at rural and community health clinics, with federally funded stipends",
 "SB 1293": "a bill to bar transgender girls and women from women's school and college sports teams, with a right to sue over violations",
 "SB 1298": "a bill to remove every county from the enhanced vehicle emissions inspection program and bar adding new ones",
 "SB 822": "a bill to void all local gun and ammunition rules and let anyone harmed by one sue the town and collect attorney fees",
 "SB 1236": "a bill to let construction sites disturbing one to five acres apply to skip the federal clean water permit",
 "SB 1279": "a bill to set deadlines for state review of housing permits, with a missed deadline counting as approval",
 "SB 49": "a bill to create a Cannabis Control Board over medical cannabis and tighten hemp product rules, without legalizing recreational use",
 "SB 908": "a bill to extend the prevailing wage law to off-site custom fabrication while removing small residential rehabs and duct cleaning from coverage",
 "SB 482": "a bill to make the state tell eligible older adults about the LIFE program, which helps frail seniors keep living at home",
 "SB 1400": "a bill to replace the automatic life sentence for second-degree murder with a court-set minimum of at least 35 years, making parole possible",
}
