CLOSE = {
 1509675: "The South Dakota House vote was 53-16, after first rejecting the bill 35-34 the same day. The Governor signed it on March 13, 2025.",
 1516742: "The South Dakota House vote was 56-14 on the final compromise text. The Governor signed it on March 31, 2025.",
 1603107: "The South Dakota House vote was 51-18 at the September 2025 special session. The Governor signed it on September 23, 2025.",
 1603108: "The South Dakota Senate vote was 24-11 at the September 2025 special session. The Governor signed it on September 23, 2025.",
 1516989: "The South Dakota House voted 27-43 on overriding the Governor's veto, short of the 47 votes needed, so it did not become law.",
 1672644: "The South Dakota House voted 36-27 on overriding the Governor's veto, short of the 47 votes needed, so it did not become law.",
 1499453: "The South Dakota House passed it, 36-34. The Senate vote of 17-16 fell short of the 18 needed, so the bill did not become law.",
 1506886: "The South Dakota Senate vote was 20-14, agreeing to the House version that became law. The Governor signed it on March 13, 2025.",
}
EFFECTS = {
 "HB 1052": "which banned using eminent domain for carbon dioxide pipelines",
 "HB 1073": "a bill to close voters' phone numbers and email addresses to public inspection",
 "HB 1094": "which raised the penalty for illegally passing a school bus to a Class 1 misdemeanor",
 "HB 1127": "which put election machine testing and audit notices on the Secretary of State's website",
 "SB 12": "which capped loans to a candidate at the same limit as donations",
 "HB 1054": "a bill to let public schools take on chaplains",
 "HB 1130": "which moved city and school elections onto the June and November election dates",
 "SB 51": "a bill to require the Ten Commandments to be displayed in every public school",
 "HB 1117": "a bill to require hands-free phone use while driving",
 "HB 1058": "a bill to keep medical debt off credit reports",
 "HB 1201": "a bill to bar school staff from teaching about gender identity and require them to tell parents",
 "HB 1238": "which set rules for people who charge veterans to help with benefit claims",
 "HB 1223": "a bill to create a conscience exemption from vaccines made with genetic material",
 "HB 1260": "a bill to write a biological definition of sex into vital records and driver's licenses",
 "HB 1264": "which required campaign reports to show money still owed on loans",
 "HB 1036": "which requires refilling the state's savings funds when they fall below ten percent of spending",
 "HB 1115": "a bill to make stealing a gun from a vehicle a felony",
 "HB 1235": "a bill to cut the yearly cap on property tax collection growth to two and a half percent",
 "HB 1040": "which raised high school students' share of reduced-rate college course costs from a third to half",
 "HB 1249": "a bill to let landowners sue over pressure tactics used to get carbon pipeline easements",
 "HB 1242": "a bill to cap what a federal candidate's committee may give to state political committees",
 "HB 1085": "a bill to bar new carbon dioxide pipeline permits until federal safety rules were final",
 "HB 1204": "a bill to let the Legislature's audit committee issue subpoenas on its own",
 "HB 1228": "a bill to require an environmental impact statement before any carbon dioxide pipeline permit",
 "SB 83": "which made a first drug ingestion offense a misdemeanor instead of a felony",
 "SB 116": "which wrote street racing and stunt driving offenses into criminal law",
 "SB 8": "which created the crime of watercraft homicide for deaths caused by drunk or drugged boating",
 "SB 59": "which set a schedule of felonies for banned items found on state prison inmates",
 "SB 201": "a bill to bar state candidates from taking money raised for a federal campaign",
 "SB 100": "which allowed concealed pistols and pepper spray on public college and technical school campuses",
 "SB 6": "which let the housing infrastructure fund lend money to build a school",
 "SB 164": "which made it a crime to spread an undisclosed deepfake about a candidate within 90 days of an election",
 "SB 216": "which capped yearly growth in the taxable value of owner-occupied homes at three percent through 2031",
 "SB 144": "which required legislative approval before Game, Fish and Parks makes big purchases",
 "HB 1062": "which opened the county voter registration file to the public and added absentee ballot records to it",
 "HB 1066": "which tightened what counts as living in South Dakota for voter registration",
 "HB 1218": "which stopped local governments barring their own staff from carrying a concealed gun at work",
 "HB 1132": "a bill to let child care workers qualify for child care assistance regardless of income",
 "SB 2": "which paid $650 million for a new men's prison in Minnehaha County",
 "HB 1084": "which hid the home details of judges and police from the public voter file",
 "HB 1064": "which allowed direct sales of custom-slaughtered uninspected meat once federal law permits them",
 "HJR 5002": "a resolution to ask voters to remove Medicaid expansion from the state constitution",
 "HB 1103": "a bill to end an exception letting water systems draw deep groundwater faster than it refills",
 "SB 85": "a bill to require a public vote on every school property tax increase above the usual limit",
 "HB 1068": "a bill to let pharmacists hand out ivermectin and hydroxychloroquine without an individual prescription",
 "HB 1153": "a bill to let health care workers and institutions refuse services that violate their conscience",
 "HB 1227": "which doubled the yearly fee on electric cars from $50 to $100",
 "HB 1105": "a bill to stop property covenants from blocking health care services in underserved areas",
 "HB 1209": "a bill to require every employer to check new hires through E-Verify",
 "HB 1171": "a bill to make blood banks ask donors about COVID-19 vaccination and label the blood",
 "SB 63": "which created a state office of apprenticeship",
 "HB 1151": "a bill to ban kratom",
 "HB 1219": "which required state agencies to provide an interpreter in a contested hearing",
 "HB 1173": "a bill to make carbon dioxide pipeline companies prepare and pay for an environmental impact statement",
 "HB 1182": "a bill to require fertility clinics to report yearly counts of embryos created and destroyed",
 "HB 1010": "a bill to bar holding a phone to make calls while driving",
 "HB 1217": "a bill to bar schools and colleges from using public money to support unions",
 "HB 1222": "a bill to bar economic development board members from owning companies the board funds",
 "HB 1210": "a bill to ban COVID-19 vaccine requirements",
 "HB 1163": "a bill to ban requiring vaccines made with genetic material",
 "HB 1275": "a bill to require app stores to verify users' ages and get a parent's consent for minors",
 "HB 1246": "a bill to ban secrecy agreements between governments and data center developers",
 "HB 1278": "a bill to stop statewide officials and legislators taking campaign money from their own top staff",
 "HB 1113": "a bill to create down payment loans for buying manufactured homes",
 "HB 1082": "which made school meals free for students who qualified for reduced-price meals",
 "HB 1244": "which paid $500,000 for a program keeping at-risk students on track to graduate",
 "SB 113": "which made it a felony to stop someone practicing their religion by force",
 "SB 214": "which put the statewide voter registration file online every week",
 "SB 44": "which gave the attorney general subpoena power in child exploitation and human trafficking cases",
 "SB 76": "which let the housing infrastructure fund lend money for airports",
 "SB 198": "a bill to ban student cell phone use during the school day",
 "SB 159": "which raised the marriage age to eighteen with a narrow court-approved exception",
 "SB 106": "which raised the money held back for costly special education cases",
 "SB 245": "which set up a state fund to cut property taxes on owner-occupied homes",
 "HB 1138": "a bill to require licensing of agencies that send aides into people's homes",
 "SB 67": "a bill to create a state office of apprenticeship",
 "SB 50": "a bill to bar county assessors from using drones to value property",
 "SB 177": "a bill to refund sales tax to data center operators",
 "SB 156": "a bill to set eighteen as the minimum age to marry",
 "SB 196": "a bill to require tribal history and culture in the state's school standards",
 "SB 54": "which cut the share of cigarette tax money going to tobacco prevention",
 "SB 202": "a bill to create a standing fund for rural water projects",
 "SB 70": "which raised the cap on extra state aid for thinly populated school districts to $137,000",
 "SB 157": "a bill to require contractors on public projects to prove they carry workers' compensation insurance",
 "SB 188": "a bill to end no-excuse absentee voting",
 "HB 1092": "which paid $500,000 for stipends for student teachers",
 "SB 62": "which made state employees report suspected fraud, theft and conflicts of interest",
 "HB 1208": "which limited people who register to vote from a mailbox address to federal races only",
 "SB 42": "which raised the penalties for smuggling drugs and phones into prisons",
 "SB 195": "a bill to make the 2023 sales tax cut permanent",
 "SB 150": "a bill to let a debtor shield personal property worth up to $12,000 from creditors",
 "SB 126": "a bill to raise the property tax exemption for totally disabled veterans",
 "SB 118": "a bill to put at least $100 million a year into a fund to cut homeowners' property taxes",
 "SB 211": "a bill to end surprise bills from ambulances outside a patient's insurance network",
 "HJR 5001": "a resolution to ask voters to narrow when private land may be taken for public use",
 "HB 1099": "which took an approved psilocybin medicine out of the state's most restricted drug list",
 "HB 1220": "which set up state licensing for sellers of vapes and other nicotine products",
}
