CLOSE = {
 1543982: "The Senate passed it 24-8, and a later House rewrite became law.",
}
EFFECTS = {
 "SB 6002": "which creates a state immigration enforcement office directing how local police work with federal agents",
 "HB 618": "which bars a person from holding two local elected offices at the same time",
 "HB 120": "which creates the crime of deliberately blocking a state protective services officer",
 "HB 22": "which requires every local governing body to set aside time for public comment at each meeting",
 "SB 694": "which raises the top consumer loan interest rate from 30 to 36 percent a year",
 "SB 690": "which requires school districts to let virtual school students play sports where the association allows",
 "HB 749": "which makes driving with certain out-of-state licenses issued only to people here illegally a misdemeanor",
 "HB 1237": "which bars race-based rules for who sits on state boards",
 "SB 955": "the Medical Ethics Defense Act, which lets providers refuse care that goes against their beliefs",
 "SB 880": "which bars state pollution limits unless the best science shows a direct link to bodily harm",
 "HB 612": "which cuts what a permit applicant must do to make up for harm to wetlands and streams",
 "SB 449": "which says Tennessee law does not ban birth control or fertility treatment",
 "SB 376": "which bars four-year colleges from treating people differently by race, ending race-conscious admissions",
 "SB 799": "which requires statewide parties to pick candidates in primary elections",
 "HB 1332": "which lowers the handgun carry permit age from 21 to 18",
 "SB 750": "which requires a report by July 2026 on crime linked to people in the country illegally",
 "SB 1360": "which widens lawsuit protections for makers and sellers of guns and accessories",
 "SB 626": "which lets counties get more time to finish counting provisional ballots",
 "SB 1004": "which spells out which medical conditions qualify as a serious risk under the criminal abortion law",
 "SB 1034": "which protects city and county seals with historic imagery from removal without state permission",
 "HB 910": "which shuts down the Human Rights Commission and moves its work to the attorney general",
 "SB 227": "which lets a charity that houses someone in the country illegally be sued for crimes that person commits",
 "HB 622": "which bars local governments from using race, sex or age in hiring decisions",
 "SB 670": "which allows changes to small or artificial isolated wetlands without permits",
 "SB 1084": "the Dismantling DEI Departments Act, which bars diversity offices and preferences in government and public colleges",
 "SB 392": "which creates the crime of human smuggling for financial gain",
 "HB 132": "which lets the General Assembly end a governor's state of emergency by joint resolution",
 "SB 674": "which bars cities and counties from setting rules on pay, hours or working conditions beyond state law",
 "SB 218": "which presumes against releasing a person charged with a gun felony or serious injury on a promise to appear",
 "SB 350": "which bars landlords from stopping renters having guns in their home or car",
 "HB 2070": "the Tennessee Energy Freedom Act, which blocks most climate lawsuits over coal, oil or gas emissions",
 "HB 1665": "which bars health insurers from requiring providers to ask minors gender identity questions",
 "HB 1705": "which requires every state and local government employer to use E-Verify from July 2026",
 "HB 1704": "which makes staying in Tennessee more than 90 days after a final federal removal order a crime",
 "SB 2364": "which makes discrimination complaints filed with the attorney general confidential",
 "SB 1464": "which keeps secret the names of officers taking part in federal immigration enforcement",
 "SB 2222": "which lets people sue someone who paid a protester for damage the protester caused",
 "HB 1784": "which sets January 22 as Sanctity of Life Day",
 "HB 1971": "which narrows the law letting people ask a court to declare a government action unlawful to local bodies",
 "SB 1619": "which closes the route for election offices to take private money",
 "SB 2031": "which lets a person sue a provider over gender transition care they were coerced into",
 "SB 1788": "which bars moving a homeless person to another jurisdiction without its written agreement",
 "HB 2018": "which requires sheriffs under federal 287(g) agreements to honor immigration detainers",
 "HB 2569": "which lowers to 50 the age at which hospitals must offer discharged patients a flu shot",
 "SB 2441": "which requires the state to step in when a virtual school keeps failing",
 "SB 2087": "which requires principals to tell every parent when a class is cleared because of a violent student",
 "HB 2616": "which lets local governing bodies interview director-level candidates behind closed doors",
 "SB 2348": "which sets library specialist staffing rules for high schools by size",
 "SB 1858": "which gives the legislature 90 days instead of 15 to fix a redistricting plan a court faults",
 "HB 754": "which makes gender clinics report every gender transition procedure to the state",
 "SB 2459": "which bars the children's services department from asking foster parents how many guns they own",
 "SB 2412": "which lets the attorney general sue to enforce the rules on abortion pills, with fines up to $1 million",
 "HB 2219": "which requires every county sheriff to sign a federal 287(g) immigration enforcement deal",
 "SB 1665": "which widens the school pronoun law to cover honorifics such as Mr. or Ms.",
 "SB 1915": "which requires counties and cities to verify every adult benefit applicant is a citizen or legally present",
 "SB 1587": "which makes it a crime to let a person in the country illegally drive a commercial vehicle",
 "SB 1713": "which requires yearly certification that governments and colleges used no diversity preference",
 "HB 1668": "which creates the crime of jugging, following someone from a bank or store to steal their cash",
 "SB 1868": "which caps state custody of a child for treatment at six months, extendable once",
 "SB 468": "which defines sex, male and female in state law and keeps some single-sex spaces separate",
 "SB 1747": "which makes recklessly firing a gun into the air at a public gathering a misdemeanor",
 "HB 7002": "which lets lawmakers redraw congressional districts at any time, not just after a census",
 "HB 7003": "which redrew Tennessee's congressional district lines in 2026",
 "HB 601": "which opens a late-stage innocence appeal to people who pleaded guilty",
 "SB 336": "which changed the child support condition for restoring voting rights to twelve months of compliance",
 "HB 1093": "which raises the penalty for machine gun conversion parts to a Class C felony",
 "HB 773": "which requires websites carrying official legal notices to be free to view",
 "SB 229": "which charges political campaign committees a $150 yearly fee",
 "SB 2028": "which bars cities and counties from setting rules on how wildlife may be taken",
 "HB 1194": "which extends the work authorization law to almost every private employer",
 "SB 2040": "which bars an owner from controlling a pharmacy plus both a health insurer and drug-benefit manager from 2028",
 "HB 1271": "which requires cities and counties to define sex and gender in their rules by physical traits at birth",
}
