OPEN = {
 1569381: ("Voted to pass Senate Bill 1257", "Voted against passing Senate Bill 1257"),
 1571090: ("Voted to pass House Bill 1586", "Voted against passing House Bill 1586"),
}
ROLLS = {
 1558765: {"yea": "Voted for House Joint Resolution 98, which asked Congress for a constitutional convention to limit federal spending and set term limits. The Texas House backed the request 86-57, and it became Texas's official application to Congress.",
           "nay": "Voted against House Joint Resolution 98, which asked Congress for a constitutional convention to limit federal spending and set term limits. The Texas House backed the request 86-57, and it became Texas's official application to Congress."},
 1568736: {"yea": "Voted for House Joint Resolution 98, which asked Congress for a constitutional convention to limit federal spending and set term limits. The Texas Senate backed the request 17-14, and it became Texas's official application to Congress.",
           "nay": "Voted against House Joint Resolution 98, which asked Congress for a constitutional convention to limit federal spending and set term limits. The Texas Senate backed the request 17-14, and it became Texas's official application to Congress."},
 1576825: {"yea": "Voted to pass Senate Bill 11, which lets school boards create a daily school prayer and religious-reading period. The bill became law after the Texas House passed it 88-48.",
           "nay": "Voted against Senate Bill 11, which lets school boards create a daily school prayer and religious-reading period. The bill became law after the Texas House passed it 88-48."},
 1524539: {"yea": "Voted to pass Senate Bill 11, which lets school boards create a daily school prayer and religious-reading period. The bill became law after the Texas Senate passed it 23-7.",
           "nay": "Voted against Senate Bill 11, which lets school boards create a daily school prayer and religious-reading period. The bill became law after the Texas Senate passed it 23-7."},
 1581609: {"yea": "Voted yes on the final version of Senate Bill 17, which bars governments, companies and certain people tied to hostile countries from buying Texas property. The Texas House adopted the compromise 85-57, and it took effect September 1, 2025.",
           "nay": "Voted no on the final version of Senate Bill 17, which bars governments, companies and certain people tied to hostile countries from buying Texas property. The Texas House adopted the compromise 85-57, and it took effect September 1, 2025."},
 1582092: {"yea": "Voted to accept the Senate's version of House Bill 121, a school safety bill that makes districts renew any exception to the armed officer rule yearly. The House agreed 97-38, and it took effect September 1, 2025.",
           "nay": "Voted against accepting the Senate's version of House Bill 121, a school safety bill that makes districts renew any exception to the armed officer rule yearly. The House agreed 97-38, and it took effect September 1, 2025."},
 1582405: {"yea": "Voted yes on the final version of Senate Bill 37, which gives public university boards control over core courses, provost hires and faculty senates. The Texas House adopted the compromise 83-47, and it took effect September 1, 2025.",
           "nay": "Voted no on the final version of Senate Bill 37, which gives public university boards control over core courses, provost hires and faculty senates. The Texas House adopted the compromise 83-47, and it took effect September 1, 2025."},
 1582950: {"yea": "Voted yes on the final version of Senate Bill 2024, which bans vapes packaged or shaped to appeal to children and vapes made in China. The Texas House adopted the compromise 96-35, and it took effect September 1, 2025.",
           "nay": "Voted no on the final version of Senate Bill 2024, which bans vapes packaged or shaped to appeal to children and vapes made in China. The Texas House adopted the compromise 96-35, and it took effect September 1, 2025."},
}
EFFECTS = {
 "HJR 4": "a proposed constitutional amendment blocking taxes on securities trades",
 "SB 14": "which created a governor's office to cut needless agency rules and ended court deference to agencies",
 "SB 2": "which created education savings accounts families can use for private school tuition",
 "SJR 18": "a proposed constitutional amendment permanently barring state taxes on capital gains",
 "HB 223": "which makes cities seek competing offers for lobbying contracts",
 "HB 5033": "which ends state car emissions inspections only if the federal requirement is removed",
 "SB 1257": "which makes health plans that cover a gender transition procedure also cover its side effects and any reversal",
 "HB 521": "which tightens the rules for curbside voting, including a sworn statement of need",
 "HB 493": "which bars people convicted of first- or second-degree felonies from serving as poll watchers",
 "HB 1586": "which makes the state post the school vaccine exemption form online for anyone to print",
 "HB 5115": "which raises certain election fraud from a misdemeanor to a second-degree felony",
 "SB 2284": "which extends the ban on local firearm rules to bows, crossbows and arrows",
 "HB 3441": "which lets people harmed by a vaccine sue its maker if the maker advertised it in Texas",
 "SB 21": "which created the Texas Strategic Bitcoin Reserve managed by the comptroller",
 "SB 33": "which bars government offices from using public money to help someone obtain an abortion",
 "SB 965": "which protects a public school employee's religious speech or prayer while working",
 "SB 1036": "which makes home solar sellers register, carry insurance and give buyers five days to cancel",
 "SB 8": "which requires every sheriff who runs a jail to seek a deal letting local officers help enforce immigration law",
 "SB 12": "which bars public schools from diversity duties and from teaching about sexual orientation or gender identity",
 "SB 2835": "which lets cities approve apartment buildings of up to six stories with one stairway",
 "SB 2337": "which makes shareholder advisory firms disclose advice based on environmental or diversity goals",
 "SB 510": "which lets the secretary of state withhold voter-registration money from county officials who miss deadlines",
 "SB 15": "which caps lot-size rules on new subdivisions in large cities at 3,000 square feet",
 "SB 1362": "which bars Texas offices from using red flag gun orders unless state law allows them",
 "SB 2972": "which limits the campus free-speech law to students and employees and bars overnight speech events",
 "SB 17": "which bars governments, companies and certain people tied to hostile countries from buying Texas property",
 "SB 13": "a school library law giving elected school boards final approval of every library book",
 "SB 379": "which barred food aid from buying sugary soft drinks",
 "SB 37": "which gives public university boards control over core courses, provost hires and faculty senates",
}
