E = lambda t: {"eff": t}
Y = lambda t: {"yea": t}
IDX = {
0: E("the PRO Act, a bill to strengthen workers' right to unionize, bar permanently replacing strikers, and override state right-to-work laws on union fees"),
1: Y("Voted to send H.R. 1319, the American Rescue Plan Act, to the President: $1.9 trillion in COVID-19 relief with $1,400 payments, extended jobless benefits, and a bigger child tax credit. The House passed it 220-211."),
2: E("the Bipartisan Background Checks Act, a bill to require a background check on nearly every private gun sale, including at gun shows and online"),
3: E("the Enhanced Background Checks Act, a bill to give dealers at least ten business days, up from three, to wait for a background check"),
4: E("a bill to renew the Violence Against Women Act through 2026 and add housing protections and gun restrictions for convicted abusers"),
5: E("the American Dream and Promise Act, a bill to offer green cards to immigrants brought here as children and others under temporary deportation protection"),
6: E("the Paycheck Fairness Act, a bill to narrow employers' defenses for paying men and women differently and protect workers who discuss pay"),
7: E("a bill to require a federal workplace safety standard against violence in hospitals, nursing homes, clinics, and social service settings"),
8: E("the Access to Counsel Act, a bill to guarantee citizens, green card holders, and visa holders a lawyer when held for extra screening at the border"),
9: E("a bill to make public companies disclose climate risk, political spending, executive pay, and other environmental, social, and governance measures"),
10: E("a bill to let workers win an age discrimination claim by showing age was a motivating factor rather than the sole cause"),
11: Y("Voted for sending S.J.Res. 15 to the President to cancel the true lender rule, which let national banks front loans funded by others and escape state interest rate caps. The House passed it 218-208."),
12: E("a bill to make lenders report credit application data for LGBTQ-owned businesses so fair lending laws can be enforced"),
13: Y("Voted for sending S.J.Res. 13 to the President to cancel a workplace rights agency rule that gave employers evidence and legal reasons for a discrimination finding before settlement talks. The House passed it 219-210."),
14: E("a bill to bar the veterans agency from charging veterans copays for contraceptives that private insurance must cover free"),
15: Y("Voted for sending S.J.Res. 14 to the President to cancel the 2020 EPA rule that had dropped methane limits on new oil and gas sources, restoring those limits. The House passed it 229-191."),
16: E("a bill to limit the President's power to fire inspectors general and strengthen their subpoena and reporting powers"),
17: E("a bill to restore the Federal Trade Commission's power to go to court for refunds from companies engaged in fraud or false advertising"),
18: E("the Women's Health Protection Act, a bill to create a federal right to provide and receive abortion care and bar state restrictions such as waiting periods"),
19: E("the PUMP for Nursing Mothers Act, a bill to extend the right to break time and a private space to pump breast milk to salaried workers"),
20: Y("Voted to send H.R. 3684, the Infrastructure Investment and Jobs Act, to the President: roughly $1 trillion for roads, bridges, rail, transit, broadband, water systems, and the power grid. The House passed it 228-206."),
21: E("the Protecting Our Democracy Act, a bill to tighten limits on presidential pardons and emergency powers and strengthen congressional subpoenas"),
22: Y("Voted to pass the Freedom to Vote: John R. Lewis Act, a bill to expand early and mail voting, make Election Day a holiday, and restore the Voting Rights Act. The House sent it to the Senate 220-203. The Senate never passed it."),
23: E("the Postal Service Reform Act, which ended the requirement to prefund retiree health benefits, tied postal retirees to Medicare, and required six-day delivery"),
24: E("the Honoring our PACT Act, a bill to expand health care and disability benefits for veterans exposed to burn pits and other toxins"),
25: E("the CROWN Act, a bill to bar discrimination based on hair texture or hairstyles associated with race in jobs, housing, education, and federal programs"),
26: {"eff": "the Federal Firefighters Fairness Act, a bill to presume certain cancers and heart and lung conditions in federal firefighters came from the job, easing compensation claims", "close": "The House passed it 288-131; Congress enacted the same provisions in December 2022 in the annual defense bill."},
27: E("the Rights for the TSA Workforce Act, a bill to give airport security screeners the same union bargaining and appeal rights as most federal workers"),
28: E("a bill to ban selling fuel at grossly unfair prices during a declared energy emergency"),
29: E("a bill to let injured federal workers be treated by nurse practitioners and physician assistants under federal workers' compensation, not only doctors"),
30: E("the Protecting Our Kids Act, a bill to raise the buying age for many semiautomatic rifles to 21, ban new large-capacity magazines, and require safe storage"),
31: E("a bill to let federal courts temporarily take guns from someone found to be a danger and fund state red flag laws"),
32: E("a bill to widen access to credit and banking, strengthen lending discrimination rules, and make racial equity a Federal Reserve duty"),
33: Y("Voted for final House passage of the Bipartisan Safer Communities Act, which widened background checks for buyers under 21, funded mental health programs, and closed the dating-partner gun loophole. The House agreed 234-193 and it became Public Law 117-159."),
34: E("the final Honoring our PACT Act, which expanded health care and disability benefits for veterans exposed to burn pits and other toxins"),
35: E("the Women's Health Protection Act of 2022, a bill to create a federal right to abortion care after the Supreme Court overturned Roe v. Wade"),
36: Y("Voted for final House passage of the CHIPS and Science Act, which put about $52 billion into U.S. semiconductor manufacturing and research and boosted federal science funding. The House agreed 243-187 and it became Public Law 117-167."),
37: E("the Assault Weapons Ban of 2022, a bill to make it a crime to sell, make, or import semiautomatic assault weapons and large capacity magazines"),
38: Y("Voted to send H.R. 5376, the Inflation Reduction Act, to the President: Medicare drug price negotiation, a $35 insulin cap, clean energy tax credits, and a 15% minimum corporate tax. The House passed it 220-207."),
39: E("a bill to bar moving federal civil service jobs into new categories outside the merit system"),
40: E("the Presidential Election Reform Act, a bill to require electors be chosen under state law set before election day and narrow grounds for objections in Congress"),
41: E("a bill to raise merger filing fees on the largest deals to fund anti-monopoly enforcement and require disclosure of foreign subsidies"),
42: E("which makes the Small Business Administration report yearly on its own cybersecurity, Chinese-built technology risks, and any breach"),
43: Y("Voted for final House passage of the Patents for Humanity Act of 2022, which writes into law an award that speeds patent proceedings for inventors solving humanitarian problems. The House agreed 396-24 and it became Public Law 117-245."),
44: Y("Voted for sending H.R. 8404, the Respect for Marriage Act, to the President: it repealed the federal man-woman definition of marriage and made states recognize valid same-sex and interracial marriages. The House passed it 258-169, and it became law."),
45: E("the VA Employee Fairness Act, a bill to let doctors and nurses at veterans' hospitals bargain and file grievances over patient care and pay"),
46: Y("Voted to pass H.R. 26, the Born-Alive Abortion Survivors Protection Act, a bill to require medical care for a child born alive after an attempted abortion, with prison for failing. The House passed it 220-210, but the Senate never took it up."),
47: Y("Voted to pass H.R. 2, the Secure the Border Act, a bill to restart border wall building, narrow asylum, limit parole, and require employers to verify workers' legal status. The House passed it 219-213, but the Senate never acted, so it died."),
48: Y("Voted to pass H.J.Res. 44, a resolution to cancel the federal rule treating pistols with stabilizing braces as short-barreled rifles needing stricter registration. The House passed it 219-210, but the Senate rejected it on June 22, 2023, so the rule stayed in force."),
49: Y("Voted to pass H.R. 3941, the Schools Not Shelters Act, a bill to cut federal funding to public schools and colleges that shelter immigrants who entered without being admitted. The House passed it 222-201, but the Senate never acted and the bill died with the 118th Congress."),
50: Y("Voted to pass H.J.Res. 98 by 206-177, a resolution to cancel a labor board rule that made it easier to treat a franchise chain and its owner as joint employers. The Senate agreed, but the president vetoed it on May 3, 2024, and the House override failed."),
51: Y("Voted to pass H.R. 5585, the Agent Raul Gonzalez Officer Safety Act, 271-154, a bill to make fleeing Border Patrol by vehicle near the border a crime punishable by prison. The bill died when that Congress ended."),
52: Y("Voted to pass H.R. 7176, the Unlocking our Domestic LNG Potential Act, a bill to end Energy Department approval of gas exports and treat them as in the public interest. The House passed it 224-200, but the Senate never acted, so it did not become law."),
53: Y("Voted to pass H.R. 3397, the WEST Act, a bill to void the public lands rule that put conservation on equal footing with grazing and drilling. The House passed it 212-202, but the Senate never acted and the bill died."),
54: Y("Voted to pass H.R. 615, the Protecting Access for Hunters and Anglers Act, a bill to block federal land agencies from banning lead ammunition or fishing tackle on their lands. The House passed it 214-201, but the Senate never acted and the bill died."),
55: Y("Voted to pass H.R. 764, the Trust the Science Act, a bill to order the Interior Department to drop the gray wolf from the endangered species list, beyond court review. The House passed it 209-205, but the Senate never acted and the bill died."),
56: Y("Voted to pass H.R. 354, the LEOSA Reform Act, a bill to let qualified current and retired police carry concealed guns in school zones, national parks, and on public transit. The House passed it 221-185, but the Senate never acted, so it did not become law."),
57: Y("Voted to pass H.R. 8282, the Illegitimate Court Counteraction Act, a bill to sanction foreigners who help the International Criminal Court investigate or prosecute Americans or allied citizens. The House passed it 247-155, but the Senate never voted, so the bill died."),
58: Y("Voted to pass H.R. 8070, the House's fiscal year 2025 defense authorization bill, which set Defense Department policy, raised junior enlisted pay, and funded military construction. The House passed it 217-199; its provisions became law through H.R. 5009 in December 2024."),
59: Y("Voted to pass H.R. 7637, the Refrigerator Freedom Act, a bill to bar refrigerator and freezer efficiency standards unless the Energy Department finds them workable and not costlier for consumers. The House passed it 212-192, but the Senate never acted and the bill died."),
60: Y("Voted yes on H.J. Res. 165, a resolution to wipe out the 2024 Title IX rule that extended sex discrimination protections to gender identity and sexual orientation. The House passed it 210-205, but the Senate never voted, so Congress did not repeal the rule."),
61: E("a bill to deny certain federal immigration funds to states and localities that limit information sharing or ignore federal detention requests"),
62: E("the Fix Our Forests Act, a bill to speed federal wildfire work in high-risk areas by exempting many forest projects from environmental review"),
63: E("the Liberty in Laundry Act, a bill to bar clothes washer efficiency rules unless found workable and not likely to raise costs for buyers"),
64: Y("Voted for final House passage of the fiscal year 2025 National Defense Authorization Act, which sets military policy and spending levels for the year and raises junior enlisted pay. The House agreed 281-140 and it became Public Law 118-159."),
65: Y("Voted to pass H.R. 29, the Laken Riley Act, a bill to make federal officers detain immigrants here unlawfully who are charged with theft or burglary. The House passed it 264-159; the Senate's broader version, S. 5, became law instead in January 2025."),
66: Y("Voted to pass H.R. 23, the Illegitimate Court Counteraction Act, a bill to sanction foreigners who help the International Criminal Court pursue Americans or allied citizens. The House passed it 243-140, but the Senate blocked it on January 28, 2025."),
67: Y("Voted to pass H.R. 28, a bill to bar federally funded schools from letting anyone male at birth play on girls' or women's teams. The House passed it 218-206, but the Senate has not passed it."),
68: Y("Voted to pass H.R. 30, a bill to bar entry to and allow deportation of non-citizens for sex offenses, domestic violence, stalking, child abuse, or breaking a protection order. The House passed it 274-145, but the Senate has not passed it."),
69: Y("Voted to pass S. 5, the Laken Riley Act, sending it to the president: it requires jailing immigrants here illegally who are arrested for theft, burglary, or violent crimes. The House passed it 263-156, and it became law on January 29, 2025."),
70: Y("Voted to pass H.R. 471, the Fix Our Forests Act, a bill to speed tree-thinning in high-risk wildfire zones on federal land by skipping full environmental review and limiting lawsuits. The House passed it 279-141, but the Senate has not passed it."),
71: Y("Voted to pass H.R. 21, the Born-Alive Abortion Survivors Protection Act, a bill to require newborn care for a baby born alive after an attempted abortion, with prison for failing. The House passed it 217-204, but the Senate has not passed it."),
72: Y("Voted to pass H.R. 26, the Protecting American Energy Production Act, a bill to bar the President from halting fracking without a law from Congress. The House passed it 226-188, but the Senate never acted, so it did not become law."),
73: Y("Voted to pass H.R. 35, the Agent Raul Gonzalez Officer Safety Act, a bill to make fleeing Border Patrol by vehicle near the border a crime punishable by prison. The House passed it 264-155, but the Senate never acted, so it did not become law."),
74: Y("Voted to pass H.R. 22, the SAVE Act, a bill to require paper proof of U.S. citizenship, such as a passport, to register to vote in federal elections. The House passed it 220-208, but the Senate has not taken it up."),
75: Y("Voted to pass S. 146, the TAKE IT DOWN Act, which makes posting intimate images shared without consent, including deepfakes, a crime and gives platforms 48 hours to remove them. The House passed it 409-2, and it became law on May 19, 2025."),
76: E("the Save SBA from Sanctuary Cities Act, a bill to make the small-business agency move any office out of a sanctuary area within 60 days"),
77: Y("Voted to pass H.R. 2966, the American Entrepreneurs First Act, a bill to limit Small Business Administration loans to citizens, nationals, and green card holders. The House passed it 217-190; the Senate has not acted, so it is not law."),
78: Y("Voted to pass H.R. 4, the Rescissions Act of 2025, canceling about $9.4 billion in approved but unspent foreign aid and public broadcasting money. The House vote was 214-212; the Senate trimmed it, and the smaller package became law July 24, 2025."),
79: Y("Voted to pass H.R. 3838, the House defense policy bill for fiscal year 2026, which set defense policy and authorized Defense Department and nuclear security funding. The House passed it 231-196; this bill never became law, and S. 1071 became the final 2026 defense law."),
80: Y("Voted to pass H.R. 3486, the Stop Illegal Entry Act, a bill to raise prison penalties for illegal entry and re-entry, up to life for those convicted of serious crimes. The House passed it 226-197, but the Senate has not acted, so it is not law."),
81: Y("Voted to pass H.R. 4922, the DC CRIMES Act, a bill to limit D.C. youth-offender sentencing to people under 18 and bar sentences below mandatory minimums. The House passed it 240-179, but the Senate has not acted, so it is not law."),
82: Y("Voted to pass H.R. 3062, a bill to replace the presidential permit for cross-border oil, gas, and power lines with a faster agency certificate. The House passed it 224-203, but the Senate has not acted, so it is not law."),
83: Y("Voted to accept the Senate's version of H.R. 5371 and send the funding bill to the President, ending the 43-day shutdown and funding most agencies into January 2026. The House agreed 222-209, and it became Public Law 119-37 on November 12, 2025."),
84: Y("Voted to pass H.R. 4405, the Epstein Files Transparency Act, ordering the Justice Department to publish its unclassified Jeffrey Epstein investigation records, including flight logs. The House passed it 427-1, the Senate agreed the next day, and it became law on November 19, 2025."),
85: E("which cancelled a federal plan change that had ended new coal leasing in Wyoming's Powder River Basin, reopening that coal to leasing"),
86: E("which cancelled the 2024 decision closing about 1.2 million acres of the Arctic National Wildlife Refuge to oil and gas leasing, reopening it to drilling"),
87: Y("Voted to pass S.J.Res. 80 and send it to the President, cancelling the 2022 plan that had closed about 48% of the National Petroleum Reserve in Alaska to drilling. The House passed it 216-209, and it became Public Law 119-47 on December 5, 2025."),
88: Y("Voted to pass H.R. 5214, a bill to require pretrial jail for violent crimes in Washington, DC and bar no-cash release for other public-safety crimes. The House passed it 237-179, but the Senate has not acted, so it is not law."),
89: Y("Voted to pass H.R. 1949, the Unlocking our Domestic LNG Potential Act, a bill to end Energy Department approval of gas exports and treat them as in the public interest. The House passed it 217-188, but the Senate has not acted, so it is not law."),
90: Y("Voted to pass the National Defense Authorization Act for Fiscal Year 2026, placed into S. 1071, setting defense policy and spending for the Defense Department, military construction, and nuclear security. The House passed it 312-112, the Senate agreed, and it became Public Law 119-60 on December 18, 2025."),
91: Y("Voted to pass H.R. 3898, the PERMIT Act, a bill to speed Clean Water Act permits, limit states' power to block projects, and drop groundwater and rain-only streams from protection. The House passed it 221-205, but the Senate has not acted, so it is not law."),
92: E("the Protect America's Workforce Act, a bill to cancel the March 2025 executive order that stripped union bargaining rights from most federal workers"),
93: Y("Voted to pass H.R. 3668, a bill to make federal energy regulators the sole lead agency for reviewing gas pipelines and export terminals and end states' water quality sign-off. The House passed it 213-184, but the Senate has not acted, so it is not law."),
94: Y("Voted to pass H.R. 4371, the Kayla Hamilton Act, a bill to require locked placement for immigrant children 12 and older with gang tattoos or serious criminal records. The House passed it 225-201, but the Senate has not acted, so it is not law."),
95: E("the Main Street Parity Act, a bill to lower the down payment a small business must put up for SBA property loans"),
96: E("a bill to let states spend federal welfare block grant money on pregnancy centers that promote carrying a pregnancy to term"),
97: Y("Voted to pass H.R. 7147, a stopgap funding bill for the Department of Homeland Security. The House passed it 220-207; after Senate changes it became law as Public Law 119-86 on April 30, 2026."),
98: E("the PROTECT Taiwan Act, a bill to seek China's exclusion from six international financial bodies if the President reports China is threatening Taiwan"),
99: E("a bill to direct the Energy Department to secure the supply of minerals it considers essential to U.S. energy security"),
100: E("which requires proof of citizenship to register and photo ID to vote in federal elections"),
101: E("a bill to make the White House budget office rewrite the rules agencies follow when publishing influential information"),
102: E("a bill to change how the Energy Department sets appliance efficiency standards, adding cost factors it must weigh"),
103: E("the Tribal Trust Land Homeownership Act, a bill to set deadlines for the Bureau of Indian Affairs to process mortgages on tribal trust land"),
104: E("a bill to fund the Department of Homeland Security for the rest of the budget year and end the partial shutdown begun February 14, 2026"),
105: E("a bill to stop federal land agencies from banning or regulating lead ammunition and fishing tackle on federal land and water"),
106: E("a bill to set up a federal commission on crime and immigration in Washington, DC and a federal cleanup program for its public areas"),
107: E("the Pay Our Homeland Defenders Act, a bill to fund the Department of Homeland Security and end the partial shutdown that began February 14, 2026"),
108: E("a bill to let the President bar from U.S. ports any ship that has called at a port seized by a Western Hemisphere country"),
109: E("the FIRE Act, a bill to change how wildfire smoke and other exceptional events count under the Clean Air Act"),
110: E("which renews foreign surveillance powers under FISA until April 2029 with added Section 702 protections"),
111: E("the 2026 farm bill, a bill to renew Agriculture Department crop support, conservation, food aid, and rural development programs through 2031"),
112: E("a bill to let higher-ethanol gasoline be sold through the summer smog season under a Clean Air Act waiver"),
113: E("the Cashless Bail Reporting Act, a bill to make the Justice Department publish a yearly list of governments that release certain defendants without cash bail"),
114: E("the PROTECT Kids Act, a bill to make federally funded elementary and middle schools get parental consent before changing a student's gender on forms"),
115: E("a bill to widen several veterans and survivors benefits and add an $833.33 monthly allowance for certain disabled veterans"),
116: E("the 2027 Agriculture and FDA appropriations bill, setting the year's funding for the Agriculture Department and the FDA"),
117: E("the Secure America Act, a bill to provide $70 billion through 2029 for immigration enforcement and border security"),
118: E("a bill to move federal payment-integrity work to the Treasury and create a new inspector general for fraud and recovery"),
119: E("the Sunshine Protection Act of 2025, a bill to make daylight saving time permanent"),
120: E("the 2027 State Department and national security appropriations bill, setting the year's funding for the State Department and related programs"),
121: E("a bill to extend through 2031 Social Security projects that help disability insurance recipients return to work"),
122: E("a bill to delay new right whale protection rules for lobster and crab gear from 2028 to 2035"),
123: E("a bill to bar colleges that take federal student aid from boycotting Israel"),
124: Y("Voted to pass the Senate's version of H.R. 1319, the American Rescue Plan Act, $1.9 trillion in COVID-19 relief with $1,400 payments and a larger child tax credit. The Senate approved it 50-49, the House agreed, and it became Public Law 117-2 on March 11, 2021."),
125: Y("Voted to pass H.R. 3684, the Infrastructure Investment and Jobs Act, a bipartisan deal putting roughly $1 trillion into roads, bridges, rail, transit, broadband, water systems, and the power grid. The Senate passed it 69-30, the House later agreed, and it became Public Law 117-58 on November 15, 2021."),
126: E("the Inflation Reduction Act, which let Medicare negotiate drug prices, capped insulin at $35 a month for Medicare patients, and funded clean energy tax credits"),
127: Y("Voted yes at Senate passage of H.R. 8404, the Respect for Marriage Act, which repealed the federal man-woman definition of marriage and made states honor valid same-sex and interracial marriages. The Senate passed it 61-36, the House agreed, and it became Public Law 117-228 on December 13, 2022."),
128: Y("Voted to pass S. 5, the Laken Riley Act, which requires jailing immigrants here illegally who are arrested for theft, burglary, or violent crimes. The Senate passed it 64-35, the House agreed, and it became law on January 29, 2025."),
129: Y("Voted to pass S. 331, the HALT Fentanyl Act, which permanently puts fentanyl copycat drugs in the strictest federal drug category with fentanyl's penalties. The Senate passed it 84-16, and it became Public Law 119-26 on July 16, 2025."),
130: E("which cancelled an EPA rule requiring plants that move to a lower pollution category to keep controlling persistent toxic air pollutants"),
131: E("which cancelled a 2024 rule that had ended fast-track approvals and short application forms in bank merger reviews"),
132: Y("Voted to pass S.J.Res. 7, a resolution to cancel the FCC rule letting schools and libraries lend Wi-Fi hotspots using federal internet discounts. The Senate passed it 50-38, but the House never voted on it, so the rule stayed in place."),
133: Y("Voted to pass H.J.Res. 60, sending it to the President: it repealed the National Park Service rule tightening off-road vehicle limits at Glen Canyon National Recreation Area around Lake Powell. The Senate passed it 50-43, and it was signed on May 23, 2025 as Public Law 119-13."),
134: E("the GENIUS Act, which set the first federal rules for payment stablecoins, requiring approved issuers to back each coin one-for-one with cash or safe assets"),
135: E("a resolution to end the national energy emergency the President declared on January 20, 2025 to speed domestic energy projects"),
136: Y("Voted to pass S. 2296, the National Defense Authorization Act for Fiscal Year 2026, as amended by the Senate, setting defense policy and authorizing Defense Department and nuclear security funding. The Senate passed it 77-20, but the House held it at the desk without voting, so it has not become law."),
137: E("a resolution to end the national emergency declared February 1, 2025 that added a 25% tariff on most Canadian imports and 10% on Canadian energy"),
138: Y("Voted for sending H.J.Res. 131 to the President, cancelling the decision that limited oil and gas leasing in the Arctic National Wildlife Refuge and opening more of it to drilling. The Senate passed it 49-45."),
139: E("the Secure America Act, a bill to provide $70 billion through 2029 for immigration enforcement and border security"),
}
