EFFECTS = {
 "HB 49": "which lets more people with a felony record serve on a Utah jury",
 "HB 100": "which gives free school lunch to students who already qualify for a reduced-price meal",
 "HB 119": "which stops homeowners associations banning rooftop solar outright on detached houses",
 "HB 267": "which barred state and local governments from bargaining with public worker unions",
 "HB 403": "which orders the state to seek federal permission to stop food stamps being spent on soft drinks",
 "SB 284": "which orders the state to seek federal permission for Medicaid to pay for doulas",
 "HB 251": "which makes the state pollinator planting program permanent and pays up to 75% of costs",
 "HB 355": "which widens what sand, gravel and rock quarries may do over local government objections",
 "HB 233": "which bars schools from letting groups that perform abortions teach any health lesson",
 "HB 402": "which bans nine food additives, including Red No. 3, from school food from the 2026-2027 school year",
 "HB 300": "which makes mail voters write ID digits on the envelope and requires opting in to mail ballots from 2029",
 "SB 262": "which creates interest-free shared appreciation loans of up to $150,000 for first-time home buyers",
 "SB 165": "which adds hearings, a cost study and a public vote before a city may start its own internet service",
 "HB 360": "which lets the largest cities use state housing money to buy, fix and sell single-family homes",
 "HB 263": "which makes the video of ballot processing a public record",
 "SB 78": "which creates a state ombudsman to investigate complaints about homeless service providers",
 "SB 297": "which tightens state oversight of residential programs that house children away from home",
 "SB 277": "which ends the State Records Committee and moves records appeals to a state director",
 "SB 181": "which limits how big a parking space a city may require at a house or townhome",
 "HB 37": "which lets cities grant density bonuses for owner-occupied homes to meet housing rules",
 "HB 477": "which says speaking at a school board meeting cannot by itself count as school trespass",
 "HB 60": "which narrows the reasons the state engineer may use to deny a new water right",
 "HB 192": "which removes the state's limits on what a vehicle safety inspection station may charge",
 "HB 296": "which lets a water supplier count water set aside for the Great Salt Lake toward conservation",
 "HB 404": "which lets landlords set aside shared housing for one sex at birth",
 "SB 69": "which widens the school phone ban to the whole school day, including lunch and recess",
 "HB 330": "which gives a new legal defense to people and companies who followed a permit or government order",
 "SB 68": "which lets businesses sued over inaccessible websites sue back if the lawsuit was abusive",
 "HB 174": "which ends the path that let some minors start cross-sex hormones from January 2027",
 "SB 58": "which requires schools to tell parents of unexcused absences within two days and track chronic absence",
 "HB 209": "which lets voters without proof of citizenship vote only in federal races from November 2026",
 "HB 48": "which lets a court send a teen convicted of aggravated murder to an adult prison",
 "HB 259": "which gives parents the right to see all of their minor child's medical records",
 "HB 337": "which raises the cigarette tax to $2.20 a pack and the vape tax to 71 percent from July 2026",
 "SB 292": "which caps pain and suffering damages from self-driving cars at $1 million",
 "SB 295": "which applies the ban on diversity, equity and inclusion programs to school clubs",
 "SB 252": "which requires low-water grass and efficient sprinklers on state building grounds",
 "SB 314": "which tells the state health department to teach the public about sleep health",
 "HB 106": "which cuts the income tax rate from 4.55 to 4.5 percent and widens the child tax credit",
 "HB 124": "which protects the work contact details of teachers and other school staff",
 "HB 252": "which bars jails and prisons from starting cross-sex hormones or surgery for people in custody",
 "HB 264": "which ends the state clean energy tax credit for systems put in service after 2027",
 "HB 269": "which requires public colleges to assign single-sex dorm units by sex at birth",
 "HB 294": "which takes away health departments' power to issue group orders such as quarantines during an outbreak",
 "HB 418": "which gives people more control over their own social media data from July 2026",
 "HB 390": "which bars public colleges from treating religious or political student groups worse",
 "HB 195": "which limits when the state may keep a person's gun after a plea deal",
 "HB 207": "which adds five years to sentences for each earlier sex crime conviction",
 "SB 327": "which said state collective bargaining protections cover private-sector workers",
 "HB 274": "which pushes water suppliers to charge more for heavy use by July 2027",
 "HB 226": "which requires jails to tell immigration agents before releasing certain people in the country unlawfully",
 "HB 222": "which shields people and companies from lawsuits over climate change",
 "HB 214": "which makes it harder to sue gun makers and sellers when someone misuses a gun",
 "SB 234": "which bars state pollution limits stricter than federal standards",
 "HB 419": "which makes people who sue to block a coal mining permit post a bond first",
 "SB 174": "which lets health care workers refuse services that go against their religious beliefs or conscience",
 "HB 471": "which makes Medicaid expansion adults prove they met work rules from January 2027",
 "HB 273": "which sets rules for classroom technology, including limits on screen time and artificial intelligence",
 "SB 153": "which made most private voter records public on May 25, 2026",
 "HB 540": "which requires one searchable website for all public court records from 2027",
 "HB 185": "which sets up a fund the attorney general may use to fight federal climate rules",
 "HB 76": "which requires large data centers to report their water use",
 "HB 331": "which widens the terrorism crime to cover acts, not just threats, and bans masks to hide from police",
 "HB 136": "which requires police to tow a car when the driver has no license and none can be confirmed",
 "HB 188": "which requires a school to send a student to court after a third drug possession offense at school",
 "HB 436": "which gives cities whose housing grew 2.5% or more extra priority for state road money",
 "HB 204": "which requires public colleges to excuse students from tests that clash with sincere religious beliefs",
 "HB 54": "which requires boaters to take a short yearly state safety course from 2027",
 "HB 84": "which lets adults 21 and older carry a hidden gun at a college without a permit",
 "HB 539": "which adds human trafficking and abuse of a vulnerable adult to domestic violence crimes",
 "HB 357": "which extends the consumer privacy law to carmakers from model year 2030",
}
