OPEN = {1558252: ("Voted to pass the final version of Senate Bill 5041", "Voted against passing the final version of Senate Bill 5041"),
 1558618: ("Voted to pass the final version of Senate Bill 5041", "Voted against passing the final version of Senate Bill 5041"),
 1558685: ("Voted to approve the compromise version of House Bill 1217", "Voted against the compromise version of House Bill 1217"),
 1558684: ("Voted to approve the compromise version of House Bill 1217", "Voted against the compromise version of House Bill 1217")}
EFFECTS = {
 "HB 1524": "which widens who counts as an isolated worker entitled to a panic button and harassment training, adding anyone whose coworkers cannot respond",
 "SB 5486": "which requires movie theaters to offer closed captioning devices at every captioned showing and larger chains to run open-caption showings",
 "SB 6002": "which sets the state's first limits on automated license plate readers, allowing government use only for listed purposes",
 "HB 1215": "which removes the line in the state's suggested advance directive form that cancelled it during pregnancy",
 "HB 1291": "a bill to stop health plans from making patients meet their deductible before covering labor and delivery care",
 "HB 1177": "which requires the state to serve every family on the child welfare housing assistance waiting list, aiming to end the list",
 "HB 1080": "a bill to make hotels and short-term rentals include every mandatory fee in the advertised room rate",
 "HB 1068": "which gives state prison managers interest arbitration, where a neutral arbitrator settles contract disputes",
 "HB 1081": "which gives homeowners approached by unsolicited buyers the right to a buyer-paid appraisal and a chance to cancel",
 "HB 1494": "which widens the property tax break for new apartment buildings that set aside homes at lower rents",
 "HB 1875": "which lets workers use paid sick leave to prepare for or attend an immigration hearing, their own or a family member's",
 "HB 1696": "which raises the income limit for the Covenant Homeownership Program's down payment help to 120% of county median income",
 "HB 1232": "which tightens health and safety rules for private detention facilities, including nonprofit operators",
 "HB 1423": "a bill to let cities pilot cameras that catch illegally loud vehicles in street-racing enforcement zones",
 "HB 1821": "which lets labor-management committees and union benefit trusts get contractors' payroll records for public works jobs",
 "HB 1622": "a bill to make public employers bargain with unions before adopting artificial intelligence tools that affect pay or reviews",
 "HB 1531": "which makes it state policy that public health responses to contagious disease follow the best available science, including vaccines",
 "HB 1971": "which makes health plans that cover hormone therapy pay for a full year's supply picked up at one time",
 "HB 1644": "which toughens child labor enforcement, with fines of at least $15,000 for a violation that seriously hurts a minor",
 "HB 1747": "which bars employers from rejecting everyone with a criminal record and from looking at records before a conditional job offer",
 "HB 1183": "which changes local building rules so homes cost less to build, including letting insulated walls reach into setbacks",
 "HB 1141": "which gives workers on licensed cannabis farms the right to form a union and bargain as a group",
 "SB 5122": "which makes Washington-based companies send their federal merger filings to the state Attorney General at the same time",
 "SB 5093": "which ends coroner authority over deaths from abortion, premature birth, or stillbirth and repeals the crime of concealing a birth",
 "SB 5662": "which lets cities in large eastern Washington counties waive utility hookup fees for shelters and affordable housing",
 "SB 5525": "a state layoff notice law requiring employers with 50 or more workers to give 60 days' notice of mass layoffs",
 "SB 5480": "which keeps medical debt off credit reports and makes any medical debt that is reported unenforceable",
 "SB 5175": "which delays the deadlines for solar panel makers to fund panel recycling programs to 2030 and 2031",
 "SB 5714": "which makes it license-threatening misconduct for a bail recovery agent to enforce a civil immigration warrant",
 "SB 5651": "which raises the amount in a debtor's bank account protected from creditors from $1,000 to $2,000",
 "SB 5494": "which creates a state program requiring certified firms for renovation work on older homes and buildings with lead paint",
 "SB 5184": "which caps how much off-street parking cities and counties may require, with none for affordable and senior housing",
 "SB 5463": "which requires every self-insured employer to handle injured workers' compensation claims in good faith",
 "SB 5375": "which adds clergy to the people who must report suspected child abuse, with no exception for privileged conversations",
 "SB 5632": "which extends Washington's abortion and gender-affirming care shield law to help such as money, rides, and information",
 "SB 5040": "which gives police officers in every city and county interest arbitration, where a neutral arbitrator settles contract disputes",
 "SB 5217": "the Healthy Starts Act, which makes employers pay workers for breaks to pump breast milk and widens rights for pregnant workers",
 "SB 5104": "which bars employers from using immigration threats to stop workers from claiming wage and labor rights, with fines up to $10,000",
 "SB 5232": "which lets the state keep housing aid flowing to elderly or disabled adults who move onto Social Security",
 "SB 5284": "which makes companies that sell packaging and paper in Washington pay for a statewide recycling program",
 "SB 5313": "which bars landlords from making tenants give up the right to sue or sign nondisclosure agreements about the lease",
 "SB 5503": "which changes how the state labor relations commission handles public-sector union cases, including faster hearings",
 "SB 5101": "which lets hate crime victims and their family members take leave or ask for safety changes at work",
 "HB 1308": "which defines what a personnel file includes and requires employers to give workers a free copy within 21 days",
 "HB 2041": "a bill to cut Apple Health coverage after pregnancy from 12 months to six for people approved from July 2026",
 "HB 2040": "which stops the state clawing back Aged, Blind, or Disabled cash aid when federal disability payments later cover the same months",
 "HB 2039": "which passes all current child support through to families on cash welfare instead of the state keeping most of it",
 "HB 1332": "which makes ride-hailing companies show drivers any bonus paid per trip and provide 24 months of trip receipts on request",
 "HB 1052": "which makes a hate crime provable when bias was part of the reason for an attack, not the sole reason",
 "HB 1213": "which lets workers take paid family leave in four-hour blocks and extends job protection to smaller employers",
 "HB 1409": "which speeds up the required cuts in carbon pollution from transportation fuels under the clean fuels program",
 "HB 1154": "which requires state approval of every landfill permit and renewal, on top of local health department permits",
 "SB 5083": "which caps what state and school employee health plans pay hospitals at 200% of Medicare rates from 2027",
 "HB 1462": "which caps the warming potential of newly made bulk hydrofluorocarbon refrigerants from 2030",
 "HB 1163": "which requires a permit, with fingerprints and a safety course, to buy a firearm in Washington",
 "HB 1491": "which makes cities allow denser housing within walking distance of rail and bus rapid transit stations",
 "SB 5686": "which opens the state's foreclosure mediation program to condo and homeowner association members behind on dues",
 "SB 5041": "which lets striking workers collect unemployment benefits for up to six weeks",
 "HB 1217": "which caps yearly rent increases at 7% plus inflation or 10%, whichever is lower",
 "HB 2411": "which lets state workers receive shared leave when they are hate crime victims or caught up in immigration enforcement",
 "HB 1604": "which sets rules for how local jails search transgender and intersex people, barring searches to learn genital status",
 "HB 1002": "a bill to let county coroner and medical examiner staff get workers' compensation for job-caused post-traumatic stress disorder",
 "HB 1687": "which lets cities and counties create social housing authorities that build and run mixed-income public rental homes",
 "HB 2242": "which locks health plans' preventive care coverage to the federal lists as they stood on June 30, 2025",
 "HB 2355": "which gives nannies, house cleaners, and other domestic workers minimum wage, overtime, written agreements, and notice before firing",
 "HB 2367": "which ends the cap-and-invest exemption for older coal-fired power plants from 2026",
 "HB 2471": "which creates a state union law for private workers that applies only if federal labor law stops covering them",
 "HB 2294": "which voids new property deed clauses that bar a grocery store or pharmacy from opening on the land",
 "HB 1570": "which lets student workers at Western Washington University form unions and bargain",
 "HB 2515": "a bill to make large data centers buy power under rate plans that protect other customers and use 80% new renewable power",
 "HB 2464": "a bill to make private jails and detention centers report deaths, abuse claims, and injuries to the state within a business day",
 "HB 2244": "a bill to open more government records to the public, including toxicology test results and redacted accident reports",
 "HB 2637": "a bill to keep birth dates, home addresses, location data, and ID numbers held by government agencies out of public records",
 "HB 2095": "a bill to presume a driver careless when they hit a pedestrian or cyclist in a crosswalk, bike lane, or sidewalk",
 "SB 5892": "which makes counties send voter list data requests to the Secretary of State and makes leaking the list a felony",
 "SB 5917": "which lets the Department of Corrections supply abortion medications to health care providers across the state",
 "SB 6188": "which lets the state write asbestos worker certification rules that go beyond federal minimums",
 "SB 5855": "which bars police, including federal officers, from wearing face masks while dealing with the public on duty",
 "SB 6081": "which keeps records of a person's sex designation change out of public view",
 "SB 6309": "which speeds up permits for regional transit authorities such as Sound Transit",
 "SB 5925": "which lets the Attorney General demand documents and sworn statements before suing over civil rights, wage, or immigration-limit violations",
 "SB 6026": "which makes cities and counties of 30,000 or more allow homes on land zoned for commercial or mixed use",
 "SB 5068": "which lets prisons and jails hire anyone legally allowed to work in the United States as corrections officers",
 "SB 5520": "which makes it easier for people wrongly convicted of a felony to win compensation from the state",
 "SB 5847": "which protects injured workers' right to choose their own doctor under workers' compensation",
 "SB 5981": "which bars drug makers from blocking delivery of discounted 340B medicines to clinics serving low-income patients",
 "HB 1155": "which voids every noncompete agreement in Washington, including ones signed years earlier",
 "HB 2266": "which makes cities and counties allow shelters and supportive housing wherever homes or hotels are allowed",
 "HB 2165": "which creates the crime of falsely posing as a police officer, including federal officers",
 "SB 6346": "which creates a 9.9% state income tax on individual income above $1 million a year, starting in 2028",
 "HB 2548": "which requires 60 days' notice to the Attorney General before more kinds of hospital and health care mergers and sales",
 "HB 1170": "which makes large artificial intelligence companies label the images, video, and audio their systems create",
 "HB 2320": "which extends Washington's bans on making illegal guns to 3D printers, milling machines, and the digital files that run them",
 "HB 2156": "which lets the Attorney General appoint investigators for economic and financial crimes",
 "HB 1750": "which sets a separate legal test for claims that a local rule makes voting harder for a minority group",
 "HB 1903": "which creates a statewide program to help low-income households pay energy bills through credits on their utility bills",
 "HB 1710": "which makes the Attorney General keep a list of local governments with a recent record of voting bias",
 "HB 1974": "which lets cities and counties set up land banks that buy and hold land for affordable housing",
 "HB 2105": "which makes employers tell workers within five days when federal agents ask to see employment records",
 "HB 2225": "which makes companion chatbot companies tell users they are talking to artificial intelligence and protect children",
 "SB 6182": "which creates a state grant program to keep abortion care available for people who cannot pay",
 "SB 6355": "which creates the Washington Electric Transmission Authority to build more high-voltage power lines",
 "HB 1795": "which limits school restraint and isolation of students to cases of real risk of serious harm to a person",
 "HB 2215": "which brings small fuel suppliers into the cap-and-invest program from 2027",
 "SB 5103": "a bill to make the Clemency and Pardons Board consider faster review for people facing deportation",
 "SB 5557": "which requires hospitals to treat pregnancy emergencies to the standard of care, including ending the pregnancy when that is the treatment",
 "SB 5701": "a bill to give labor-management committees and union benefit trusts access to contractors' payroll records on public works jobs",
 "SB 5023": "a bill to give nannies, house cleaners, and other domestic workers minimum wage, overtime, breaks, and written agreements",
 "SB 5123": "a bill to add ethnicity, homelessness, immigration status, and neurodivergence to groups protected from bias in public schools",
 "SB 5328": "a bill to license pay advance services and cap their fees at $5 per advance and $10 a month",
 "SB 5466": "a bill to create the Washington Electric Transmission Authority to expand the state's high-voltage power lines",
 "SB 5490": "a bill to set rules for searching transgender and intersex people in local jails, barring searches to learn genital status",
 "SB 5215": "a bill to require trucks carrying dirt, sand, or gravel on paved roads to cover their loads by 2028",
 "SB 5576": "a bill to let local governments tax short-term rentals up to 4% to fund affordable housing",
 "SB 5469": "a bill to ban rent-setting software that pools landlords' data to recommend rents and lease terms",
 "SB 5708": "a bill to bar social media apps from showing addictive feeds to minors and to limit late-night notifications to them",
 "SB 5800": "a bill to let the state sell up to $7 billion in bonds for highway projects, repaid from fuel taxes and vehicle fees",
 "SB 5797": "a bill to tax stocks, bonds, and funds worth more than $50 million at $5 per $1,000 of value",
 "SB 5280": "a bill to cap cryptocurrency kiosk transactions at $1,000 a day and fees at $5 or 5%",
 "SB 5581": "a bill to fold walking and biking paths into state and local highway planning",
 "SB 5098": "a bill to ban weapons in public buildings where government staff work, playgrounds, sports fields, and county fairs",
 "SB 5331": "a bill to let the Insurance Commissioner order insurers to repay people they harmed and raise fines to $10,000 per violation",
 "SB 5067": "a bill to lower the blood alcohol limit for drunk driving from 0.08 to 0.05",
 "SB 5972": "a bill to give all jail officers interest arbitration, where a neutral arbitrator settles contract disputes",
 "SB 5993": "a bill to cap interest on medical debt at 1% a year for debt incurred after 2026",
 "SB 5956": "a bill to bar schools from disciplining students based only on automated system scores and from using facial recognition to track them",
 "SB 6184": "a bill to widen housing programs for homeless and at-risk youth, including paying stipends directly to young people",
 "SB 5984": "a bill to make companion chatbot apps tell users they are talking to artificial intelligence and protect minors from harmful content",
 "SB 5061": "a bill to make public works contracts raise their minimum hourly wages each year to match the latest prevailing wage",
 "SB 5906": "a bill to limit immigration enforcement at schools, child care sites, health care facilities, and colleges",
 "SB 6049": "a bill to keep hate crime survivors' identifying details and staff and student survey answers out of public records",
 "SB 6302": "which requires the state to investigate reports of worker misclassification on public works jobs",
 "SB 5496": "a bill to bar businesses from holding more than 100 single-family homes and bar investment firms from buying any",
 "SB 5924": "a bill to let pharmacists prescribe vaccines, birth control, overdose treatments, and drugs for minor conditions from December 2027",
 "SB 5947": "a bill to create a state board to design a health plan covering all medically needed care for every resident",
 "SB 5360": "a bill to make knowingly breaking water pollution, clean air, and hazardous waste laws a felony",
 "SB 5647": "a bill to extend the real estate excise tax exemption to affordable homes sold to low-income households by approved groups",
 "HB 1345": "which lets counties allow one backyard accessory dwelling unit on rural lots outside urban growth areas, with strict limits",
 "HB 2384": "which makes continuing care retirement communities that sell life care contracts file an actuarial study from July 2027",
 "HB 1069": "which makes the state bargain with corrections workers' unions over payments toward extra retirement benefits",
}
