EFFECTS = {
 "AB 1": "a bill to make school report cards use the same score cutoffs and definitions every year",
 "AB 4": "a bill to require civics lessons in public, charter and voucher schools from the 2027-28 school year",
 "AB 2": "which requires every school board to ban pupils' phones during class time by July 2026",
 "AB 5": "a bill to make school boards post their adopted textbook lists online and let residents inspect them",
 "AB 3": "a bill to require schools to teach cursive writing by the end of fifth grade",
 "AB 87": "a bill to require immediate restitution from human traffickers and add related penalties",
 "AB 85": "a bill to make the state recommend revoking supervision whenever a person is charged with a crime",
 "AB 66": "a bill to bar prosecutors from dropping or reducing certain charges without a judge's approval",
 "AB 91": "a bill to split the cost of Milwaukee school resource officers between the district and the city",
 "AB 89": "which raises the penalties for repeat theft and lets prosecutors add up separate thefts",
 "AB 24": "a bill to make sheriffs ask felony jail inmates for proof of lawful presence in the United States",
 "AB 102": "a bill to make college sports teams men's, women's or coed by sex at birth and bar men from women's teams",
 "AB 100": "a bill to make school sports teams boys, girls or coed by sex at birth and bar boys from girls' teams",
 "AB 103": "a bill to require school policies keeping pupils' legal names and pronouns unless a parent files a notarized request",
 "AB 104": "a bill to bar gender transition medical treatment for anyone under 18",
 "AB 162": "a bill to make state job training programs track and publish how well they work",
 "AB 167": "a bill to widen what counts as misconduct that disqualifies a worker from unemployment benefits",
 "AB 73": "a bill to write treatment court and commercial court dockets into state law",
 "AB 164": "a bill to rename unemployment insurance reemployment assistance and tighten weekly job search rules",
 "AB 168": "a bill to tighten identity checks and fraud controls in unemployment insurance",
 "AB 166": "a bill to make every college report graduates' salaries, debt and graduation rates each year",
 "AB 169": "a bill to make unemployment claimants report every job offer and interview each week",
 "AB 165": "a bill to bar local governments from spending their own money on guaranteed income programs",
 "AB 58": "a bill to allow only the U.S., Wisconsin and agency flags on government and school buildings",
 "AB 211": "a bill to exempt some cigar and pipe bars from Wisconsin's indoor smoking ban",
 "AB 308": "a bill to bar public money from paying for health care for people not lawfully present in the United States",
 "SB 76": "a bill to limit what prosecutors can do with domestic abuse, sexual assault and other listed charges",
 "AB 614": "a bill to write a teacher's authority to remove a disruptive pupil from class into state law",
 "AB 617": "a bill to change absentee voting rules, including letting voters fix faulty ballot envelopes",
 "SB 10": "a bill to make every public high school let military recruiters into common areas",
 "AB 648": "a bill to create new state aid for school districts that merge from July 2026",
 "AB 644": "a bill to raise state aid for school districts that merge in 2027 through 2029",
 "AB 592": "which sets up a two-year program to train science teachers",
 "AB 582": "a bill to make at least 72 general education credits transfer between state universities and technical colleges",
 "AB 647": "a bill to give school boards that share whole grades a four-year grant of $500 per pupil",
 "AB 385": "a bill to make online political donation platforms verify card security codes and U.S. billing addresses",
 "AB 380": "a bill to stop pay for judges suspended by the Supreme Court over criminal misconduct",
 "SB 146": "a bill to bar anyone convicted of a violent felony from ever changing their name",
 "AB 281": "a bill to require employers doing business with state government to use E-Verify",
 "SB 214": "a bill to let out-of-state health providers treat Wisconsin patients by telehealth after registering",
 "AB 38": "a bill to let taxpayers subtract tips from Wisconsin taxable income for 2025 through 2028",
 "AB 226": "a bill to bar school meals containing five listed additives including red dye 3",
 "AB 377": "a bill to make English Wisconsin's official language",
 "AB 457": "a bill to bar school boards from asking voters for money until their state financial reports are current",
 "AB 461": "a bill to let taxpayers subtract overtime pay from Wisconsin taxable income",
 "AB 840": "a bill to set water, power and cost rules for the largest data centers",
 "AB 415": "a bill to bar state devices from opening apps or AI tools controlled by a foreign adversary",
 "SB 7": "a bill to bar foreign adversary governments and citizens from owning Wisconsin real property",
 "AB 663": "a bill to restrict University of Wisconsin partnerships with foreign adversary countries",
 "AB 662": "a bill to bar state agencies from contracting with businesses owned by a foreign adversary",
 "AB 672": "a bill to make harassing dissidents or journalists on behalf of a foreign government a crime",
 "AB 673": "a bill to bar state-funded facilities from using genetic sequencers made in foreign adversary countries",
 "SB 405": "a bill to let people sue providers who performed gender transition procedures on them as minors",
 "SB 432": "a bill to widen who must report child abuse and what must go to the police",
 "SB 610": "a bill to add homeless shelters to the places where dealing drugs carries an extra penalty",
 "SB 532": "a bill to stop University of Wisconsin campuses charging extra fees for online-only courses",
 "AB 1005": "a bill to base UW-Madison undergraduate admissions mainly on ACT or SAT scores",
 "AB 629": "a bill to let police act against drones that pose a credible threat",
 "SB 485": "which lets group homes and residential care centers for children use video cameras in common areas",
 "AB 446": "which tells state and local governments to consider a set definition of antisemitism in discrimination cases",
 "AB 793": "a bill to create an Office of Internal Audit at the state pension agency",
 "SB 785": "which requires a public website where anyone can look up a teaching license and any investigation results",
 "SB 389": "a bill to end the automatic yearly $325 per pupil increase in school district revenue limits after 2026",
 "SB 431": "a bill to widen when employers may turn someone away because of a pending criminal charge",
 "SB 176": "a bill to give companies a 6.32 percent tax credit on broadband expansion money from 2026 through 2030",
 "SB 36": "a bill to let taxpayers subtract tips from Wisconsin taxable income for 2025 through 2028",
 "SB 420": "a bill to bar local governments from passing rights of nature ordinances",
 "AB 963": "a bill to make large social media companies get parental consent before a minor can hold an account",
 "SB 799": "a bill to give parents more access to their children's health records",
 "AB 996": "a bill to have the state match the federal $1,000 deposit into each Wisconsin child's Trump account",
 "AB 180": "which orders the state to seek federal permission to stop candy and soft drinks being bought with FoodShare",
 "AB 1027": "a bill to tighten food stamp work requirements, raising the age limit from 50 to 65",
 "SB 4": "a bill to set state rules for direct primary care subscription agreements",
 "SB 25": "a bill to bar private criminal complaints against police officers over deaths once the district attorney declines",
 "SB 56": "which lets the state forgive loans to private water utilities used to replace lead service lines",
 "SB 182": "which funds grants to technical colleges to train more emergency medical workers",
 "SB 108": "which sets up a statewide online system for sharing a child's mental health safety plan",
 "SB 94": "a bill to make urging or organizing a riot a felony",
 "SB 106": "which creates a new kind of inpatient psychiatric treatment center for children and young people under 21",
 "SB 41": "a bill to create school safety grants of up to $20,000, with the funding removed before the vote",
 "SB 184": "a bill to bar governments from restricting vehicles or devices because of the energy source that powers them",
 "SB 279": "which funds grants for police agencies to buy a real-time data-sharing platform",
 "AB 35": "which lets a candidate withdraw from the ballot after filing by paying a fee",
 "SB 16": "a bill to bar school districts from joining an athletic association that ignores open records laws",
 "SB 394": "a bill to make damaging a historical monument on public property a felony",
 "SB 384": "a bill to require the same care for a child born alive after an attempted abortion as any newborn",
 "AB 223": "which requires people who collect nomination paper signatures to be Wisconsin voters",
 "SB 287": "a bill to require government agencies to check every new hire through E-Verify",
 "SB 825": "which lets major highway projects clear environmental review earlier with less federal involvement",
 "AB 595": "a bill to require daily voter list checks against license, death and felony records",
}
