CLOSE = {
 1541880: "The Senate rejected the amended bill 16-18, so it did not become law.",
}
EFFECTS = {
 "HB 2710": "the Truth in Giving Act, a bill to make resale stores post who benefits from donated goods",
 "HB 2719": "a bill to end the ban on companies giving money directly to candidates",
 "SB 460": "a bill to let parents opt children out of school vaccine requirements for religious reasons",
 "HB 3276": "a bill to let public water and sewer utilities raise rates yearly without a hearing",
 "HB 3412": "a bill to remove the Legislature from the state's Freedom of Information Act",
 "HB 3446": "a bill to make every public high school help each student file the federal student aid form",
 "HB 2013": "which takes civil service and grievance rights away from new hires in five state agencies",
 "SB 526": "which lets pharmacists prescribe drugs for flu, COVID-19 and RSV confirmed by a simple test",
 "HB 4081": "a bill to create grants for food and hygiene pantries at public colleges",
 "HB 4198": "a bill to make every employer check new hires through E-Verify",
 "HB 5319": "a bill to make camping without permission on public property a crime",
 "SB 641": "which narrows which aboveground storage tanks the state regulates near drinking water",
 "SB 586": "which limits backflow prevention inspections at public water systems to once every three years",
 "HB 4025": "which takes civil service and grievance rights away from new hires in the three health departments",
 "SB 592": "a bill to remove several kinds of storage tanks from the post-2014 chemical spill safety law",
 "SB 548": "a bill to require yearly youth violence prevention training in public schools",
 "SB 579": "a bill to bar Home Rule cities from protecting groups state law does not already protect",
 "SB 718": "a bill to make hospitals publish their prices, facility fees and insurer discount contracts",
 "SB 730": "a bill to make forest carbon offset deals be registered with the state and recorded at the courthouse",
 "HB 2513": "which raises required yearly training for county school board members from seven hours to twelve",
 "HB 3017": "a bill to make counties inspect every ballot-counting machine for modems before early voting",
 "HB 3444": "which repeals the old laws on newborn eye medication and reporting",
 "SB 587": "which doubles the point at which governments must seek competing construction bids to $50,000",
 "SB 963": "a bill to limit when a domestic violence protective order can take away a person's guns",
 "SB 420": "a bill to push utilities to run coal plants at about two thirds of full output year round",
 "HB 4005": "the Workforce Development Act of 2026, which follows federal law on which jobs are closed to workers under 18",
}
